### ISSUE TITLE
Error al instalar rails

### ISSUE THREAD

**Issue by ibaeza1** [IIC2143-2020-2/syllabus#1]
Hola!
Tengo un problema cuando instalo rails
Use gem install rails y dice que se instalo todo bien pero cuando trato de usar el comando rails (como rails -v o algo asi) me sale este error:
C:/RailsInstaller/Ruby2.2.0/bin/ruby.exe: bad interpreter: No such file or directory

Adjunto pantallazo de mi cmd
![image](https://user-images.githubusercontent.com/37149485/90216234-f8c54980-ddcb-11ea-84e9-9f54eddc4f83.png)
Estoy usando wsl.
Que significa este error? Porque dice que se instalo todo bien pero no puedo usar rails.
Revise y si esta el archivo ruby.exe asi que no se por que me sale ese error :(
Gracias!

**Comment by ibaeza1** [comment]
Update:
Cuando hago 
sudo which ruby me sale:
/usr/bin/ruby
Y cuando hago which ruby:
/home/ibaeza1/.rbenv/shims/ruby

Como hago para que sean el mismo path?

**Comment by jerosalazar** [comment]
Hola! Qué versión de ruby tienes? Y que te sale cuando corres `gem install rails`?

**Comment by ibaeza1** [comment]
Al final se arreglo solo (?) jajaja 
Ahora hago rails -v y me sale la version de rails asi que asumo que esta funcionando pero no se por que se arreglo la verdad.

**Comment by jerosalazar** [comment]
Que raro 🤔  Que bueno que se solucionó en todo caso! si vuelve a haber algún problema reabre esta issue
