### ISSUE TITLE
Sort lista de listas

### ISSUE THREAD

**Issue by CataSudo** [IIC2143-2020-2/syllabus#10]
Hola! He estado buscando online, y en python estaba la opción de usar lambda cuando queríamos hacer uso de sort para ordenar una lista de listas por el segundo elemento. Es decir tengo una lista tipo [[student_id, nota],[student_id, nota],...,[student_id, nota] ] y quiero que me haga sort por nota;  ¿Me pueden guiar en como hacer eso?

**Comment by jerosalazar** [comment]
Hola! Te recomiendo que busques como funciona `sort_by` con este método puedes hacer ordenamientos más personalizados
