### ISSUE TITLE
Problema instalación

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2143-2020-2/syllabus#100]
Hola, instalé node de la forma en que nos dicen (se instaló bien) pero cuando pongo rails db:create me sale el error " Could not find a JavaScript runtime".
También me ha salido un error " psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?" 
en el mismo paso que mencione antes. Había instalado todo en windows y me estaba funcionando pero ahora que queria hacerlo con wsl me salieron esos errores.

**Comment by daleal** [comment]
Hola! Esos son dos errores distintos. El primero es porque no tienes instalado `node` en wsl. El segundo es porque no tienes iniciada la base de datos. Para iniciarla, puedes ejecutar `sudo service postgresql start`. Eso iniciará la base de datos.

**Comment by mariovaldesa** [comment]
Node si lo instale en wsl pero me sigue saliendo lo mismo. Y el segundo tambien me sale iniciada la base de datos.

**Comment by mariovaldesa** [comment]
v12.18.3 is already installed.
Now using node v12.18.3 (npm v6.14.6)
me sale eso

**Comment by mariovaldesa** [comment]
pero cada vez que abro un nuevo terminal se olvida nvm pero sigue estando en mis archivos, ya intente con nvm alias default y no funciono

**Comment by daleal** [comment]
A ver, vamos por partes. `nvm` te funciona? O sea, si ejecutas `nvm --help`, te sale el _output_ de ayuda de `nvm`?

**Comment by mariovaldesa** [comment]
Al momento de instalarlo si, pero cada vez que abro una nueva terminal y pongo un comando de nvm me sale Command 'nvm' not found, did you mean: ....

**Comment by mariovaldesa** [comment]
incluso cada vez que abro una nueva terminal lo primero que me sale, sin poner nada antes es Command 'nvm' not found, did you mean: ....

**Comment by daleal** [comment]
Podrías mostrarme el output del comando `cat ~/.bashrc`?

**Comment by mariovaldesa** [comment]
![output_ubuntu](https://user-images.githubusercontent.com/62063962/92192298-a956c400-ee33-11ea-894a-026cba7667e3.jpg)

**Comment by mariovaldesa** [comment]
![image](https://user-images.githubusercontent.com/62063962/92192358-d6a37200-ee33-11ea-9d75-5daa7fd2df5c.png)
lo primero es lo que me sale cada vez que abro el terminal

**Comment by daleal** [comment]
Podrías enviar el _output_ de los siguientes comandos?

```sh
source ~/.nvm/nvm.sh

nvm --help
```

**Comment by mariovaldesa** [comment]
mando mas fotos del output?

**Comment by mariovaldesa** [comment]
![image](https://user-images.githubusercontent.com/62063962/92307139-25e7c080-ef62-11ea-813d-b1efbbb95326.png)
despues de esos comandos me salio todo perfecto! se me crearon dos bases de datos eso si, no tres... no se si eso está bien. Hay alguna forma de no tener que poner ese comando de source ~/.nvm/nvm.sh ?

**Comment by daleal** [comment]
Ya, mira, haz lo siguiente. Ejecuta `nano ~/.bashrc`. Eso debería abrir un editor de texto en tu terminal. Luego, con las flechas del teclado, baja hasta el fondo del archivo. Debería haber una línea que dice `export NVM_DIR="$HOME/.nvm". Borra las líneas después de esa para que esa quede de última línea. Ahora, añade una nueva línea que diga `source ~/.nvm/nvm.sh`. Una vez hecho eso, apreta `ctrl + X`, y luego apreta la tecla `Y` de tu teclado. Cuando hayas hecho todo eso, cierra tu terminal, y al volverlo a abrir, ya debería estar funcionando `nvm`.

**Comment by mariovaldesa** [comment]
![image](https://user-images.githubusercontent.com/62063962/92313863-88f74880-ef9e-11ea-8eb3-23b8cfe5e030.png)
el archivo me quedo asi pero aun no me funciona

**Comment by daleal** [comment]
Reiniciaste tu consola?

**Comment by mariovaldesa** [comment]
sisi incluso reinicie el pc

**Comment by mariovaldesa** [comment]
![image](https://user-images.githubusercontent.com/62063962/92313925-497d2c00-ef9f-11ea-9ea7-deabf9e8c77e.png)
abri la consola y lo primero que me sale es esto de nuevo

**Comment by mariovaldesa** [comment]
hice lo mismo pero con nano ~/.bash_profile y le agregue las siguientes lineas export NVM_DIR=~/.nvm
source ~/.nvm/nvm.sh y me funciono. Está bien o no deberia haber modificado ese archivo? jajajja

**Comment by mariovaldesa** [comment]
hice lo mismo pero con "nano /.bash_profile" y le agregue las siguientes lineas "export NVM_DIR=/.nvm"
"source ~/.nvm/nvm.sh" y me funciono. Está bien o no deberia haber modificado ese archivo? jajajja

**Comment by daleal** [comment]
Está bien!
