### ISSUE TITLE
PG::ConnectionBad: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by Juaconsio** [IIC2143-2020-2/syllabus#101]
Hola, me salta el siguente error despues de ingresar rails db:create
![jicn@LAPTOP-BB74LMQB_ _mnt_c_Users_712ji_Documents_proyecto 03-09-2020 19_56_20](https://user-images.githubusercontent.com/53885988/92184567-95a16280-ee1f-11ea-998a-d581ea0ab43e.png)

**Comment by daleal** [comment]
Hola! Probablemente se debe a que no tienes iniciado el servidor de base de datos en tu computador. Puedes iniciarlo con `sudo service postgresql start`

**Comment by Juaconsio** [comment]
Hola de nuevo, me asegure que el servidor estuviese iniciado y me sigue saltado el mismo error

**Comment by jerosalazar** [comment]
Hola, te funcionó?

**Comment by Juaconsio** [comment]
Si, creo que fue porque tenia postgresql fuera del wsl tambien, desinstale completamente los dos, hice la guia de nuevo y funciono.
