### ISSUE TITLE
duda de ayudantía 2 - paso 8

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#102]
Hola tengo la duda de a qué se refieren con "nombre proyecto" ?
![image](https://user-images.githubusercontent.com/59337116/92260936-ad6ff980-eea6-11ea-91c6-2709abce6009.png)

**Comment by jerosalazar** [comment]
Cuando corres el comando `rails new` este crea una carpeta donde aloja todo el código que genera. `nombre proyecto` hace referencia al nombre que tendrá esta carpeta.

**Comment by Camila-sty** [comment]
Yaa gracias!
esta bien como lo estoy haciendo?
![image](https://user-images.githubusercontent.com/59337116/92275129-87edea80-eebc-11ea-8579-7b422f4c5203.png)
me tira ese error y no entiendo por qué..

**Comment by jerosalazar** [comment]
El nombre tiene que ir sin <>. Por ejemplo `rails new proyecto-bdd` (recuerda también no ponerle espacios o escaparlos con `\ `)
