### ISSUE TITLE
Error en paso 8 de ayudantia 2

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#104]
Hola, hice el paso donde había que poner ```rails new <nombre proyecto> --database=postgresql``` y luego puse ```cd nombre proyecto```, pero no me salía. Así que volví a poner el primer paso, pero ahora me sale algo que no entiendo:
![image](https://user-images.githubusercontent.com/59337116/92284060-3d299e00-eecf-11ea-89c4-16fffd2f6e11.png)
Qué error tengo?

**Comment by jerosalazar** [comment]
te recomiendo que no ocupes espacios en el nombre del terminal porque se toman como argumentos distintos. Si ocupas un espacio en el nombre tienes que escaparlo con `\`
