### ISSUE TITLE
Error al crear base de datos

### ISSUE THREAD

**Issue by fbesoainp** [IIC2143-2020-2/syllabus#105]
Hola al intentar crear la base de datos con el comando rails db:create me da este error: PG::ConnectionBad: FATAL:  password authentication failed for user "postgres".

ya comprobe que el servidor de PostgreSQL esta corriendo y que la contraseña en la configuración es la misma que configure en psql.
![image](https://user-images.githubusercontent.com/53845524/92293136-15e2c900-eeef-11ea-8bee-a9b6132d1c46.png)

**Comment by cchauriye** [comment]
Hola! Probaste cambiando de puerto?

**Comment by cirey1** [comment]
Hola @fbesoainp,

Primero que todo me podrias subir un screenshot de tu database.yml.

Segundo, necesito que ingreses a la consola de postgres con ``` sudo -u postgres psql ```, escribas el siguiente comando ``` \conninfo ```. Porfavor sube un screenshot de este resultado tambien.

Saludos,

**Comment by fbesoainp** [comment]
Hola! esta es mi configuración de database.yml
![image](https://user-images.githubusercontent.com/53845524/92408739-ce3d8680-f114-11ea-84a0-4f684b76a696.png)
probé esta misma config en otro computador y funcionaba perfecto, por lo que desinstale ubuntu e hice todo el proceso de nuevo pero obtuve el mismo error.
esto es lo que obtengo en psql con \conninfo
![image](https://user-images.githubusercontent.com/53845524/92408823-ff1dbb80-f114-11ea-84a2-fdf7f61716fb.png)
todavía no pruebo si cambiar el puerto sirve.

**Comment by cirey1** [comment]
Perfecto. Haciendo referencia a #111, tienes que setear bien tu database.yml. Entonces dado que tienes el puerto 5432 ocupado, tu servidor no puede encontrar la base de datos ahí (Esto puede darse por distintas razones). Tienes que hacer lo siguiente para que te quede funcionando.

1- Tendrás que cambiar tu atributo pool, y colocar solamente un 5.
2- Tendrás que agregar una linea, en donde especifiques tu puerto para la db. Es decir, deberás agregar ``` port: 5433 ```

Tu archivo database.yml, deberia quedar de este estilo.
```
default: &default
  adapter: postgresql
  encoding: unicode
  host: locahost
  port: 5433
  username: postgres
  password: hola123
  pool: 5
```

Inténtalo y me cuentas como te va,

Saludos,

**Comment by fbesoainp** [comment]
Ahí funciono! muchas gracias!!! :)

**Comment by fbpesenti** [comment]
Tenia el mismo problema y agregue la linea del puerto pero igual no puedo crear la base de datos y al tratar de correr el server me aparece esto
![image](https://user-images.githubusercontent.com/48263110/92436160-6c176c80-f17a-11ea-8231-f471f3da0590.png)

Esto me aparece después de poner ` rails db:create`
![image](https://user-images.githubusercontent.com/48263110/92436201-86e9e100-f17a-11ea-90cd-82bc5f1c79fd.png)

Esta es mi configuración de database.yml
![image](https://user-images.githubusercontent.com/48263110/92436237-9ec16500-f17a-11ea-8542-cf584978f95c.png)

esto es lo que obtengo en psql con` \conninfo`
![image](https://user-images.githubusercontent.com/48263110/92436312-c31d4180-f17a-11ea-9966-8cf52dbb1ac9.png)

**Comment by cirey1** [comment]
Hola @fbpesenti,

Actualmente tienes un problema con el encoding de tu base de datos. Para solucionarlo debes seguir los pasos mencionados en esta issue #43. Aquí podrás ver que necesitas agregar una linea a tu default de database definiendo el template con el cual crear tus bases de datos.

Tienes que agregar la linea ``` template: template0 ``` dentro de default, por lo que quedaria asi.

```
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: <la clave que pusiste en el paso 7>
  pool: 5
  template: template0
```

Saludos y cuentame como te va,

**Comment by fbpesenti** [comment]
Si me funcionó muchas gracias!!!!
