### ISSUE TITLE
Ayudantias Grabadas

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2143-2020-2/syllabus#106]

**Comment by DiegoPibe** [comment]
Hola, sorry la duda pero donde quedan las ayudantias grabadas ??? no las encuentro jeje (Siempre escribo la pregunta en el titulo)

**Comment by meretamal** [comment]
Hola 😁 

Las puedes encontrar [acá](https://drive.google.com/drive/folders/1SWY1VmcixYzEVhvSB2EAYKd7V7Z_D_CK?usp=sharing)

**Comment by DiegoPibe** [comment]
Vale muchas gracias <3
