### ISSUE TITLE
Windows WSL paso 7. Error.

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2143-2020-2/syllabus#107]
Hola, Tengo el siguiente problema al ejecutar el paso 7:

psql: error: could not connect to server: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Lo googlie, pero no encontré solución. Alguna sugerencia?
Gracias de antemano

**Comment by daleal** [comment]
#59
