### ISSUE TITLE
Error paso 8 [WSL]

### ISSUE THREAD

**Issue by Etienne99** [IIC2143-2020-2/syllabus#108]
Hola! Al ejecutar bundle install tengo el siguiente error:

root@LAPTOP-SOVN35NH:/# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this
application for all non-root users on this machine.
Could not locate Gemfile

Estoy usando Ubuntu 18.04 en Windows 10. Intenté hacer algunas cosas que encontré googleando pero no ha funcionado nada. ¿En qué me estoy equivocando?

**Comment by daleal** [comment]
Hola! El problema es que, por alguna razón, estás dentro del terminal del usuario `root`. Deberías tratar de entrar a Ubuntu con un usuario que no sea `root`. Así te va a funcionar. Te dejo [este thread](https://github.com/microsoft/WSL/issues/4276) con hartas respuestas al mismo problema, para que lo mires

**Comment by santiagoolivos** [comment]
Hola! Tengo otro problema con el paso 8 luego de ejecutar rails new <nombre proyecto> --database=postgresql me sale un error que no he podido solucionar, es el siguiente:
santiagoolivos@LAPTOP-0PTQJ278:/mnt/c/Users/santi/desktop$ rails new p123 --database=postgresql
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
error: chmod on /mnt/c/Users/santi/desktop/p123/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'

He tratado hartas cosas y me sigue saliendo el mismo error.

**Comment by daleal** [comment]
@santiagoolivos, te pediré que para problemas distintos, abras issues distintas. En cualquier caso, tu problema es exactamente el discutido en #85.
