### ISSUE TITLE
Error con postgresql 

### ISSUE THREAD

**Issue by lewebe** [IIC2143-2020-2/syllabus#109]
![image](https://user-images.githubusercontent.com/62037289/92341362-dbfef780-f093-11ea-91be-d61fc8e82cea.png)
Hola, seguí la guía de instalación pero al llegar al paso 12, no me conectaba al servidor del proyecto. Cerré Ubuntu y lo abri de nuevo, y al intentar meterme a postgresql, no me deja. Tengo problemas para correr el comando del paso 7 y del paso 10

**Comment by daleal** [comment]
Me podrías decir exactamente qué estás usando? `wsl`? `Windows` directamente con el _git bash_? Y dónde instalaste `postgres`?

**Comment by cirey1** [comment]
Hola @lewebe,

Al parecer no tienes instalado PostgreSQL en tu wsl. Hagamos lo siguiente:

1- Utiliza el comando ``` psql --version ```, con esto debería salirte la versión de Postgresql si es que esta bien instalado.
- Si te sale "psql (PostgreSQL) <version>", entonces tienes un problema con las variables de entorno de entorno en tu wsl. Por lo que recomiendo desinstalar PostgreSQL ```  sudo apt-get remove postgresql ``` y volver a instalarlo ``` sudo apt-get install postgresql ```

- Si no te sale la versión, o mas bien, no te reconoce el comando psql. Tienes que instalar PostgreSQL con el comando descrito en el paso anterior. ``` sudo apt-get install postgresql ```

2- Ya instalado PostgreSQL (Te sale la version con psql --version). Tienes que correr el servidor con ``` sudo services postgresql start ```

3- Si se inicio correctamente, entras al bash con ``` sudo -u postgres psql ``` y cambias la password de tu usuario postgres con ```\password```. Aqui quedara seteado tu user postgres con esa password de tu servidor, la cual sera posteriormente utilizada en el proyecto.

4- Si funcionaron los pasos anteriores, estas listo con PostgreSQL y puedes salirte de la consola psql utilizando ```\q```

Cualquier cosa y/o error, porfavor comenta esta issue y pon pantallazos de los errores para poder ir ayudandote,

Saludos,

**Comment by lewebe** [comment]
Hola, el problema era que no tenía instalado PostgreSQL. Lo hice de nuevo pero esta vez me quedé atascado en el paso 11 y 12, pues no me conecta al servidor. Esto es lo que me sale en consola (Ubuntu) 
![image](https://user-images.githubusercontent.com/62037289/92410307-157a4600-f11a-11ea-9ed1-dc69d62462b0.png)
![image](https://user-images.githubusercontent.com/62037289/92410319-21660800-f11a-11ea-9dc4-f6f9b6ccc34a.png)

**Comment by cirey1** [comment]
@lewebe tienes que ubicarte en tu carpeta de proyecto para poder hacer esos comandos. Utiliza cd para moverte a traves de los directorios hasta entrar en la carpeta de tu proyecto.

Intentalo y me dices como te va,
Saludos,

**Comment by lewebe** [comment]
Ahí funcionó! Muchas gracias! Última cosa, le puse de nombre a mi proyecto "proyecto_1"; da lo mismo? Lo puedo cambiar si quiero?

**Comment by cirey1** [comment]
Da lo mismo el nombre. La carpeta donde están tus proyectos puedes cambiarle el nombre pero después se te va a formatear al nombre del repositorio de tu grupo. Asi que no hace mucho sentido cambiarlo ahora.

Saludos y happy coding,
