### ISSUE TITLE
Formato de las lineas de los archivos .txt

### ISSUE THREAD

**Issue by maormeno** [IIC2143-2020-2/syllabus#11]
Hola, cómo es el formato de las líneas de estos archivos? Especificamente del archivo instrucciones.txt; estoy leyendo el archivo y guardando cada linea en un array, pero cuando hago elemento_del_array.length(), me dice (por ejemplo) 11 para la linea "aprobados", pero cuando hago "aprobados\n".length() me dice 10, y estoy usando la condicion elemento_aprobados_del_array == "aprobados\n", por lo que no se me cumple nunca.... cuál será el caracter que me falta?

**Comment by jerosalazar** [comment]
No me quedó muy claro como lo estás manejando, pero te recomiendo que le eches una ojeada al método `chomp` que te sirve para limpiar strings de saltos de líneas y otras cosas. Quizás te sirve para manejar de mejor forma las instrucciones

**Comment by maormeno** [comment]
Gracias!! Justamente preguntaba porque no encontraba un equivalente al strip()
