### ISSUE TITLE
Error para cambiar contraseña y conectar al servidor

### ISSUE THREAD

**Issue by eugeizquierdo** [IIC2143-2020-2/syllabus#110]
Hola!! Tengo dos dudas.
1. Cuando trato de cambiar la contraseña de PostgreSQL, me deja hacerlo, pero luego al ingresar de nuevo, la contraseña válida es la original y no la nueva. 

2. Al ingresar desde el servidor a la carpeta del proyecto, en el paso 8, cuando pongo "bundle install" me aparecen los siguientes errores:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
An error occurred while installing pg (1.2.3), and Bundler cannot continue.
Make sure that `gem install pg -v '1.2.3' --source 'https://rubygems.org/'` succeeds before bundling.

Traté de solucionarlo instalando lo que me dice ahí, pero me sale "extconf failed, exit code 1"

Muchas gracias.

**Comment by cirey1** [comment]
Hola @eugeizquierdo,

Si no me equivoco, creo que iniciaste el proyecto mal. Deberías utilizar el siguiente comando ``` rails new <proyect_name> --database=postgresql ```.

Si no te funciona eso, por favor sube screenshots de tu database.yml y el proceso de seteo de password en psql.

Saludos,

**Comment by eugeizquierdo** [comment]
Pucha, no me resulta. Es que el proyecto lo inició alguien de mi grupo y yo estoy tratando de conectarme a él. 
Al hacerlo como me dices tú me sigue saliendo el siguiente error al poner bundle install:
An error occurred while installing pg (1.2.3), and Bundler cannot continue.
Make sure that `gem install pg -v '1.2.3' --source 'https://rubygems.org/'` succeeds before bundling.

Y al poner rails db:create:
Could not find gem 'rails-controller-testing' in any of the gem sources listed in your Gemfile.

Aquí va lo del cambio de la contraseña, que pareciera ser exitoso, pero cuando me meto denuevo no me resulta esa contraseña.

![image](https://user-images.githubusercontent.com/53871813/92485317-2762f400-f1c1-11ea-981a-212ad6455094.png)


Gracias!!

**Comment by eugeizquierdo** [comment]
Y esta es mi database.yml


default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: '1234'
  pool: 5

production:
  <<: *default
  database: carrete_production

development:
  <<: *default
  database: carrete_development

test:
  <<: *default
  database: carrete_test

**Comment by eugeizquierdo** [comment]
Quizás podría borrar postgres y instalarlo denuevo para hacerlo desde 0 con la contraseña correcta, pero no sé como eliminarlo. 
Gracias!

**Comment by meretamal** [comment]
Hola 😄

Antes de correr `rails db:create` podrías correr `bundle install`?

**Comment by eugeizquierdo** [comment]
Ahí me funcionó!!! Muchas gracias!!!!

Pero lo de la contraseña todavía no me resulta... Osea me funcionó, lo cerré, me vuelvo a meter y no me acepta la nueva contraseña.

**Comment by daleal** [comment]
@eugeizquierdo, podrías darnos un poco más de información? Por ejemplo, cómo estás cambiando la contraseña, tienes Linux, macOS, WSL, Windows normal, etc; exactamente en qué paso no te funciona la contraseña alterada, qué error te arroja?

**Comment by eugeizquierdo** [comment]
Hola! perdón, se me olvidó mandar estos datos, y me sigue sin funcionar.
Tengo un Windows 10, me descargué WSL.  
Cuando cambio la contraseña, me la acepta, y puedo seguir haciendo todo de forma normal, pero cuando ingreso nuevamente, la contraseña que me acepta es la anterior. 

La estoy cambiando así:
![image](https://user-images.githubusercontent.com/53871813/95354804-3d84d280-089b-11eb-8765-50e7a6a792d6.png)

Gracias!
