### ISSUE TITLE
Error en Paso 11 rails db:create

### ISSUE THREAD

**Issue by rkarac** [IIC2143-2020-2/syllabus#111]
Hola, cuando corro el comando rails db:create me aparece:

FATAL:  la autentificacin password fall para el usuario postgres
Couldn't create 'carrete_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: FATAL:  la autentificacin password fall para el usuario postgres

Creo que a alguien en la ayudantía de Setup le pasaba lo mismo pero no aparecía como lo resolvieron. Ya cambie la contraseña varias veces para asegurarme que era lo mismo que estaba en config/database.yml pero aun así me aparece el mismo error.

**Comment by cirey1** [comment]
Hola @rkarac,

Necesito lo siguiente para poder ayudarte.

1- Screenshot de tu archivo database.yml
2- Screenshots de los pasos de como seteaste la password dentro de psql
3- Screenshot cuando ejecutas dentro de psql (Para entrar a la consola, utiliza ``` sudo -u postgres psql ```)  el comando ``` \conninfo ```

Saludos y estoy atento a tu respuesta,

**Comment by rkarac** [comment]
1- Screenshot de tu archivo database.yml
![db](https://user-images.githubusercontent.com/42577093/92399457-b52ada80-f100-11ea-8289-b96fc2b4033d.JPG)

2- Screenshots de los pasos de como seteaste la password dentro de psql
![password sql](https://user-images.githubusercontent.com/42577093/92399460-b65c0780-f100-11ea-9868-3499b8e3156f.jpg)

3- Screenshot cuando ejecutas dentro de psql (Para entrar a la consola, utiliza sudo -u postgres psql) el comando \conninfo
![info](https://user-images.githubusercontent.com/42577093/92399459-b65c0780-f100-11ea-85c7-ecfb91ea580c.jpg)

**Comment by cirey1** [comment]
Perfecto, ya se que es. Cuando uno defino los settings dentro de database..yml y utiliza el default, el puerto al cual busca la base de datos es el 5432, tu estas utilizando el 5434 para cambiar la password. Entonces para poder solucionarlo agrega una linea dentro de la seccion default de database.yml y tienes que poner ```port: 5434```.

Entonces tu seccion default del archivo database.yml quedaría asi.

```
default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5434
  username: postgres
  password: ""rkara18"
  pool: 5
```


Avísame si te funciona esto,

Saludos,

**Comment by rkarac** [comment]
Funciono!! Pero me aparecio esto cuando corri rails db:create, no se es necesario hacer algo

WARNING:  could not flush dirty data: Function not implemented
Created database 'carrete_development'
WARNING:  could not flush dirty data: Function not implemented
Created database 'carrete_test'

Y si me apareció la página final, muchas gracias !!

**Comment by cirey1** [comment]
No te preocupes de eso! Happy coding.
