### ISSUE TITLE
Configuración del repositorio

### ISSUE THREAD

**Issue by benjavicente** [IIC2143-2020-2/syllabus#112]
Hola! Me gustaria sabe si para este proyecto nosotros podemos cambiar (o si nos pueden cambiar) algunas configuraciones del repositorio, como por ejemplo, cambiar la rama por defecto a la cual se unirán los cambios de una PR.

Gracias de antemano!

**Comment by cirey1** [comment]
Si!, yo en particular les recomiendo dejar por default a development para las PR. Ahora dicho eso, la gracia de las ramas es que sigan un GitFlow adecuado. Para las branches, normalmente se utilizan asi:

- Branch Master: Esta contiene todo el código de producción, el cual esta testeado y no tiene errores (code+linter). El codigo de  esta branch es el que deberia conectarse y exportarse con heroku. Esta branch solo deberia recibir PR desde la branch development.

- Branch Development: Esta contiene todas las features(funcionalidades) ya terminadas. Esta es la única branch que debiese hacer Merge con Master. Esta branch deberia tener codigo testeado, pero al ser development, existe la posibilidad de errores de desarrollo.

- Cualquier otra branch: Debiera contener una parte del codigo, ya sea una funcionalidad, un refactor, debugging, etc. Estas al ser terminadas y testeadas, deberan ser Mergeadas a Development a traves de un Pull Request.

- Acuerdate entonces que el flow de PR es Cualquier branch -> Development -> Master

Te dejo una link que te podria servir.

https://danielkummer.github.io/git-flow-cheatsheet/

**Comment by benjavicente** [comment]
Ya perfecto! Me quedo claro como va a funcionar las branches.

Pero creo que nosotros tenemos bloqueado el acceso a esa configuración 😕

Y ya que el _flow_ debe seguir reglas como master sin problemas en testing y lint, se puede integrar con Actions?

**Comment by cirey1** [comment]
Si no tienen acceso, entonces la unica diferencia es que al hacer pull request tendrán que fijarse que su branch que recibe código sea la adecuada (Development/Master).

Al comentarte que no tuviera errores de testing y lint, basta que ustedes lo prueben localmente. Si quieres implementar actions para automatizar ese proceso puedes hacerlo pero es totalmente opcional, tienes que tener ojo con el tiempo que usas al hacer los tests dentro de los actions.
