### ISSUE TITLE
Actualización de Ubuntu 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#113]
Hola!Trate de actualizar el Ubuntu que uso para la consola WSL , uso Windows,  antes usaba el 16 y quise pasarlo al 18 ya que es más estable , instale tanto ruby como rails siguiendo los pasos de la ayudantía pero cuando estaba en la parte de Postgres más exactamente cuando intente ingresar a la consola de PostgreSQL como usuario postgres  me aparece el siguiente error 
![Captura de pantalla (69)](https://user-images.githubusercontent.com/62029138/92407380-d693c280-f110-11ea-95ee-46cd5a5c358d.png)
Aún tengo la versión 16 , esto me pasa debido a que desde esa versión esta accediendo a PostgreSQL? o es por otro motivo?

**Comment by cirey1** [comment]
Hola @RonaldoSosa,

Tienes que iniciar el servicio de postgres antes de ingresar a la consola de psql. Entonces tienes que hacer lo siguiente.

1- Correr el comando ``` sudo services postgresql start ```

2- Cuando ya este corriendo, intenta ingresar denuevo con ``` sudo -u postgres psql ```

3 - Ahora podras cambiar la password con ``` \password ```

Intentalo y avisame como te va,

Saludos,

**Comment by RonaldoSosa** [comment]
Hola!!!Cuando ingreso sudo services postgresql start me aparece :
![Captura de pantalla (70)](https://user-images.githubusercontent.com/62029138/92409973-e6afa000-f118-11ea-98d0-47abc2ea950f.png)

**Comment by cirey1** [comment]
Perdon, escribi mal el comando. Es ``` sudo service postgresql start ```. Ya esta editado en el comentario inicial.

**Comment by RonaldoSosa** [comment]
Sii ahora me funcionó todo !!! Muchas gracias !! :)
