### ISSUE TITLE
Subir proyecto a Heroku

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#114]
Hola!Tengo una duda acerca de como subir el proyecto a Heroku, más que nada no estoy del todo seguro de los pasos que hay que realizar , mi duda es que en primer lugar debo clonar el repositorio de mi grupo a una carpeta en mi escritorio, digamos que se llamará ,la carpeta, Proyecto_DCCarrete, luego hacer git push al proyecto que cree en rails en dicha carpeta, y luego seguir los pasos que se me indican el página de Heroku, me refiero a los siguientes:
![Captura de pantalla (73)](https://user-images.githubusercontent.com/62029138/92420755-871eb800-f14b-11ea-8802-da0bb29c7219.png)
En la parte que dice cd my-proyect , debería ir cd Proyecto_DCCarrete omit el git init ya que dicha carpeta es un "repositorio" de git y finalmente hacer el heroku git:remote -a dccarrete63-app , esos serían los pasos a seguir o pase por alto alguno?

**Comment by RonaldoSosa** [comment]
Ya me quedo claro , sin embargo, me aparece un error , en la carpeta de mi escritorio del repositorio que clone coloque la carpeta que se creo con rails y al momento de hacer **git add .** me tira el siguiente error:
![Captura de pantalla (75)](https://user-images.githubusercontent.com/62029138/92494350-fdfb9580-f1cb-11ea-86d6-26ffc0c40941.png)
![Captura de pantalla (74)](https://user-images.githubusercontent.com/62029138/92493966-8594d480-f1cb-11ea-8878-7a145d367a9b.png)
Es normal que me aparezca ese mensaje? debo seguir y hacerle el git commit ?

**Comment by aaguilarg** [comment]
Tienes algo en tu carpeta ```proyecto_DCCarrete``` ?
Si te fijas sale ```fatal: adding files failes```, por lo tanto no tienes nada que hacer commit ya que no se agregaron files

**Comment by RonaldoSosa** [comment]
Es que en mi carpeta proyecto_DCCarrete estan todos los elementos que aparecen por defectos al crear un proyecto con rails
![Captura de pantalla (77)](https://user-images.githubusercontent.com/62029138/92500202-33f04800-f1d3-11ea-95ca-9eb449853292.png)

**Comment by daleal** [comment]
Hola! Déjame explicarte qué está sucediendo, y luego te explico cómo subir tu app a Heroku. Lo que pasa es que Heroku usa `git` para manejar los proyectos. Por lo mismo, puedes pensar en Heroku de la misma manera en que piensas en GitHub. `git` es un _software_ de control de versiones. Lo que hace GitHub es almacenar y sincronizar remotamente tu repositorio de `git` (por eso se dice que GitHub es un _remote_ de tu repositorio). **Lo mismo hace Heroku**! Heroku también es un _remote_ de tu repositorio. Por lo mismo, cuando subes algo a Heroku, lo que estás haciendo es sincronizar el _remote_ de Heroku con tu repositorio de `git`. Para hacer una comparación, para subir algo a GitHub, los pasos son:

```sh
git add .  # Seleccionar todos los archivos que se desean 'versionar'
git commit  # 'Consolidar' la nueva versión del repositorio
git push  # Sincronizar el remote principal
```

En este ejemplo, `git push` es un _alias_ para `git push origin <actual-branch>`. En el caso de tu repo, GitHub debería ser el _remote_ llamado `origin`. El remote para Heroku debería llamarse `heroku`. Por lo mismo, si quisieras actualizar tu aplicación en Heroku, tendrías que asegurarte de que la app esté _commiteada_ (probablemente ya le hiciste `commit` para subirla a GitHub), y luego simplemente sincronizar el _remote_ de Heroku con el siguiente comando:

```sh
git push heroku master
```

Lo que hace ese comando es sincronizar la branch `master` del _remote_ `heroku` con el estado actual de tu repositorio. Una vez hecho esto, Heroku se encargará de lo demás.

**Comment by RonaldoSosa** [comment]
Eso significa de que no tengo la necesidad de subir mi proyecto en el repositorio de mi grupo?Sino que enlazo directamente mi trabajo en rails a Heroku, es que el problema que tengo es que no me deja subir el proyecto que hice en rails al repositorio del grupo y no entiendo de que forma mis compañeros podrían acceder a el

**Comment by Gaonuk** [comment]
Lo que deberias hacer, es que tu repositorio del grupo y tu carpeta del proyecto de rails sea la misma. Por ejemplo, cuando entras a tu repositorio te aparece una carpeta con el nombre de tu proyecto, pero la idea es que cuando entres a tu repo te aparezcan todas las carpetas generadas al usar rails new app.

**Comment by RonaldoSosa** [comment]
Ya entendido me hago una idea de como hacerlo ! Muchas gracias !

**Comment by daleal** [comment]
Eso **no** es válido. Lo que sucede es que dentro de tu repo hay dos carpetas `.git`. Se debe ver algo similar a esto:

```
grupo63-proyecto
|
|-- .git
|-- proyecto_DCCarrete
    |
    |-- .git
    |-- app
    |-- bin
    |-- config
    .
    .
    .
```

Para resolver tu problema, elimina la carpeta `.git` que se encuentra dentro de la carpeta `proyecto_DCCarrete`, haz `git add` (que agregará todos los archivos dentro de `proyecto_DCCarrete`), `git commit` y finalmente `git push`.

**Comment by RonaldoSosa** [comment]
Elimine la carpeta .git de mi carpeta **proyecto_DCCarrete** pero al intentar hacer git add . me aparece los siguiente:
![Captura de pantalla (93)](https://user-images.githubusercontent.com/62029138/92599287-6c019480-f280-11ea-813b-ec52720bcf73.png)

**Comment by RonaldoSosa** [comment]
Ya logré solucionarlo con ayuda!!!Lo que hice fue ir al a la carpeta del repositorio hacer **git rm --cached "NOMBRE DEL PROYECTO"** y luego **git add .** con eso se creó la carpeta del proyecto en rails no como git sino como una carpeta y el repo me quedo así:
![Captura de pantalla (101)](https://user-images.githubusercontent.com/62029138/92630360-1a6c0080-f2a6-11ea-9535-ed38061b3c04.png)

**Comment by daleal** [comment]
Perfecto!!

**Comment by Tomas-Ira** [comment]
Como lo solucionaron??
Tenemos el mismo error, pero no logramos subir ninguna carpeta.
