### ISSUE TITLE
Error en Deploy Heroku

### ISSUE THREAD

**Issue by Naogaz** [IIC2143-2020-2/syllabus#115]
Hola, estoy intentando hacer Deploy en heroku, me salta el siguiente error:

Could not find gem 'sqlite3 x64-mingw32' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.

al ejecutar el comando dicho me salta los siguientes errores
![error1](https://user-images.githubusercontent.com/48302271/92435569-10001880-f179-11ea-9345-355957a44017.png)
![error2](https://user-images.githubusercontent.com/48302271/92435576-142c3600-f179-11ea-9639-f88a3d111487.png)

**Comment by aaguilarg** [comment]
Buscando tu error en Google encontré [esto](https://stackoverflow.com/questions/34171874/an-error-occurred-while-installing-sqlite3-1-3-11-and-bundler-cannot-continue/36440832) que quizás te podría servir. Te recomiendo leer bien cada respuesta y ver cuál se podria ajustar mejor para solucionar tu problema. 
Ojalá eso te ayude.

**Comment by daleal** [comment]
Hola! Dado que usaremos PostgreSQL, puedes eliminar la gema `sqlite` de tu `Gemfile`!
