### ISSUE TITLE
push a heroku no funciona

### ISSUE THREAD

**Issue by baseba** [IIC2143-2020-2/syllabus#117]
hola cuando intento subir mi proyecto a heroku me aparece el siguente error
![Anotación 2020-09-08 201425](https://user-images.githubusercontent.com/48297670/92536400-fbbb2a80-f20f-11ea-81c9-c1773e2b9785.png)

**Comment by baseba** [comment]
como extra esto me sale en la app de heroku 
![image](https://user-images.githubusercontent.com/48297670/92536961-4c7f5300-f211-11ea-9930-994d4ce5b3ff.png)

**Comment by daleal** [comment]
Hola! Esto probablemente se debe a que en tu repositorio la aplicación está en una sub-carpeta del repo y no en la raíz. Para arreglarlo, mueve todo a la raíz del repositorio y probablemente se arregle.

**Comment by catalina-ramirez** [comment]
Hola! @daleal  te refieres a sacar todo de la carpeta de la aplicación para dejarlo en la carpeta del repo?

**Comment by daleal** [comment]
Así es! Y puedes dejar cosas como los relatos de usuario dentro de una carpeta `docs` para que sea fácil encontrarlos!
