### ISSUE TITLE
Ofensa Missing frozen string literal comment en Rubocop

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#118]
Hola!Al usar Rubocop me aparecen multiples ofensas , en su gran mayoría relacionadas a Missing frozen string literal comment quiero saber si para esta entrega es válido solucionarlo haciendo un  bundle exec rubocop --auto-correct --only FrozenStringLiteralComment o tendría que hacerlo de otra forma?

**Comment by daleal** [comment]
Hola! Tienes dos formas de enfrentar este problema. Una es programando de tal manera que dicha ofensa nunca ocurra (y si, ejecutar `rubocop` con `--auto-correct` estaría bien, lo importante es que el código en el repo cumpla con las reglas) o agregar una omisión a dicha regla en el archivo `.rubocop.yml` para que `rubocop` no exija usar _frozen string literal comments_.

**Comment by RonaldoSosa** [comment]
Entendido!Al final hice lo de .rubocop.yml , mucha gracias!!!
