### ISSUE TITLE
[Rubocop] Archivo bin/setup y bin/update

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#119]
Hola! En los archivos bin/setup y bin/update usan un include para el FileUtils por lo que investigue este se usa para incluir los métodos de otro modulo pero se hace solo en las clases y en estos archivos no se crea ninguna , lo pregunto ya que esto me toma como una ofensa para Rubocop , sin embargo, si la incluyo en la iteración **chdir APP_ROOT** se deja de considerar como una ofensa y el proyecto me sigue funcionando , con esto último me refiero a que cuando ejecuto rails server me aparece lo trabajado en el proyecto.También se arregla si elimino la línea **include FileUtils** y me sigue funcionando como normalmente lo hace , así que quisiera saber cual método sería más recomendable usar para corregir esto.
![Captura de pantalla (86)](https://user-images.githubusercontent.com/62029138/92596131-b7fe0a80-f27b-11ea-85f4-b40cc1fc8cac.png)
![Captura de pantalla (88)](https://user-images.githubusercontent.com/62029138/92596347-11fed000-f27c-11ea-90a2-aa166eb93928.png)
![Captura de pantalla (87)](https://user-images.githubusercontent.com/62029138/92596224-e380f500-f27b-11ea-9070-d25cf4a5815b.png)
![Captura de pantalla (90)](https://user-images.githubusercontent.com/62029138/92596442-335fbc00-f27c-11ea-98fd-137560aa9b50.png)
![Captura de pantalla (91)](https://user-images.githubusercontent.com/62029138/92596599-70c44980-f27c-11ea-8064-69a2bb8f6793.png)
![Captura de pantalla (89)](https://user-images.githubusercontent.com/62029138/92596459-38247000-f27c-11ea-8d21-6fbe21f69afa.png)

**Comment by daleal** [comment]
Hola! Si quieres, puedes ignorar los archivos dentro de `bin` en tu `.rubocop.yml`. Lo importante es que definas un set de reglas que tu grupo sea capaz de cumplir a lo largo del desarrollo del proyecto

**Comment by RonaldoSosa** [comment]
Yaaaa , logré hacerlo!!!Entendido tendré en cuenta lo de las reglas! Gracias!!!!
