### ISSUE TITLE
Duda top_ayudantes o top_grupos

### ISSUE THREAD

**Issue by Francisco5674** [IIC2143-2020-2/syllabus#12]
Un problema que puede ocurrir aunque es muuuy poco probable con estos métodos es que existan más de un ayudante con el máximo promedio de grupos o más de tres grupos con la máxima nota de su muestra, o acaso sera la misma muestra de ayudantes, grupos y alumnos para todas las instrucciones?

**Comment by jerosalazar** [comment]
En caso de que haya un empate por estos puestos, puedes quedarte con el que tenga ID más bajo 😊

**Comment by fnberrios** [comment]
Hola @jerosalazar duda sobre esto. En caso de empates mi código contabiliza a ambos grupos como un "primer, segundo o tercer lugar" y los guarda. Eso será considerado erróneo?
