### ISSUE TITLE
Git y la secuencia de término de línea

### ISSUE THREAD

**Issue by benjavicente** [IIC2143-2020-2/syllabus#120]
Hola! En un commit se nos cambió el término de línea de `LF` a `CRLF`. Esto hace que el commit sea de sobre 1.5k líneas y que se detecte la ofensa correspondiente en rubocop.

Al crear un archivo `.gitattributes` con `* text eol=lf` he podido modifica el _index_ en cada archivo, pero no he logrado cambiarlos en el directorio local 😕.

¿Como puedo actualizar el directorio local para que tenga lo mismo que el _index_ de git? Y, ¿`* text eol=lf` es la manera correcta para forzar la secuencia de término de línea en git?

Gracias de antemano!

**Comment by daleal** [comment]
Hola! Esa si sería la manera de forzar el término de línea. Pero en local tienes las líneas ya cambiadas. Deberías poder modificar tu editor de texto para usar un tipo de `EOL` en particular
