### ISSUE TITLE
Heroku intenta instalar sqlite 3

### ISSUE THREAD

**Issue by baseba** [IIC2143-2020-2/syllabus#121]
hola cada vez que hago git push heroku master me aparece que intenta instalar sqlite 3 para posteriormente fallar dado que heroku no usa sqlite 3
![image](https://user-images.githubusercontent.com/48297670/92629164-4a1a0900-f2a4-11ea-8d7e-d0d8999cf2d4.png)
pero no tengo mencionado sqlite3 ni en mi gemfile ni en mi gemfile.lock ni en mi database.yml
![image](https://user-images.githubusercontent.com/48297670/92629249-6ddd4f00-f2a4-11ea-8f45-80f37e4df9f3.png)
![image](https://user-images.githubusercontent.com/48297670/92629271-76ce2080-f2a4-11ea-9d7a-eb8c4bc5ba6e.png)
![image](https://user-images.githubusercontent.com/48297670/92629321-85b4d300-f2a4-11ea-8596-5ef8eea60733.png)
ya se me agoto donde buscar en google :(

**Comment by daleal** [comment]
Hiciste `commit` antes de hacer `git push heroku master`?

**Comment by baseba** [comment]
sip

**Comment by daleal** [comment]
Y tienes ese código en `master`? En tu repositorio veo en `master` solamente la carpeta `docs`

**Comment by baseba** [comment]
el codigo esta en la branch "developer" de nuestro repo

**Comment by daleal** [comment]
Lo que sucede es que cuando haces `git push heroku master`, lo que haces es subir a Heroku lo que hay en tu branch `master`. Quizás si no encuentra nada, utiliza un `Gemfile` que por _default_ incluye `sqlite3`, o quizás en tu rama `master` local tienes esa gema en el `Gemfile`. Como sea, lo que deberías hacer es pasar a `master` tu proyecto y ahí hacer `git push heroku master`

**Comment by baseba** [comment]
ok lo intentare : )

**Comment by baseba** [comment]
hice el merge y lo intente denuevo pero no funciono : (

**Comment by daleal** [comment]
Encontré raro que no te funcionara y le hice `git clone` a tu repo y luego `git push heroku master` y se hizo _deploy_ bien. Quizás tienes alguna versión des-actualizada del repo o algo así. Yo eliminaría el repo y haría `git clone` de nuevo.

**Comment by baseba** [comment]
ahora si funciono : 3 muchas gracias !!!
