### ISSUE TITLE
Version Ruby en el grupo

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2143-2020-2/syllabus#122]
En mi grupo de trabajo tenemos distintas versiones de ruby, 2.6 o 2.7. ¿Es necesario tener la misma versión todo el grupo?. De ser un problema, ¿Cual es la mejor forma de cambiar de version?

**Comment by daleal** [comment]
Hola! Puede ser que tengan algunos problemas si usan distintas gemas (pero también puede ser que no). Al principio de semestre les recomendamos instalar `rvm` para instalar `ruby`. La gracia de `rvm` es que controla distintas versiones de `ruby` muy fácilmente. Si tienes `rvm`, puedes ejecutar `rvm install 2.6 && rvm use 2.6` para instalar y usar `ruby 2.6` (por supuesto, puedes hacer esto con cualquier versión de `ruby`).

**Comment by johnowenatala** [comment]
Hola,

Deben asegurarse de tener la misma versión de ruby, o sino tendrán muchos problemas - por ejemplo, sus proyectos instalaran versiones distintas de las gemas y tendran que estar reinstalando gemas todo el tiempo.
Normalmente los manejadores de paquete de ruby, como rvm o rbenv ayudan con esto.
