### ISSUE TITLE
Error "FATAL" al hacer rails db:create

### ISSUE THREAD

**Issue by EstefanyOlmos** [IIC2143-2020-2/syllabus#123]
Hola, al intentar hacer rails db:create en la carpeta del proyecto de grupo que cloné desde github en la consola me tira el siguiente error:

```
FATAL:  la autentificacin password fall para el usuario postgres
Couldn't create 'dccarrete59_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: FATAL:  la autentificacin password fall para el usuario postgres
```

Tengo postgres iniciado con la clave y nombre de usuario que están en el archivo database de la carpeta del proyecto, he intentado cambiar esa contraseña y muchas otras cosas como reinstalar postgres pero nada me funciona.
También me tira esta linea al principio del error pero no creo que sea relevante

```
/home/estefany/.rvm/rubies/ruby-2.7.1/bin/ruby: warning: shebang line ending with \r may cause problems
```

De antemano gracias.

**Comment by daleal** [comment]
Lo del `shebang` puedes verlo [aquí](https://stackoverflow.com/a/54288670). Con respecto a lo de Postgres, tienes Windows + WSL? O Linux? Si tienes Windows + WSL, dónde instalaste postgres y cambiaste usuario/contraseña? En Windows o en WSL?

**Comment by EstefanyOlmos** [comment]
Ah se me había olvidado mencionar eso, tengo Windows + WSL, y todo he hecho todo en WSL, y gracias por lo de `shebang`

**Comment by daleal** [comment]
@EstefanyOlmos, creo que lo más probable es que las credenciales del proyecto de tu grupo simplemente no calcen con aquellas en tu máquina. Podrías confirmarme si ese es el caso?

**Comment by EstefanyOlmos** [comment]
Me parece que ese es el problema pero por mas que cambie las credenciales en mi pc para que calcen con las del proyecto no funciona, incluso desinstalé y re instalé postgres y no me funciona igual.

**Comment by daleal** [comment]
Debe haber algún tipo de error en cuanto a las credenciales que estás cambiando. Dado que es un problema muy particular, te recomiendo que lo hables con tu Product Owner para poder tener una línea de comunicación directa y poder resolver el problema de manera más expedita. Cerraré esta _issue_ debido a que la solución deberá ser encontrada de manera más directa.
