### ISSUE TITLE
Error Homepage

### ISSUE THREAD

**Issue by hsazos** [IIC2143-2020-2/syllabus#124]
Hola! estoy tratando de hacer que mi pagina principal sea en la que yo escribí hello world, y cuando tiro rails server, puedo ingresar a http://localhost:3000/hello_world/index y ver el hello, world! Pero si ingreso solo a localhost:3000 me tira el mensaje de bienvenida a rails. Ya agregué el index a routes y todo, y mi homepage sigue siendo la de bienvenida a rails uwu.

**Comment by hsazos** [comment]
Ya lo solucioné :)

**Comment by daleal** [comment]
Que bueno! Podrías explicar qué sucedió, por si algún compañero tiene la misma duda? 🐳

**Comment by hsazos** [comment]
Use esta página pero no estoy seguro si sirva para el sprint 0.
https://iridakos.com/programming/2013/11/24/saying-hello-world-with-ruby-on-rails
