### ISSUE TITLE
Error: 2 errors occurred outside of examples

### ISSUE THREAD

**Issue by Baelfire18** [IIC2143-2020-2/syllabus#125]
Hola intente hacer el rspec del controlador según lo indicado en la ayuntia 3, del min 39 en adelante y me salió este error, no se pq puede ser

![image](https://user-images.githubusercontent.com/50716449/92668511-69855600-f2e5-11ea-8526-357069aae5d5.png)

**Comment by meretamal** [comment]
Hola 😁 

Solo para asegurarme, instalaste rspec-rails, ejecutaste `rails g rspec:install` y después de escribir tus tests ejecutaste `rails spec`, verdad?

**Comment by Baelfire18** [comment]
Sip lo instale, aparentemente me tira error del webdriver de selenium, puede ser?
chrome webdriver es algo que yo ya habia instalado en mi PC tiempo atras, puede ser por eso?
![image](https://user-images.githubusercontent.com/50716449/92744923-48118200-f358-11ea-93da-664f39df2e57.png)

**Comment by meretamal** [comment]
El primero error (el que está en rosado), es porque no tiene un servicio de postgres corriendo. Intenta primero iniciando uno (si estás en wsl hay un comando en la ayudantía 2) y luego trata de correr los tests

**Comment by Baelfire18** [comment]
![image](https://user-images.githubusercontent.com/50716449/92807348-2d0f3400-f391-11ea-80a0-353078fde1d4.png)
Sigue fallandome, con otra cosa. Que puede ser?
