### ISSUE TITLE
Highlight Rubocop errors

### ISSUE THREAD

**Issue by MINGOD24** [IIC2143-2020-2/syllabus#126]
Hola, queria saber si existe alguna manera para que los errores o ofensas que detecta rubocop sean señalados en el codigo en si, sin tener que escribir el comando rubocop.

Muchas gracias!

**Comment by daleal** [comment]
Hola! Si, dependiendo del editor que tengas, deberías poder instalar una extensión que haga eso por ti. Hay varias, en `vscode` hay una que se llama Rubocop y creo que la que se llama Ruby también hace el _lint_, pero tendrías que configurar la extensión (y la configuración varía 100% de máquina a máquina). Hasta donde sé, Rubocop es más _plug and play_

**Comment by MINGOD24** [comment]
Gracias! Te pasaste! :)
