### ISSUE TITLE
Problema al hacer "git push heroku master"

### ISSUE THREAD

**Issue by matiasone** [IIC2143-2020-2/syllabus#127]
Al usar ese comando, no tengo problemas hasta que en el output aparece:

```
remote:        webpack binstubs not found.
remote:        Have you run rails webpacker:install ?
remote:        Make sure the bin directory or binstubs are not included in .gitignore
```

Luego, intento hacer `rails webpacker:install`, y me aparece este error:

```
ArgumentError: Malformed version number string 0.32+git
bin/rails:4:in `<main>'
Tasks: TOP => webpacker:install => webpacker:check_yarn
(See full trace by running task with --trace)
```

Lo busqué en google, y una posible solución puede ser esta: https://github.com/rails/webpacker/issues/1461

Mi problema es que no estoy seguro como proceder, que archivos yarn borrar y cuales instalar, o si el problema pueda venir de otro lado.

Gracias!

**Comment by Gaonuk** [comment]
Podrias mandar una foto de tu output entero al hacer el comando? y subir de paso una foto de tu Gemfile

**Comment by matiasone** [comment]
Hola, ya lo pude solucionar. Tuve que borrar yarn descargado por defecto e instalé la versión 1.22.5.
