### ISSUE TITLE
Consulta config rubocop

### ISSUE THREAD

**Issue by inarrgd** [IIC2143-2020-2/syllabus#128]
Hola!
Tengo una consulta, generé los ficheros de rubocop con `rubocop --auto-gen-config`, y luego ejecuté el comando `rubocop`, y no detectó ofensas en 48 archivos inspeccionados. Quería saber si esto se considera como una configuración no vacía para rubocop, si no es así, qué se busca como configuración? No he entendido del todo lo que hay que hacer con esto.

Saludos!! gracias

**Comment by jerosalazar** [comment]
segun tengo entendido, el comando `rubocop --auto-gen-config` te genera un archivo rubocop.yml y rubocop_todo.yml 
Sin embargo, el archivo rubocop no se encuentra completo, ya que depende del archivo "to do". Esto quiere decir que rubocop no tiene una configuración 100% valida, si no que simplemente "ignora" todo lo que aparece en el archivo "to do" para que puedas revisar el archivo "to do" a mano y arreglar las ofensas tu. Lo que tu deberías hacer es revisar el archivo "to do" y ver que ofensas crees que debes arreglar y que ofensas corresponden a reglas que no les interesa seguir como grupo (por ejemplo, maximo de caracteres por linea = 80, si ustedes quieren setear un máximo de 100) y que desactives o edites esas reglas en tu rubocop.yml
Te dejo un [post](https://leonelgalan.com/2020/02/26/rubocops-auto-gen-config.html) donde hablan harto accerca de este comando y que creo que les puede servir harto
