### ISSUE TITLE
Grabacion de clases

### ISSUE THREAD

**Issue by MINGOD24** [IIC2143-2020-2/syllabus#129]
Hola, quería saber si es posible que se guarden las clases en un drive como lo hacen con las ayudantias porque en canvas duran un tiempo limitado.

**Comment by Juan379** [comment]
Me pregunto lo mismo!

**Comment by johnowenatala** [comment]
Hola a todos,

No es un tema de canvas. Es su responsabilidad  asistir a clases y tomar los apuntes que necesiten. Las grabaciones se mantienen por 14 días por zoom como respaldo en los casos que no pudieron asistir a clases. Desde este punto de vista, 2 semanas es un tiempo más que razonable Para que revisen una clase a la que no asistieron.

**Comment by Juan379** [comment]
Ok! No hay problema con tener opiniones distintas! Estoy de acuerdo con que sea nuestra responsabilidad. Pero mi comentario no iba a no ver las clases y después "aprovechar" para verlas después, simplemente a que puede ser conveniente tenerlas para estudiar **después de haberlas visto** y poder repasar algunos temas junto con los apuntes. Hay ramos que tengo actualmente que lo hacen sin problemas por lo que pense que sería posible, pero entiendo tu punto también. 
Saludos.
