### ISSUE TITLE
Tests a realizar Entrega 1

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#130]
Hola!Tengo una duda acerca de lo que hay que testear con Rspec , en el enunciado dice :
**Además, deben incluir un test simple para el controlador y un test simple para la vista**
Qué funcionalidad del controlador es la que debe ser testeada?

**Comment by Gaonuk** [comment]
Que te muestre la vista indicada!

**Comment by RonaldoSosa** [comment]
Pero eso no sería lo que habría que testar en la vista , o en la vista el test es de que te cargue(funcione) la vista ?

**Comment by Gaonuk** [comment]
En el test de la vista, tu quieres testear que por ejemplo te esta mostrando el texto correctamente, en el test de controller quieres saber si se está "rendereando" bien el archivo correcto y no otro, onda que te muestre index.html.erb y no show.html.erb

**Comment by RonaldoSosa** [comment]
Yaaa! Me quedo claro!! gracias!!!!
