### ISSUE TITLE
contraseña base de datos

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2143-2020-2/syllabus#131]
Hola, en el archivo database.yml todos los del grupo que quieran correr la aplicación tienen que cambiar la password de acuerdo a su contraseña de postgres?

**Comment by Gaonuk** [comment]
La idea es que todos tengan la misma password!

**Comment by Tomas-Ira** [comment]
tengo el siguiente error y no entiendo por qué:
![image](https://user-images.githubusercontent.com/42189004/92785484-d815f280-f37d-11ea-83b2-806757bb2768.png)

¿Qué hago?

**Comment by Gaonuk** [comment]
Podrias subir un screenshot de tu database.yml? Primero que nada, tienes bien puesta la clave en el archivo y es la misma que en postgres?

**Comment by Tomas-Ira** [comment]
![image](https://user-images.githubusercontent.com/42189004/92788602-75722600-f380-11ea-8a40-7c0b965480cb.png)

La clave que uso, es la misma con la que logre entrar a tirarrazabal1, y es la que pongo cada vez que me pide una clave (la usé en el paso 7, "99% seguro"). (no es la misma que la de mi computador (nunca entendí si tenía que usar esa o no)

**Comment by Gaonuk** [comment]
Ahh entonces ahi esta el problema, porque esa clave es la clave de tu "root" de wsl, no la de postgres, lo que pasa es que cada vez que usas el comando "sudo" es como si ejecutaras algo en modo administrador y te pide confirmar con la clave del equipo, pero esta no es la clave de tu postgres. Usa el comando "sudo -u postgres psql", una vez dentro de postgres usa "\password" para setear la password de postgres y ahi pon cualquier cosa para probar que funcione onda "hola".

**Comment by Tomas-Ira** [comment]
Si me sirvio. Muchas Gracias
