### ISSUE TITLE
Variables de entorno para eliminar "deprecated warnings" 

### ISSUE THREAD

**Issue by benjavicente** [IIC2143-2020-2/syllabus#132]
Hola!

Tanto en `rails spec` como en `rails server` aparecen muchos advertencias como

```
actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the cal
```

Encontré que al entregar a rails la variable de entorno **`RUBYOPT="-W0"`**  (como  `RUBYOPT="-W0" rails s`) no se imprimen estas advertencias. También encontré que añadiendo `ENV['RUBYOPT'] = '-W0'` a  `config/application.rb` se soluciona para `rails spec`, pero no para el server.

¿Cómo puedo añadir una variable global para que esté disponible para todo el proyecto de rails?, o ¿hay una configuración de rails para desactivar estas advertencias?

Gracias de antemano!

**Comment by meretamal** [comment]
Hola 😄

¿Qué versión de ruby están usando?

**Comment by benjavicente** [comment]
`2.7.1`

**Comment by meretamal** [comment]
Parece que con la versión 2.7, usando rails 5.2, suelen aparecer hartos _warnings_.

Si intentas crear una app de rails 5.2 con algún lanzamiento de ruby 2.6, deberían dejar de aparecer.

**Comment by benjavicente** [comment]
Al final pude ocultar esa advertencia y otras sin cambiar a ruby `2.6` con lo siguiente

#### deprecated warning

antes de correr rails, añadir la variable de entorno

```bash
export RUBYOPT="W0"
```

#### tzinfo-data (>= 0) will be unused

eliminar `, platforms: [:mingw, :mswin, :x64_mingw, :jruby]` del `Gemfile`, para que si se use
luego usar `bundle update` para actualizar `Gemfile.lock`

#### Selenium::WebDriver::Chrome#driver_path= is deprecated

cambiar en `Gemfile`

```rb
gem 'chromedriver-helper'
```

por

```rb
gem 'webdrivers'
```
