### ISSUE TITLE
error con push a Heroku

### ISSUE THREAD

**Issue by Afro27** [IIC2143-2020-2/syllabus#133]
Después de hacer el primer deploy a heroku correctamente, agregamos Rubocop al proyecto y lo configuramos. Tras hacer esto y hacer los push correspondientes a github, se nos presenta un error de  que dice que no se pudieron instalar las gems via bundler.
![image](https://user-images.githubusercontent.com/53800902/92824934-605bbe00-f3a5-11ea-9f60-1a971a416550.png)

**Comment by daleal** [comment]
Hola! El problema es que los saltos de línea en el repositorio están en formato de Windows (`\r\n`) en vez de en formato Unix (`\n`) como espera bundler en Heroku. Por eso, al fer una línea terminada en `ruby`, lo que lee es `ruby\r`, y como no es capaz de encontrar un binario llamado `ruby\r`, falla. Lo que deben hacer es configurar sus editores para usar el salto de línea de Unix, hacer `commit` y volver a intentarlo.

**Comment by Afro27** [comment]
Encontré un comando que debería configurar los saltos de linea automáticamente a unix al hacer un commit:
git config --global core.autocrlf true
Pero no funcionó, luego probe con otro que debería hacer lo mismo pero para Ubuntu por lo que lo corri desde wsl:
git config --global core.autocrlf input
Sin embargo, me sigue arrojando el mismo error:
Bundler Output: /usr/bin/env: ‘ruby\r’: No such file or directory
Que debería hacer para poder arreglar este error?

**Comment by daleal** [comment]
Sigue siendo el mismo error, tu repositorio local debe estar con saltos de línea Windows y el remoto con saltos de línea UNIX. Deberás configurar tu editor de texto para que transforme automáticamente los saltos de línea a UNIX y luego deberás ir archivo por archivo arreglando todo
