### ISSUE TITLE
Error con repositorio

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2143-2020-2/syllabus#134]
Hola! tuvimos unos problemas con el repositorio y las cosas que subimos y decidimos hacer todo de nuevo. ¿Como se hace para "reiniciar el repo como ustedes nos lo dieron? Intentamos todo ya :(

**Comment by daleal** [comment]
Hola! Una opción sería eliminar todo de la carpeta (excepto la carpeta `.git`), hacer `git add *`, `git commit` y `git push`

**Comment by johnowenatala** [comment]
si haces git push --force, lo que tengas localmente sobreescribirá todos los archivos y todo el historial de commits que tengas en el repositorio en la rama actual. Sólo debes hacer un git push --force en casos muy extremos.
