### ISSUE TITLE
Error .gitignore 

### ISSUE THREAD

**Issue by vsantelicest** [IIC2143-2020-2/syllabus#135]
Hola, para que cada uno de los integrantes del grupo pudiera hacer funcionar la aplicación con su usuario y clave de postgres propio, tuvimos que crear un archivo llamado local_env.yml, que fue puesto en el gitignore para así cada uno tener su propio archivo guardando la contraseña de su postgres. Al subir nuestra aplicación al master, este archivo no fue ignorado, y al hacer pull desde otro computador este archivo se descargó, dejando así al descubierto la clave de uno de los integrantes. Mi pregunta es por qué sucedió esto y como se arregla, para que tampoco vuelva a pasar.

**Comment by Gaonuk** [comment]
Hola! Primero que nada, la idea es que todos tengan la misma password de postgres para que no tengan que hacer este tipo de cosas! Hagan eso y luego borran ese archivo local_env.yml.

**Comment by vsantelicest** [comment]
Tratamos de hacer lo que indicas, de compartir la misma password, pero no nos resultó el cambio desde la que teníamos a la que queríamos tener en común. Por esta razón, pedí ayuda a un ayudante que me indicó que por razones de seguridad, era mejor crear el archivo local_env.yml, para así poder trabajar cada uno con su propia contraseña. 
Si es que consideras que es 100% necesario que cambiemos nuestras claves para trabajar con una en común, sería de gran ayuda si nos pudieras indicar como hacerlo, ya que anteriormente no nos resultó. Gracias!

**Comment by Gaonuk** [comment]
Si quieres podemos tener una reunion por meet para solucionarlo rapidamente, escribeme a mi mail rodrigo.gaona@uc.cl.

**Comment by vsantelicest** [comment]
No te preocupes! Ya lo solucionamos. Muchas gracias!
