### ISSUE TITLE
Error instalando heroku en wsl

### ISSUE THREAD

**Issue by FelipeA7** [IIC2143-2020-2/syllabus#136]
Hola, estaba intentando partir con subir el proyecto a heroku, pero me tira un error en el primer paso mientras intento instalar el comando heroku
Intenté de 2 formas distintas y las 2 me tiran error
![error heroku](https://user-images.githubusercontent.com/48482398/92846099-13d0ac80-f3be-11ea-97db-ed3dcac74b3d.png)

**Comment by benjavicente** [comment]
Yo tuve que cambiar la versión de WSL a la 2 para poder usar `snap`.

[Use esta guia para hacerlo](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2). Es importante que luego de actualizar a la 2, se cambie la versión de WSL en la distribución que tienes instalada, com `wsl --set-version <distro> 2`. Se puede verificar que esté en la versión correcta con `wsl -l -v`.

**Comment by FelipeA7** [comment]
Graciass, pero me gustaría ver si hay otra forma de arreglarlo sin WSL 2, porque no tengo el build de Windows que se requiere para instalar el 2.
Tengo varios amigos que también tienen instalado WSL 1 y pudieron instalar heroku con curl sin problemas, no entiendo por qué me sale eso a mi :(

**Comment by benjavicente** [comment]
Prueba con el otro link de `curl`.

```bash
curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
```

Si no te funciona eso puede ser que no se pueda 😕
