### ISSUE TITLE
Error push a heroku

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2143-2020-2/syllabus#137]
![image](https://user-images.githubusercontent.com/54009399/92852933-a4f75180-f3c5-11ea-8d0c-710ac5252b58.png)
Intento subir el trabajo a Heruku pero me sale este error y no se sulucionarlo

**Comment by Gaonuk** [comment]
Podrias mandar una foto de lo que sale mas arriba? Tambien que te dice cuando haces "git branch"?

**Comment by felipefuentesporras** [comment]
Ya lo resolvi!!, era por un error en bundle y un path que no reconocia heroku
