### ISSUE TITLE
Error al iniciar un proyecto

### ISSUE THREAD

**Issue by santiagomuzzo** [IIC2143-2020-2/syllabus#138]
Desinstalé Ubuntu 16.04 y me descargué Ubuntu 18.04 porque la versión antigua no me dejaba descargar heroku. Hice todos los pasos nuevamente pero el paso número 8 me falló y me sale este error. Además el proyecto que había creado con el antiguo ubuntu (que sigue existiendo) no me deja correr el servidor. Que puede estar pasando?

`rails new djm --database=postgresql
       exist
   identical  README.md
   identical  Rakefile
   identical  .ruby-version
   identical  config.ru
   identical  .gitignore
   identical  Gemfile
         run  git init from "."
error: chmod on /mnt/c/Users/santi/djm/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.repositoryformatversion' to '0'`

**Comment by Gaonuk** [comment]
Podrias probar usar "cd ~" y luego ejecutar el comando por favor

**Comment by santiagomuzzo** [comment]
Se me ejecutó pero solo se me ejecutó y creo el proyecto pero solo se descargaron unos pocos archivos y ninguna carpeta

**Comment by Gaonuk** [comment]
Mmmm, no entiendo muy bien lo que tratas de hacer, quieres hacer un nuevo proyecto de rails? Por que podrias clonar el que tienes de tu repo y saltarte ese paso.

**Comment by santiagomuzzo** [comment]
Si, un nuevo proyecto de rails. Como se hace eso? Hice un proyecto ayer y ahora no me deja trabajar con ese (por todo el cambio a wsl2 y ubuntu 18.04 que hice) y me pasa que tampoco me está funcionando crear uno nuevo.

**Comment by Gaonuk** [comment]
Oka, entonces solo tienes que hacer "cd ~" asi no tienes problemas de permisos, luego "rails new <nombre_de_tu_app> --database=postgresql"

**Comment by santiagomuzzo** [comment]
Ok. Eso hice pero la carpeta que se me creó solo tiene 7 archivos y la carpeta .git

**Comment by Gaonuk** [comment]
Mandame una foto por favor

**Comment by santiagomuzzo** [comment]
![image](https://user-images.githubusercontent.com/62107395/92933892-37770f80-f41d-11ea-8504-c5d70f5848cd.png)

**Comment by Gaonuk** [comment]
Nono pero en la consola, que te dice la consola cuando ejecutas "rails new testapp" luego de hacer "cd ~"

**Comment by santiagomuzzo** [comment]
![image](https://user-images.githubusercontent.com/62107395/92934806-5033f500-f41e-11ea-9854-eb944bbb8213.png)

**Comment by santiagomuzzo** [comment]
En que parte de mi computador debería guardarse?

**Comment by santiagomuzzo** [comment]
para poder acceder desde visual studio

**Comment by Gaonuk** [comment]
Si usaste el comando "cd ~" y luego hiciste "rails new testapp" se deberia generar un proyecto y deberia aparecer lo que te aparecio a ti pero arriba deberia decir muchos "create", para acceder con visual studio code basta con meterse al directorio del proyecto usando "cd <nombre que usaste para el proyecto>" y poner "code ."

**Comment by santiagomuzzo** [comment]
Perfecto, ahí me está funcionando gracias. Eso sí se me está abriendo el VScode versión antigua que tengo que creo que me venía instalada. Como hago para que se me abra el que siempre uso?

**Comment by daleal** [comment]
@santiagomuzzo probablemente tendrás que desinstalar la versión antigua o definir como predeterminada la nueva. Dado que el problema original fue solucionado, cerraré esta _issue_.
