### ISSUE TITLE
[Rubocop] Layout/EndOfLine: Carriage return character detected

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#139]
Hola!Al intentar ejecutar rubocop en el proyecto , me apareció el siguiente error:
![Captura de pantalla (106)](https://user-images.githubusercontent.com/62029138/92959995-33f67f00-f443-11ea-880b-b56bc55f0846.png)
Busqué en internet y decía que esto era que debido a que  los finales de línea son configurables y se basan en su sistema operativo y que para que se solucione agregue esto a mi .database.yml:
Style/EndOfLine:
  EnforcedStyle: lf
Sin embargo esto no dio solución a mi problema ni tampoco reemplazando el lf por crlf , así que quisera saber como podría solucionarlo, además señalo que antes no me aparecía este error cuando corría rubocop

**Comment by daleal** [comment]
Podrías intentar ejecutandolo como `bundle exec rubocop --cache false`?

**Comment by RonaldoSosa** [comment]
Hola!Ejecute ese comando y el error sigue :( , el mensaje que me aparece  es el mismo

**Comment by daleal** [comment]
El problema es el tipo de saltos de línea de tu sistema operativo, más que un error de Rubocop. Deberías poder configurar tu editor de texto para usar `LF` por default. Con eso, al momento de guardar cambios en tus archivos, se actualizarían los saltos de línea a los caracteres esperados (`LF`) en vez de los que hay actualmente (`CRLF`).

**Comment by RonaldoSosa** [comment]
Entendido!Gracias
