### ISSUE TITLE
Error al instalar Rails.

### ISSUE THREAD

**Issue by EstebanReyes1998** [IIC2143-2020-2/syllabus#14]
Buenas tardes. Actualmente tengo instalado WSL2 en mi computador Windows, y conseguí instalar correctamente la versión 2.7 de Ruby (ver primera imagen). Sin embargo, al intentar instalar Rails mediante la consola me tira el siguiente error:
<img width="371" alt="dios" src="https://user-images.githubusercontent.com/42703907/90344597-191e1f80-dfe9-11ea-89c1-cb3ef281197d.PNG">
<img width="682" alt="diosplan" src="https://user-images.githubusercontent.com/42703907/90344598-1a4f4c80-dfe9-11ea-8ba2-968033e0ff69.PNG">
<img width="628" alt="diosplanes" src="https://user-images.githubusercontent.com/42703907/90344599-1ae7e300-dfe9-11ea-9a1b-8ff4928cfd34.PNG">
He intentado buscar en Internet pero no consigo solucionar el problema. Que podría hacer en esta situación?
De antemano muchas gracias

**Comment by daleal** [comment]
Podrías ejecutar `sudo apt-get install ruby-dev` y luego volver a intentar instalar `rails`? (Por cierto, te recomiendo instalar la última versión de `rails 5.2`, que sería `rails 5.2.4.3`)

**Comment by EstebanReyes1998** [comment]
Hola Daniel! Intenté hacer lo que mencionaste pero no funcionó. Sin embargo, al usar el comando sudo apt install ruby-railties funcionó. Muchas gracias por la ayuda igual.
