### ISSUE TITLE
Problema con deploy a Heroku

### ISSUE THREAD

**Issue by amparostevens** [IIC2143-2020-2/syllabus#141]
Hola!
No puedo hacer git push heroku master y no entiendo por qué. Para la entrega lo hice y funcionaba perfecto, pero ahora me sale error. 
He intentado de todo, busqué en Google pero nada funcionó, incluso cloné de nuevo el repositorio e hice una nueva app pero no funciona. Tengo instalado `bundler 2.1.4`. Y en la carpeta `tmp` no aparece ningún `buildpacks`, así que no se a qué se refiere. 

![error](https://user-images.githubusercontent.com/53883653/93288382-1b26fa00-f7b2-11ea-892a-b7a53f974a37.PNG)
![error2](https://user-images.githubusercontent.com/53883653/93288387-1cf0bd80-f7b2-11ea-87ff-054bfbb07b9c.PNG)

**Comment by daleal** [comment]
Hola! Aparentemente el error se debe a la versión de `ruby` que está usando Heroku. Puedes leer un poco más al respecto [en la documentación de Heroku](https://devcenter.heroku.com/articles/bundler-version#bundler-2-0-1). Por alguna razón, el _buildpack_ de Heroku está usando `ruby 2.6.0`, cuando tanto en tu `Gemfile` como en tu `Gemfile.lock` está especificada la versión `2.7` de `ruby`. Mi apuesta es que Heroku aún no soporta usar `ruby 2.7` y debe estar haciendo _fallback_ a `ruby 2.6.0`, pero como puedes leer en la documentación mencionada previamente, el _buildpack_ para `ruby 2.6.0` incluye una versión más antigua de `bundler`. Mi recomendación sería intentar especificar en el `Gemfile` la última versión de `ruby 2.6`, actualizar el archivo `Gemfile.lock`, hacer `git add`, `git commit` y luego hacer el `push` a Heroku.

**Comment by amparostevens** [comment]
Hola, hice lo que me dijiste y estuve leyendo la documentación pero sigo teniendo el mismo error. Al intentar hacer deploy vuelve a salir que usa `2.6.0` a pesar que lo actualicé y especifico en el `Gemfile` que quiero que use la `2.6.6`. Además me aparece que usa otra versión que ni siquiera es la 2.6.
![image](https://user-images.githubusercontent.com/53883653/93962328-fd691000-fd30-11ea-85c7-3f3d3aee850a.png)

**Comment by daleal** [comment]
Oh que extraño 🤔 Podrías intentar ejecutando `heroku buildpacks:set https://github.com/bundler/heroku-buildpack-bundler2` y luego haciendo el deploy?

**Comment by amparostevens** [comment]
Ahora funcionó!!! :tada: (qué era lo que estaba mal?)

Pero no puedo ver la aplicación 😢 me aparece lo siguiente: 
![image](https://user-images.githubusercontent.com/53883653/93965690-242b4480-fd39-11ea-8028-78d5df1a7ca2.png)
Y estos son los logs
![image](https://user-images.githubusercontent.com/53883653/93965780-5dfc4b00-fd39-11ea-9836-3a847be426bd.png)

**Comment by daleal** [comment]
🎉🎉🎉 Lo que pasa es que Heroku ocupa cosas llamadas _buildpacks_ para hacer el _build_ de tu aplicación, que corresponden a entornos predeterminados. A veces, falla en reconocer el entorno que debe usar y pasa lo que te pasó a ti (no estoy seguro de por qué falla). Con respecto a tu error actual, dado que el error original fue resuelto (y que el nuevo error ya está mencionado en una issue), cerraré esta issue. Por supuesto, si la issue con tu nuevo error no es capaz de resolverlo y tienes información nueva, puedes re-abrirla para continuar con las soluciones.

**Comment by maormeno** [comment]
> 🎉🎉🎉 Lo que pasa es que Heroku ocupa cosas llamadas _buildpacks_ para hacer el _build_ de tu aplicación, que corresponden a entornos predeterminados. A veces, falla en reconocer el entorno que debe usar y pasa lo que te pasó a ti (no estoy seguro de por qué falla). Con respecto a tu error actual, dado que el error original fue resuelto (y que el nuevo error ya está mencionado en una issue), cerraré esta issue. Por supuesto, si la issue con tu nuevo error no es capaz de resolverlo y tienes información nueva, puedes re-abrirla para continuar con las soluciones.

Hola! Disculpa lo tarde, yo sé que probablemente estaremos fuera de plazo para cuando veas esto, pero de todas maneras nos gustaría saber cómo solucionar ese error de code=H10, ya que llevamos varias horas con esto y no logramos encontrar la Issue a la que te refieres, ni alguna solución al problema. Muchas gracias.
