### ISSUE TITLE
Revisar rama Parent

### ISSUE THREAD

**Issue by hsazos** [IIC2143-2020-2/syllabus#142]
Hola,

Con mi grupo creamos ramas para las funcionalidades, pero no sabemos si esas ramas heredan desde development, o desde la rama master. Hay alguna manera de revisar como es la estructura del repositorio?

De antemano, gracias.

**Comment by daleal** [comment]
Hola! Al momento de crear una rama, esa rama hereda desde donde estés parado. Por ejemplo, para crear una rama desde `develop`, debes hacer lo siguiente:

```sh
git checkout develop  # checkout to base branch
git checkout -b my-new-feature  # create new branch
```

**Comment by johnowenatala** [comment]
Esto también te pueda servir. Cuando vas en github a ver el listado de ramas, puedes ver cómo están las ramas respecto a master (cantidad de commits atrás | cantidad de commits adelante):

<img width="936" alt="Screen Shot 2020-09-25 at 10 27 36" src="https://user-images.githubusercontent.com/4601442/94272718-d457a380-ff19-11ea-89af-13d5dccd69a5.png">

Por último, siempre tienes la opción de ver (por ejemplo), si hay un commit que sabes que tienes en develop y no en master, puedes ver si tu rama actual tiene o no ese commit (es fácil de ver gráficamente en github: )

<img width="1388" alt="Screen Shot 2020-09-25 at 10 30 08" src="https://user-images.githubusercontent.com/4601442/94272936-23053d80-ff1a-11ea-93d9-26cdf207d929.png">
