### ISSUE TITLE
Error para hacer git pull heroku master

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#144]
Hola. Resulta que quiero hacer "git pull heroku master" y no me resulta. Mis compañeros pueden, y se supone que todos somos colaboradores. 
Cuando lo hago me sale esto:
![image](https://user-images.githubusercontent.com/59337116/94850760-cd3f0280-03fd-11eb-9441-7e0aa765f147.png)
Qué podría ser?

**Comment by johnowenatala** [comment]
Ejecuta el comando git remote -v y ve que tengas a heroku en la lista de repositorios. Debieras obtener algo como esto:

```
git remote -v
heroku  https://git.heroku.com/thawing-inlet-61413.git (fetch)
heroku  https://git.heroku.com/thawing-inlet-61413.git (push)
```

Es muy probable que no tengas a heroku en la lista de repos. Te recomiendo que revises este link: https://devcenter.heroku.com/articles/git#for-an-existing-heroku-app

**Comment by jerosalazar** [comment]
Hola! te funcionó?

**Comment by Camila-sty** [comment]
hola, sí ya lo arreglé, gracias!
