### ISSUE TITLE
Error al hacer git pull

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#146]
Hola.
Después se seguir los pasos de la ayudantía de devise, quise hacer git push para subir los cambios al repo. Pero antes debía hacer git pull, pero ésto último me tira los siguientes errores;

![image](https://user-images.githubusercontent.com/59337116/95001369-b0423500-059f-11eb-8769-9878f3a57b80.png)

Luego me quise ir a la rama master pero tampoco me deja, me tira esto:

![image](https://user-images.githubusercontent.com/59337116/95001386-e5e71e00-059f-11eb-888f-f68693084d60.png)

Cómo lo puedo solucionar? llego horas intentándolo, incluso poniendo los errores en internet, pero nada me resulta.
Les agradecería mucho si me pudieran ayudar, gracias!

**Comment by jerosalazar** [comment]
Hola! Esto que te está pasando se debe a conflictos de git. Esto generalmente pasa cuando tienes cambios locales en los mismos archivos y líneas que los commits que están en el repo remoto y que estás tratando de hacer pull. De la misma forma, si tu tienes cambio que no están commiteados, git no te dejará cambiar de branch porque no sabe que hacer con esos cambios.
Una solución simple para esto es ocupar git stash. Con este comando guardas todos tus cambios no commiteados como un “borrador” y dejan de aparecer en tu branch actual para que puedas hacer pull o checkout libremente. En tu caso te recomiendo hacer esto:
* `git stash` para esconder tus cambios actuales en esta especie de borrador
* `git pull` para bajar los cambios nuevos del repositorio remoto
* `git stash pop` de esta forma retomas tus cambios locales que estaban guardados en el borrador y se aplican sobre los cambios que pulleaste 
* en este punto es probable que tengas conflictos, ya que si los cambios que pulleaste y los tuyos trabajan sobre una misma línea, git no sabe con cuál quedarse. Si el terminal te indica que tienes conflictos, revisa los archivos que mencione y ahí puedes elegir si te quedas con los cambios del pull o del stash

Espero que te sirva y cualquier duda sigue comentando no mas

**Comment by Camila-sty** [comment]
No me deja cambiarme de rama. 
Entonces tuve que hacerlo en master|MERGE. Y me tira error en todo. Antes había buscando cómo solucionarlo y me salía lo mismo que me recomendaste tu. Pero aún así no entiendo, porque me tira errores;
![image](https://user-images.githubusercontent.com/59337116/95023953-6ec09100-0656-11eb-8913-e39ac14f68e8.png)

**Comment by jerosalazar** [comment]
Revisa tu archivo gemfile.lock porque creo que significa que tienes conflictos en el

**Comment by jerosalazar** [comment]
Hola! te funcionó?

**Comment by Camila-sty** [comment]
sí, gracias
