### ISSUE TITLE
Error puerto conexión con postgres

### ISSUE THREAD

**Issue by rkarac** [IIC2143-2020-2/syllabus#147]
Hola, 
Tengo problemas nuevamente con el puerto de postgres :( . Había ya hecho una issue en el comienzo del curso donde me respondieron que tenía que agregar al 'database.yml' el puerto específico que utilizaba postgres en mi computador al pedir la contraseña ( que era "port: 5434") y en su momento me funcionaba perfecto lograr ver la página.

Ahora que hemos avanzado con la entrega 1, en un principio lograba ver las views pero ahora me aparece el siguiente error:

![WhatsApp Image 2020-10-03 at 18 06 13](https://user-images.githubusercontent.com/42577093/95001841-3ceef200-05a4-11eb-8fb9-830653bb77c3.jpeg)

![WhatsApp Image 2020-10-03 at 18 06 49](https://user-images.githubusercontent.com/42577093/95001839-3bbdc500-05a4-11eb-9146-2e32f58874fe.jpeg)

![WhatsApp Image 2020-10-03 at 18 07 39](https://user-images.githubusercontent.com/42577093/95001840-3ceef200-05a4-11eb-9fdf-f964dce088ca.jpeg)

No se que puedo hacer para poder arreglarlo

**Comment by meretamal** [comment]
Hola 😁 

Puede ser que no esté corriendo un servicio de postgres en ese puerto. Puedes ejecutar `sudo service postgresql start`?

**Comment by rkarac** [comment]
Sii, efectivamente no había ejecutado el comando, muchas gracias !!
