### ISSUE TITLE
Borrar modelo 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#148]
Hola!Tengo un problema, lo que pasa es que cuando cree un modelo me equivoque respecto al tipo de dato que queria asignarle a un elemento de este , sin embargo , cuando me di cuenta ya había ejecutado el rails db:migrate, intente destruir el modelo con rails destroy model "nombre del modelo" y procedi a crear un nuevo modelo con el mismo nombre pero con los tipos de datos correctos,y al intentar hacer el rails db:migrate me aparece el siguiente error, debo señalar que llame al modelo Carrete y también cree el controlado Carretes , no se si esto último tambien este relacionado pero lo menciono de igual forma.

Una forma de solucionarlo sería meterme directamente, por ejemplo desde pgAdmin 4, a la base de datos y borrar la tabla carrete desde ahí o no sería recomendable hacer eso ?.
![Captura de pantalla (121)](https://user-images.githubusercontent.com/62029138/95024854-17bdba80-065c-11eb-8e5d-ce88df73680a.png)
![Captura de pantalla (122)](https://user-images.githubusercontent.com/62029138/95024876-2c9a4e00-065c-11eb-9e8e-32ae91682d30.png)
![Captura de pantalla (123)](https://user-images.githubusercontent.com/62029138/95024878-2f953e80-065c-11eb-96a2-991fad9796d9.png)
![Captura de pantalla (124)](https://user-images.githubusercontent.com/62029138/95024879-31f79880-065c-11eb-8196-1fe267f1245c.png)
![Captura de pantalla (125)](https://user-images.githubusercontent.com/62029138/95024881-33c15c00-065c-11eb-9804-43bcf67b46ec.png)

**Comment by jerosalazar** [comment]
Hola! lo que está pasando es que la migración anterior creó la tabla de carretes en la db y tienes que deshacer ese cambio. Si corres `rails db:migrate:status` puedes ver todas las migraciones y si están corridas o no. Para deshacer la ultima migración que está up, puedes correr `rails db:rollback`. Te recomiendo que corras status antes y despues para checkear que todo esté bien

**Comment by RonaldoSosa** [comment]
Me aparece  lo siguiente:
![Captura de pantalla (127)](https://user-images.githubusercontent.com/62029138/95036212-9a1a9e80-069d-11eb-9eae-506627afa991.png), tendria que aparecerme otra migracion carrete, es que la que me aparece tiene el identificador que me aparecio cuando hice el nuevo modelo

**Comment by jerosalazar** [comment]
Puede ser que la del modelo antiguo se eliminó cuando hiciste el `model destroy`. Lo que puedes hacer en este caso, ya que eliminaste el archivo y no tienes como hacerle rollback es (si no tienes información importante en la db) `rails drop` para botar la db, `rails db:create` y `rails db:migrate` para volver a crearla y correr las migraciones desde 0.

Recuerda que nunca debes eliminar un archivo de migraciones a menos que le hayas hecho rollback y estes seguro de que no lo necesitarás

**Comment by RonaldoSosa** [comment]
Hola rails drop no me aparece como comando valido, creo que el correcto seria rake db:drop db:create db:migrate

**Comment by jerosalazar** [comment]
db:drop

**Comment by RonaldoSosa** [comment]
Ahora me funciona todo correctamente!! Gracias!!!!
