### ISSUE TITLE
Métodos

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#15]
Hola!!
Tengo una duda sobre a qué clase deberían pertenecer los métodos ```aprobados()```, ```reprobados()```, etc. ¿?

**Comment by meretamal** [comment]
Hola 😁 !! Queda a tu criterio cómo modelar esa parte.

**Comment by Camila-sty** [comment]
Ok!! Gracias 😄

**Comment by catalinamusalem** [comment]
Hola, los métodos deben pertenecer si o si a alguna de las clases que nos dan?
