### ISSUE TITLE
Can't find header files for ruby

### ISSUE THREAD

**Issue by gachondoj** [IIC2143-2020-2/syllabus#151]
Hola, recientemente tuve que hacer una maquina virtual nueva por problemas de memoria con la primera y al seguir los pasos de la ayudantia 2 denuevo, hice "bundle install" y me tira el siguiente error.
![issue](https://user-images.githubusercontent.com/48296516/95097182-91f54a00-0703-11eb-9c7c-a35af077c637.PNG)
He buscado en google como arreglarlo pero no he logrado nada.
Gracias de antemano.

**Comment by daleal** [comment]
Podrías hacer `sudo apt install ruby-dev` y volver a intentarlo?

**Comment by gachondoj** [comment]
Hola, lo hice y funciono
Muchas gracias!
