### ISSUE TITLE
Error al hacer db:rollback

### ISSUE THREAD

**Issue by mjespinoza** [IIC2143-2020-2/syllabus#153]
Holaa, me equivoque en algo al crear el modelo y ya habia hecho db:migrate, por lo que para deshacer la migracion intente usar rails db:rollback pero me tira el siguiente error:
![error1](https://user-images.githubusercontent.com/42595117/95269436-c2c2a580-080f-11eb-82d5-148df3d15ed2.JPG)
![error2](https://user-images.githubusercontent.com/42595117/95269456-cbb37700-080f-11eb-85aa-d41d916ea873.JPG)

Gracias de antemano.

**Comment by jerosalazar** [comment]
Hola, la primera linea del error dice que es posible que falte un end en alguna parte del archivo `config/routes`. Podrías mostrarme que tienes definido ahí?

**Comment by mjespinoza** [comment]
ya lo solucione, era eso!! gracias
