### ISSUE TITLE
Error con db:migrate

### ISSUE THREAD

**Issue by mldarquea** [IIC2143-2020-2/syllabus#154]
Hola! Siguiendo la ayudantía de devise todo va bien hasta antes del db:migrate (hasta  rails generate migration AddUsernameToUsers username:string sin problema), pero al correr esto me sale:
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
Qué puede estar pasando??

**Comment by jerosalazar** [comment]
Hola, quizas sea que postgres no está corriendo. Puedes asegurarte de hacerle start al servicio de postgres?

**Comment by mldarquea** [comment]
Estaba haciendo mal algo antes, gracias!!

**Comment by gachondoj** [comment]
Hola, tengo este mismo error
Como lo resolviste?
Gracias

**Comment by mldarquea** [comment]
holaa se me habia olvidado esto:
sudo service postgresql start
ojala te sirva!
