### ISSUE TITLE
Error base de datos proyecto

### ISSUE THREAD

**Issue by eugeizquierdo** [IIC2143-2020-2/syllabus#155]
Hola! Hice el modelo Carrete, luego lo borré, y borré también la base de datos. Luego, al crearlo denuevo, al poner rails db:migrate me sale el siguiente error:

![image](https://user-images.githubusercontent.com/53871813/95354386-bb94a980-089a-11eb-8187-d391ce0f1e25.png)
![image](https://user-images.githubusercontent.com/53871813/95354432-cd764c80-089a-11eb-944f-43861bbf5c33.png)
![image](https://user-images.githubusercontent.com/53871813/95354463-d6671e00-089a-11eb-865e-1d6fd4fd3b5b.png)
![image](https://user-images.githubusercontent.com/53871813/95354530-e3840d00-089a-11eb-91be-89c83d49cc2a.png)

Qué puede ser? 
Muchas gracias!!

**Comment by jerosalazar** [comment]
Hola, que atributos (y de que tipo) tiene tu modelo? parece ser que hay problema con algun atributo attachment

**Comment by eugeizquierdo** [comment]
Al generar el modelo, lo hice así:

rails g model Carrete titulo:string descripcion:string servicios:string comuna:string direccion:string capacidad_maxima:integer costo_total:integer estado_busqueda_asistentes:string imagen:attachment

Gracias.

**Comment by jerosalazar** [comment]
probablemente postgres no reconoce attachment como un tipo de atributo valido. Mi recomendación es que crees el modelo sin el atributo de imagen por ahora (si quieres mostrar el perfil de usuario pones un avatar de ejemplo por mientras) y eso lo implementan despues

**Comment by eugeizquierdo** [comment]
Perfecto, muchas gracias. Para cambiar esto, pongo model destroy "Carrete" y lo hago denuevo nomás? O necesito hacer algún paso más?
Y cómo se hace para agregar o eliminar campos de un formulario cuando el modelo ya está creado?

**Comment by jerosalazar** [comment]
Hola, ya que la migración no se ha corrido puedes editarla y quitar la linea de ese atributo. Para el resto de los archivos quizás deberías editar el controlador (si es que ocupas el param image en alguna parte) y para los formularios debes editar el html de la vista

**Comment by eugeizquierdo** [comment]
Ahí me funcionó!! Gracias.
Ahora me sale otro error que no logro arreglar....
En el archivo routes.rb tengo esto:

Rails.application.routes.draw do
  #create
  get "carretes/new", to: "carretes#new"
end

Y cuando corro "rails server" me sale el siguiente error:
/home/meizquierdo/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load': /mnt/c/Users/Mª Eugenia Izquierdo/Desktop/Ingeniería de Software/grupo68-proyecto/config/routes.rb:4: syntax error, unexpected string literal, expecting `do' or '{' or '(' (SyntaxError)
  get "carretes/new", to: "carretes#new"


Muchas gracias.


Adjunto fotos para que sea mas claro:
![image](https://user-images.githubusercontent.com/53871813/95461113-34a00980-094c-11eb-8e1d-95867dc44f68.png)

![image](https://user-images.githubusercontent.com/53871813/95461078-2c47ce80-094c-11eb-8fd7-a2b921ce9aee.png)

**Comment by jerosalazar** [comment]
te sale el mismo error si solo lo dejas como `get 'carretes/new'`?

**Comment by jerosalazar** [comment]
muestrame que tienes en ru archivo routes.rb porfa

**Comment by jerosalazar** [comment]
con respecto al fin de linea, cambiaste algo en tu git config?

**Comment by eugeizquierdo** [comment]
Aqui va el archivo:
![image](https://user-images.githubusercontent.com/53871813/95470985-ca8d6180-0957-11eb-94f3-06f3bc12db83.png)

Y supongo que no cambie nada en el git config (no sé bien a qué te refieres con eso, es un archivo?)

Gracias

**Comment by jerosalazar** [comment]
ve si te funciona borrando todos los comentarios

**Comment by eugeizquierdo** [comment]
Lo hice y me sale el mismo error....
/mnt/c/Users/Mª Eugenia Izquierdo/Desktop/Ingeniería de Software/grupo68-proyecto/config/routes.rb:2:in `block in <main>': undefined method `get ' for #<ActionDispatch::Routing::Mapper:0x000055a9adf5eab8> (NoMethodError)
Did you mean?  get
                          gets

**Comment by jerosalazar** [comment]
hmmm está muy raro. Será que hay un espacio extra despues del get?

**Comment by eugeizquierdo** [comment]
Lo escribi denuevo para ver si se arreglaba y parece que sí, porque ahora me sale otro error..... Como que no reconoce el modelo "Carrete"

![image](https://user-images.githubusercontent.com/53871813/95478794-615e1c00-0960-11eb-916d-63503d707f70.png)

**Comment by jerosalazar** [comment]
probablemente sea `Charretes`

**Comment by johnowenatala** [comment]
Hola, podrías pegar un pantallazo para ver el modelo, incluyendo cómo se llama el archivo y el contenido del modelo?
