### ISSUE TITLE
Error para ver la página localhost:3000

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#156]
Hola!
Tengo problemas para ver página localhost:3000.
En wsl hago lo siguiente:
![image](https://user-images.githubusercontent.com/59337116/95375621-4040f100-08b6-11eb-9c63-cc8a5d61d731.png)
Y esto es lo que me sale en la página
![image](https://user-images.githubusercontent.com/59337116/95375684-52229400-08b6-11eb-8c51-2039309cf4b6.png)
Al parece mi contraseña de usuario de postgres es incorrecta, pero según yo está bien. Cómo podría cambiarla suponiendo que se me "olvidó" ?.  Si me puede recomendar alguna página para poder hacerlo o si me puede decir qué código ingresar, se los agradecería mucho. Yo no he podido resolverlo, ni siquiera siguiendo lo que he encontrado en algunas páginas de internet.
Gracias!

**Comment by jerosalazar** [comment]
Puede ser que tienes una contraseña en tu usuario postgres distinta a la que definiste en tu `config/database.yml`.

Prueba lo siguiente:

* Recuerda partir el servicio de postgres si no está corriendo
1. `sudo -u postgres psql` para entrar a la consola de postgres
2. dentro de la consola de postgres corre `\password postgres`. Este comando es para cambiarle la contraseña al usuario "postgres". Te va a decir "Enter new password" y le escribes la contraseña que tienes definida en tu archivo `database.yml`

**Comment by Camila-sty** [comment]
sí, tenía una contraseña distinta. Hice lo que me dijiste para cambiar la contraseña a la que está en `database.yml`.
Luego cerré la consola e intente hacer el mismo proceso, pero no me reconoce la contraseña que cambie ..
![image](https://user-images.githubusercontent.com/59337116/95379555-e80ced80-08bb-11eb-81a4-0e9599c4a226.png)

**Comment by jerosalazar** [comment]
Ahi tienes que seguir ocupando la contraseña de sudo. La contraseña de la base de datos es aparte y no debería ser necesario que la escribas en el terminal para comenzar o detener el servicio de postgres

**Comment by Camila-sty** [comment]
ok, gracias!

**Comment by jerosalazar** [comment]
Avisame si te funciona

**Comment by Camila-sty** [comment]
sí, me funcionó

**Comment by jerosalazar** [comment]
recuerda cerrar las issues si no tienes mas dudas con ese tema

**Comment by Camila-sty** [comment]
yo tengo que cerrarlas? y cómo se hace? xd

**Comment by jerosalazar** [comment]
Esta ya la cerré, pero cuando esté resuelta tu duda apreta el boton al lado de "comentar" que dice "cerrar issue"

**Comment by Camila-sty** [comment]
ah ya gracias 👍
