### ISSUE TITLE
FATAL: la contraseña de autentificación fallo para el usuario postgres

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2143-2020-2/syllabus#157]
![image](https://user-images.githubusercontent.com/53879072/95378071-c7439880-08b9-11eb-8f62-96758ac772d3.png)

Hola, como puedo solucionar esto ?.

**Comment by jerosalazar** [comment]
Hola, trata lo que puse en #155 y dime si te funciona

**Comment by DiegoPibe** [comment]
hola, ya lo habia intentado, lo intente de nuevo por siacaso y tampoco sirvio :C

**Comment by jerrazuriz99** [comment]
trata de cambiar el puerto de tu proyecto, mira en #111

**Comment by DiegoPibe** [comment]
siiiiiiii eso eraaaaa, muchas gracias <3
