### ISSUE TITLE
ActionController::ParameterMissing (param is missing or the value is empty: ReporteAUsuario):

### ISSUE THREAD

**Issue by jerrazuriz99** [IIC2143-2020-2/syllabus#158]
al crear un reporte, no se crea nada y me sale ese error

**Comment by oscars810** [comment]
Hola!
Puedes poner mas información?, como que estas intentando crear (no sé que es un reporte), un poco de codigo donde falla, etc.

**Comment by jerrazuriz99** [comment]
![Captura1](https://user-images.githubusercontent.com/53884268/95500623-6e3d3880-097d-11eb-8ba8-1b1c41246906.JPG)

**Comment by jerrazuriz99** [comment]
![Captura2](https://user-images.githubusercontent.com/53884268/95500660-81e89f00-097d-11eb-9c7d-469151600bed.JPG)

**Comment by jerrazuriz99** [comment]
![Captura3](https://user-images.githubusercontent.com/53884268/95500675-87de8000-097d-11eb-9c51-3bb1e1483355.JPG)

**Comment by jerrazuriz99** [comment]
![Captura4](https://user-images.githubusercontent.com/53884268/95500686-8d3bca80-097d-11eb-9c06-14b3f031896c.JPG)

**Comment by jerrazuriz99** [comment]
son:
-vista
-controlador
-routes
-erros

**Comment by oscars810** [comment]
Hola! (Perdon por la demora)

Si no has solucionado tu problema aún... Rails te está diciendo que faltan parametros y revisando el codigo no veo nada de malo, por lo que te recomiendo printear los parametros en el controlador para ver como están llegando y si efectivamente falta uno. Tambien, siempre que haces un `post`, te aparece en consola por defecto las cosas que estás enviando de la siguiente manera:
![Screenshot_20201009_173745](https://user-images.githubusercontent.com/53796555/95630152-b6c92480-0a57-11eb-9869-bc57248f5ef9.png)
Por lo que puedes revisar como están saliendo tambien.

---

Como consideración extra, ruby usa `snake_case`, entonces te recomiendo no usar variables con `CamelCase` y/o mayusculas al principio porque generalmente hacen referencia a los modelos y en algun momento te podría traer problemas.

**Comment by johnowenatala** [comment]
Lo que te está pasando es que cuando haces el params.require(:ble), tu estás exigiendo que venga ese parámetro, pero no viene - en este caso, params[:ReporteAUsuario].
Te recomiendo que arregles lo que dice oscars810, porque te puede estar trayendo más de algún problema (el usuario cosas como :ReporteAUsuario o @ReporteAUsuario en lugar de :reporte_a_usuario o @reporte_a_usuario) y que veas qué parámetros te están llegando al request.
