### ISSUE TITLE
Datatype Imagen

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2143-2020-2/syllabus#159]
Hola, quería saber en que formato tengo que poner las imagenes al crear un CRUD. ¿Cuál es su datatype?

**Comment by daleal** [comment]
Hola! Para poder usar imágenes, probablemente deberás usar una _feature_ de Rails llamada `ActiveStorage`. Te recomiendo leer la documentación! Ojo que en Heroku, guardar las imágenes "localmente" no funciona (el sistema de archivos de Heroku es _efímero_, se borra cada cierto tiempo), por lo que deberás usar algo como Cloudinary.
