### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#16]
Hola!
Tengo un error al hacer el cálculo de la nota de proyecto. La verdad es que no entiendo por qué me lo tira, al principio escribí la formula con paréntesis incluidos, se los saqué pensando que esa era el problema, pero no se arregló.
Les adjunto la imagen del error, para ver si me pueden ayudar a identificarlo. Gracias!!
![image](https://user-images.githubusercontent.com/59337116/90353266-d58cdb00-e013-11ea-9b78-9641447c4735.png)

**Comment by lisraelrat1** [comment]
Hola Cami! 
Si te fijas en el error dice que se está esperando un end, esto significa que probablemente más arriba (antes de la linea "nota" = 0.5 * ....") te haya faltado agregarle el end a una función o a alguna otra sentencia. 
Ojalá te sirva :)

**Comment by Camila-sty** [comment]
@lisraelrat1  ese podría ser el único problema?, es que tengo todos los "end" :(

**Comment by jerosalazar** [comment]
Podrías mostrar que tienes en las líneas anteriores y posteriores?

**Comment by Camila-sty** [comment]
la operación matemática que hago para el cálculo de la nota lo hago dentro de un método de una clase, la cual termina con un "end". Antes de eso tengo lo siguiente:
```
class Evaluations 
    def initialize()
        @nota_catedra = 0 
        @nota_proyecto = 0
    end 

    def nota_catedra(i1, i2, ex)
        nota = (i1 + i2 + ex) / 3
        @nota_catedra = nota
    end
```

**Comment by Camila-sty** [comment]
Después de lo anterior viene lo siguiente:
```
def nota_proyecto(e0, e1, e2, e3, ef, p)
        nota = 0.5 ∗ (e0 + e1 + e2 + e3) / 4 + 0.2 ∗ ef + 0.3 ∗ p
        @nota_proyecto = nota
    end

    def promedio()
        if @nota_catedra >= 4.0 and @nota_protecto >= 4.0 #aprueba
            nota = (0.5 * @nota_catedra) + (0.5 * @nota_proyecto)
            return True, nota
        else  #reprueba
            nota = MIN(3.9, (0.5 * @nota_catedra) + (0.5 * @nota_proyecto))
            return False, nota
        end
    end 
end
```
son los métodos que pertenecen a la misma clase.

**Comment by jerosalazar** [comment]
Me aparece que los asteriscos que ocupas en esa fila son distintos a los de las otras, los cambié por asteriscos normales y me dejó de salir el error. Ve si eso te funciona

**Comment by Camila-sty** [comment]
😲 eso era jajaja, estaba difícil de notar, gracias!! 😄
