### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by gachondoj** [IIC2143-2020-2/syllabus#160]
Hola, estoy tratando de editar un carrete pero al momento de hacer @carrete.update(@carrete_params) me dice:
ArgumentError (When assigning attributes, you must pass a hash as an argument)

No se por que pasa, al hacer lo mismo con save en vez de update funciona perfecto

**Comment by betojarav** [comment]
Me pasa algo similiar! Pero en vez de: "_**ArgumentError (When assigning attributes, you must pass a hash as an argument)"**_ 
me sale:  **syntax error, unexpected tSTRING_BEG, expecting do or '{' or '('**

**Comment by jerosalazar** [comment]
tienes definido carrete_params como un metodo privado? si es asi debes pasarlo sin el @

**Comment by gachondoj** [comment]
trate sin el @ y me dice que no esta definido carrete_params

**Comment by gachondoj** [comment]
Ya lo arregle, había un @ extra al definir la variable
