### ISSUE TITLE
Error PG::ConnectionBad (FATAL:  la autentificacin password fall para el usuario postgres )

### ISSUE THREAD

**Issue by mafernandez9** [IIC2143-2020-2/syllabus#163]
Hola! tengo un error y me gustaría saber si podrían ayudarme. Actualmente no puedo iniciar la aplicación en mi computador con localhost 3000, se ve de la siguiente forma:
![error software](https://user-images.githubusercontent.com/53874019/95400297-b22e3000-08e0-11eb-89ae-a8ac865f4116.PNG)
![error2software](https://user-images.githubusercontent.com/53874019/95400300-b3f7f380-08e0-11eb-9899-8bcc6829426b.PNG)

Mientras que a mis compañer@s se les ve de la siguiente forma:
![image](https://user-images.githubusercontent.com/53874019/95400361-c83bf080-08e0-11eb-80bc-537675a9a76e.png)

Debo señalar que estuve viendo las issues anteriores,  y ninguna pudo solucionar este problema. Muchas gracias de antemano!

**Comment by Gaonuk** [comment]
Tienes puesta la misma contraseña de postgres que tus compañeros en el archivo database.yml?

**Comment by mafernandez9** [comment]
Si, la actualicé a la misma que ese archivo

**Comment by Gaonuk** [comment]
Y la actualizaste localmente? usaste el comando ```sudo -u postgres psql``` y luego ```\password``` y pusiste la contraseña de tu equipo?

**Comment by mafernandez9** [comment]
Exacto

**Comment by jerrazuriz99** [comment]
tenia el mismo error, tienes que cambiar el puerto de tu proyecto

**Comment by mafernandez9** [comment]
Hola! como puedo cambiar el puerto? hay algun comando o algo asi?

**Comment by jerrazuriz99** [comment]
mira esta issue #111

**Comment by mafernandez9** [comment]
No me funcionó, me tira este error ahora:
PG::ConnectionBad (could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5434?

**Comment by daleal** [comment]
Hola @mafernandez9! El puerto e `5432`, no `5434`

**Comment by mafernandez9** [comment]
Hola! los intenté ambos, y ninguno solucionó el problema, me sigue tirando el mismo error 
PG::ConnectionBad (FATAL:  la autentificacin password fall para el usuario postgres
):

**Comment by daleal** [comment]
Podrías enviar el contenido de tu `config/database.yml`?

**Comment by mafernandez9** [comment]
![image](https://user-images.githubusercontent.com/53874019/95865062-9988a480-0d3c-11eb-843d-39365fbd0560.png)
Sisi, ahí va!

**Comment by daleal** [comment]
Ok, me parece que encontré el problema. En el archivo `pg_hba.conf` de Postgres (debería estar en una dirección parecida a `C:\Program Files\PostgreSQL\<version>\data`) probablemente haya una línea como la siguiente:

```
local   all    all     peer
```

Cambia esa línea para que diga lo siguiente:

```
local   all    all     md5
```

Reinicia tu computador y debería funcionar todo bien.

**Comment by mafernandez9** [comment]
Hola! Me sale eso en las líneas que no estan comentadas, debería agregar la línea que mandaste tu?
![image](https://user-images.githubusercontent.com/53874019/96543119-0f7b9700-127a-11eb-8fce-a87f2ea288b1.png)

**Comment by meretamal** [comment]
Hola 😁 

Solo para poder ir descartando algunos posibles problemas, podrías cambiar los `md5` a `trust`, reiniciar tu servicio de postgres y ver si funciona?

**Comment by mafernandez9** [comment]
Esto último arreglo mi problema!!! muchisimas graaciaaasss <3<3 !!!
