### ISSUE TITLE
CRUD update

### ISSUE THREAD

**Issue by betojarav** [IIC2143-2020-2/syllabus#164]
Hola! Estoy haciendo el update de carrete siguiendo los pasos de la ayudantía pero al momento de correr la vista asociada me sale: 
_syntax error, unexpected tSTRING_BEG, expecting do or '{' or '('_ en la línea: **redirect_to carrete_path(@carrete.id), notice "Bacán! editaste un carrete"** No he podido encontrar qué significa el error tSTRING_BEG

**Comment by Gaonuk** [comment]
podrias mandar un pantallazo de la linea donde tienes el error?

**Comment by betojarav** [comment]
![image](https://user-images.githubusercontent.com/40377725/95484728-362afb00-0967-11eb-9f22-122b5b7e0595.png)
Esa es

**Comment by Gaonuk** [comment]
Veo que despues del notice te falta el ```:``` prueba ver si eso es lo que causa el error.

**Comment by betojarav** [comment]
Eso era! muchas gracias jajaja
