### ISSUE TITLE
ayudantía 4

### ISSUE THREAD

**Issue by cotefon** [IIC2143-2020-2/syllabus#165]
Hola! :smiley: que en la ayudantía 4, Oscar al momento de crear el modelo ejecuta el siguiente código:
rails g model Serie nombre:string puntuacion: integer comentario: string

mi duda es si quiero guardar por ejemplo un afiche de la imagen, que tengo que poner ?  :sweat_smile:

**Comment by Gaonuk** [comment]
Hola! Podrias por ejemplo guardar el path o la url de la imagen como un String.
