### ISSUE TITLE
Problema con postgres - psql 

### ISSUE THREAD

**Issue by diegopcalderon** [IIC2143-2020-2/syllabus#166]
Hola!! 
Intente meterme a postgres siguiendo los pasos de la ayudantia de Setup, pero cuando pongo el comando "psql" me sale el siguiente error. 
![Captura de pantalla de 2020-10-08 01-08-42](https://user-images.githubusercontent.com/53881413/95414133-7e183680-0903-11eb-9bb8-8dba840937f1.png)

**Comment by Gaonuk** [comment]
#87
