### ISSUE TITLE
Duda salto de línea de LF a CRLF

### ISSUE THREAD

**Issue by eugeizquierdo** [IIC2143-2020-2/syllabus#168]
Hola!
Cuando subo archivos a una rama del repositorio de mi grupo de proyecto me sale lo siguiente:

![image](https://user-images.githubusercontent.com/53871813/95474624-b64b6380-095b-11eb-9a45-e9e8c03dea20.png)

Afecta en algo?

Muchas gracias.

**Comment by daleal** [comment]
Hola! Lo que sucede es que, por razones históricas, los saltos de línea funcionan distinto en sistemas `UNIX` (_e.g._ Linux y macOS) que en sistemas `MS` (_e.g._ Windows). En sistemas `UNIX`, los saltos de línea son representados como `\n`, llamado _Line Feed_ (o `LF`), mientras que en `MS`, los saltos de línea son representados como `\r\n`, `\r` siendo llamado _Carriage Return_ (o `CR`), por lo que, en conjunto, se les conoce como `CRLF`. Y cual es el problema? Bueno, resulta que `git` se las da de genio, y, por detrás de escena, convierte los saltos de línea del código a los saltos de línea adecuados. Eso quiere decir, por ejemplo, que si uno de mis compañeros escribe código desde macOS y lo pushea a GitHub, al hacer `git pull` en mi máquina con Windows, `git` transforma los saltos de línea que escribió mi compañero de `LF` a `CRLF`. Lo que te sucedió a ti fue que tu editor de texto, que también se las da de genio, decidió (como la mayoría hace por _default_) **ignorar el tipo de salto de línea que le gusta a Windows**, y guardar todo con `LF` (por temas de compatibilidad con otros desarrolladores, es lo más adecuado). Y aquí, el problema fue que, al hacer pasar esos archivos con `LF` por `git`, éste detectó que estás en un sistema `MS` **y decidió cambiar los saltos de línea a los preferidos por Windows**. En general, no debería haber ningún problema con que `git` haga esto, solamente que tus archivos van a vivir con `CRLF` en tu máquina local. De cualquier manera, si quisieras trabajar con `LF` en tu máquina local, puedes decirle a `git` que **no** transforme tus saltos de línea `LF` a `CRLF` y que además convierta cualquier salto `CRLF` que alguien más pushee, utilizando el siguiente comando:

```sh
git config --global core.autocrlf input
```

**Comment by eugeizquierdo** [comment]
Perfecto, muchas gracias!!!
