### ISSUE TITLE
Relacion CRUD y gema devise

### ISSUE THREAD

**Issue by hsazos** [IIC2143-2020-2/syllabus#169]
Hola!

Hay algo que no me queda claro al implementar devise y los CRUDs. Según lo que entendí, devise es una gema que te permite registrar y autentificar usuarios, y de hecho, viene con una tabla por defecto. Pero cuando hacemos el CRUD del Cliente (por ejemplo), también hay que crear una tabla... entonces eliminamos la que viene con devise y creamos nuestra propia tabla?, o partimos en base a lo que esta gema nos entrega?
Otra duda: En caso de que tengamos que partir por lo que nos entrega devise (tabla "users"), si quisiéramos hacer dos ingresos de usuarios distintos (Clientes: para crear y asistir a eventos. Servicios: para entregar servicios a los eventos) es posible? O necesariamente tenemos que partir de un usuario común y después darles la opción de entregar un servicio?

Salu3

**Comment by mpbascunan** [comment]
Hola, 
Devise básicamente te crea el modelo de usuario y todo lo relacionado a este, por lo tanto, no es necesario que crees tablas o modelos de usuario por tu cuenta. Aunque puedes hacerlo, pero no es recomendable dado todo lo que te provee esta gema. Entonces, si ya tienes tu crud de Cliente te recomendaría borrarlo y sólo quedarte con lo de Devise, osea partir en base a lo que la gema entrega.
Respondiendo tu otra duda, sí es posible hacer lo que dices, de hecho en la documentación de Devise te explican cómo hacerlo. Aquí te dejo el link : https://github.com/heartcombo/devise/wiki/How-to-Setup-Multiple-Devise-User-Models 
Ojalá te sirva, éxito! :)

**Comment by hsazos** [comment]
Gracias!
