### ISSUE TITLE
Problema con rails spec

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#172]
Hola!Cuando hice git pull al repositorio de nuestro proyecto y traje los cambios implementados por mis compañeros e intente hacer un rails spec me aparecen los siguientes errores  los cuales no logro solucionar , en mi caso para los del modelo Comuna debido a que no fue creado de manera local me mandan esos errores del principio????? y respecto a los ejemplos que fallan me indican que estan en spec/requests sin embargo yo no edite esa carpeta en ningun momento , significa de basta con comentar lo que hay en ella para dar solucion a este problema? 
![Captura de pantalla (131)](https://user-images.githubusercontent.com/62029138/95514959-3ccf6780-0993-11eb-8402-1cfad4f5eba4.png)
![Captura de pantalla (132)](https://user-images.githubusercontent.com/62029138/95514963-3fca5800-0993-11eb-8b13-b71db5ae13d4.png)
![Captura de pantalla (133)](https://user-images.githubusercontent.com/62029138/95514967-422cb200-0993-11eb-811d-09f103dc0c15.png)
![Captura de pantalla (134)](https://user-images.githubusercontent.com/62029138/95514978-448f0c00-0993-11eb-8fe0-e0b3f5469dc5.png)
![Captura de pantalla (135)](https://user-images.githubusercontent.com/62029138/95514991-4789fc80-0993-11eb-9ff8-b85f689f2c16.png)

**Comment by dpvillarroel** [comment]
Cómo resolviste tu problema? a mi me pasa lo mismo y aun no encuentro el error

**Comment by RonaldoSosa** [comment]
Hola!
