### ISSUE TITLE
Problema RSPEC id = 'show'

### ISSUE THREAD

**Issue by dpvillarroel** [IIC2143-2020-2/syllabus#173]
Hola, 

Todo mi grupo tiene el mismo problema que cuando corremos el comando Rspec nos sale este error diciendo que no encuentra el parámetro con id = 'show'

`
  4) Carretes GET /edit returns http success
     Failure/Error: @carrete = Carrete.find(params[:id])
     
     ActiveRecord::RecordNotFound:
       Couldn't find Carrete with 'id'=edit
     # ./app/controllers/carretes_controller.rb:8:in `show'
     # /Users/dpvillarroel/.rvm/gems/ruby-2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
     # /Users/dpvillarroel/.rvm/gems/ruby-2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /Users/dpvillarroel/.rvm/gems/ruby-2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call' `
<img width="1237" alt="Captura de Pantalla 2020-10-08 a la(s) 20 00 29" src="https://user-images.githubusercontent.com/53846238/95521852-f8e35f00-09a0-11eb-8ef6-95fc3572c9a1.png">

**Comment by JosefaPaz** [comment]
Hola! 

No soy ayudante pero el problema va porque en la url cuando accedes a un comentario, al 1 por ejemplo, se accede de la forma http://localhost:3000/comments/1, entonces cuando dices http://localhost:3000/comments/show, intenta buscar el comentario con id "show". 

Aún no sé solucionarlo, pero por lo que he leído en internet no pareciera ser necesario, si averiguo algo más lo comento jajaj

Éxito!

**Comment by daleal** [comment]
Ese es exactamente el problema! Para editar el recurso de id `2`, la ruta debería ser `/resources/2/edit`, y para mostrarla, la ruta debería ser `/resources/2/show`. Probablemente, estás saltándote el `id` en la ruta, y buscando directamente `/resources/edit` y `/resources/show`.

**Comment by dpvillarroel** [comment]
Pero en routes.rb tengo las rutas tal cual como las mencionas `/resources/2/edit` y `/resources/2/show`. O donde te refieres que estoy saltándome el `id` en la ruta.

**Comment by JosefaPaz** [comment]
@dpvillarroel  si no me equivoco te la estarías saltando en los test unitarios :eyes:

**Comment by dpvillarroel** [comment]
Perdón lo perdida :( pero los test unitarios serian por ejemplo carretes_request_rspec.rb? Por que ahí también los tengo de la forma `/resources/:id/edit` y no funciona. Lo unico que me sirvió fue comentar esa parte.

**Comment by JosefaPaz** [comment]
@dpvillarroel Noo tranqui! yo también estaba re perdida jajajaja S[i, el test sería en la ruta que mencionas. Recién lo pude solucionar y lo que revisé fue lo siguiente: (en tu caso con los Carretes)

* estar creando un carrete para probar el test
* obtener con get la ruta especifica
* probar lo que quieras testear con el test

**Comment by johnowenatala** [comment]
lo que te está fallando es que cuando llamas la acción en el test, tienes que llamarla como lo harías en la vida real, por ejemplo, 
get "/resources/2/edit" # con eso harás un GET a la acción edit del recurso con id 2.

yo lo haría algo como esto:

let(:carrete_de_prueba){ create(:carrete) }

it 'el test' do
get "/carretes/#{carrete_de_prueba.id}/edit"
expect( ...lo que quieras probar ...
end
