### ISSUE TITLE
problemas con merge a master, y deploy a heroku

### ISSUE THREAD

**Issue by mgbriones** [IIC2143-2020-2/syllabus#174]
hola tenemos problemas para hacer el merge a master pq git nos dice que hay conflicto entre algunos archivos, pero no podemos resolverlos.

Intentamos hacer deploy  a heroku desde develop pero tampoco nos permite hacerlo.
Que podemos hacer?

![image](https://user-images.githubusercontent.com/53794443/95534491-68b31300-09bc-11eb-8ca8-e1f57768de0f.png)

**Comment by daleal** [comment]
Hola! Para resolver ese tipo de conflictos, deben hacer un `merge` localmente. La forma de hacer esto es la siguiente:

```sh
git pull  # Actualizar el repositorio local
git checkout my-feature-branch  # Moverse a la branch de la feature
git merge develop  # Hacer merge de develop hacia la branch de la feature
```

En este momento, la consola debería decirte que no se puede hacer el merge automáticamente. Si abres tu editor de texto, verás algunos archivos marcados en un color distinto a los demás. Dichos archivos contienen dentro de ellos trozos de código tanto de la rama `my-feature-branch` como de la rama `develop`. Los trozos deberían estar marcados con colores, parecido a esto:

![merge-conflict](https://user-images.githubusercontent.com/37158127/95550444-4bdc0700-09df-11eb-920e-0a03cf565691.png)

Eso representa un conflicto que `git` no es capaz de resolver automáticamente porque no es lo suficientemente inteligente 😢 pero tú si puedes! Lo que debes hacer es dejar solamente el código que quieres que quede luego del _merge_ (la mayor parte de las veces vas a querer una de las dos versiones, pero a veces quieres "mezclarlas", y tendrás que hacerlo en el editor de texto).

Una vez guardados todos los cambios, en tu consola debes hacer `git add` de todos los archvios editados, y luego `git commit` para hacer un `commit` del _merge_ de `develop` a `my-feature-branch`. Al hacer `git push`, se actualizará _automagicamente_ tu Pull Request con el nuevo commit, y los conflictos desaparecerán.
