### ISSUE TITLE
Problema al cargar una imagen 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#176]
Hola! Para intentar agregar una imagen use la gema Paperclip y también use el ImageMagick ,use  la siguiente guía  https://guias.makeitreal.camp/ruby-on-rails-i/carga-de-imagenes , sin embargo al momento de cargar la imagen me aparece el siguiente error:
![Captura de pantalla (142)](https://user-images.githubusercontent.com/62029138/95590209-24eff600-0a1c-11eb-81ac-2db81e55f0e3.png)
![Captura de pantalla (143)](https://user-images.githubusercontent.com/62029138/95590213-27525000-0a1c-11eb-85b8-26d1deec6242.png)
Esto tiene que ver la extenión de la imagen que intento subir ?

**Comment by johnowenatala** [comment]
No uses paperclip. Aunque paperclip es una gema maravillosa, no estás resolviendo tu problema - probablemente sólo te estarás hundiendo más y más.
Paperclip fue reemplazado por algo que viene incorporado en Rails hace un rato, ActiveStorage.

Te recomiendo leer al respecto (es mucho más simple de usar que paperclip):
https://guides.rubyonrails.org/v5.2/active_storage_overview.html

**Comment by RonaldoSosa** [comment]
Entendido!Intentaré hacer de ese modo , gracias!

**Comment by daleal** [comment]
Ojo que con `ActiveStorage` resuelves el problema de hacer el "link" entre el código y la imágen, pero no se resuelve el almacenamiento de la imagen. En tu computador, puedes usar el almacenamiento local, pero en Heroku, el sistema de archivos se borra cada cierto tiempo, por lo que tendrás que usar algo como [Cloudinary](https://cloudinary.com/documentation/rails_activestorage) para almacenar las imágenes.

**Comment by RonaldoSosa** [comment]
Entendido también tendré en cuenta eso , gracias!
