### ISSUE TITLE
problemas con heroku 

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#177]
Holaa!
Tenemos problemas con la aplicación en heroku, al poner el path de cualquier vista nos sale el mismo error siempre;
![image](https://user-images.githubusercontent.com/59337116/95592450-03dcd480-0a1f-11eb-8525-6aee0c807420.png)
Luego ejecuté el comando para ver si estaba ok la instalación de heroku, y me sale lo siguiente:
![image](https://user-images.githubusercontent.com/59337116/95592387-f0ca0480-0a1e-11eb-979a-79c31d52184b.png)
Esto no lo entiendo, por qué tira estos errores? y cómo podría solucionarlo?
Gracias!

**Comment by meretamal** [comment]
Hola 😁 

Ejecutaste la migraciones? Si no lo hiciste, puedes correr `heroku run rails db:migrate`?

**Comment by Camila-sty** [comment]
sí, lo hice también, y me sale lo mismo;
![image](https://user-images.githubusercontent.com/59337116/95594600-8ebece80-0a21-11eb-9a71-9bff47a5a611.png)

**Comment by Camila-sty** [comment]
Ya lo solucioné, gracias!

**Comment by fmaturanaa** [comment]
Hola Camila! Como solucionaste este problema?  Tenemos lo mismo repetidas veces.

**Comment by Camila-sty** [comment]
Hola @fmaturanaa. 
Primero puedes ver qué está pasando en `dashboard.heroku.com/apps/<nombre app>/logs` . Ahí te saldrán los errores.
Y yo lo solucione con `heroku run rails db:migrate`ejecutándolo en wsl con directorio del proyecto. La verdad es que sabía que con este comando lo podría solucionar pero a mi me tiraba los errores que mencioné arriba, así que le pedí a mi compañero de proyecto que lo ejecutara y se pudo, se arregló. 😁
Ojalá te sirva!
