### ISSUE TITLE
problemas con heroku

### ISSUE THREAD

**Issue by mgbriones** [IIC2143-2020-2/syllabus#178]
Hola intentamos hacer deploy pero nos rechaza constantemente. Nos dice que hubo problemas con la intalacion de la gemas.
Que se puede hacer?
(tratamos hacer deploy desde master) 
![image](https://user-images.githubusercontent.com/53794443/95598591-7ef5b900-0a26-11eb-8723-139d85cc97a2.png)

**Comment by meretamal** [comment]
Hola 😁 

Puedes ejecutar `rails app:update:bin`, volver a hacer un _commit_ y hacer el _push_ a heroku?

**Comment by mgbriones** [comment]
lo hicimos y me sale method not allowed
