### ISSUE TITLE
Error al crear test vista show

### ISSUE THREAD

**Issue by aljara97** [IIC2143-2020-2/syllabus#179]
Hola, estoy tratando de hacer un test de request cuando quiero acceder a la vista de un servicio en mi proyecto. En el método describe creo un it que se encarga de hacer un nuevo servicio con el método create y save, pero cuando intento llamar a la ruta de la forma:
```
      service_id = @servicio.id
      get "/services/:service_id"
```
Pero al hacer `rails spec` arroja el siguiente error
```
Failures:

  1) ServicesController /services/show should return a successful request
     Failure/Error: @service = Service.find(params[:id])

     ActiveRecord::RecordNotFound:
       Couldn't find Service with 'id'=:service_id
```

**Comment by oscars810** [comment]
Hola!
Tienes que pasarle el id de otra forma al url porque ahí estás intentando sacarlo con `params[:id]` y como ves en el error te está retornando el string de "acá va un id".

Te dejo un link para que te guies pero busca en internet como hacer test de request con id.

https://stackoverflow.com/questions/37008040/rails-passing-id-to-rspec-test

**Comment by aljara97** [comment]
Gracias, revisaré que onda :D
