### ISSUE TITLE
Problema con File Handling

### ISSUE THREAD

**Issue by vsantelicest** [IIC2143-2020-2/syllabus#18]
Hola! 
Para la tarea, a la hora de crear un nuevo archivo .txt donde ir anotando los resultados de los métodos pedidos no tengo ningún problema, per después más abajo en el código cuando trato de abrir nuevamente este archivo creado con el file.open en modo "a", este no me permite añadir más texto del proporcionado inicialmente cuando lo creé usando el modo "w". Por que podria ser que pase esto?

**Comment by jerosalazar** [comment]
Quizás pueda ser porque la vez que abres el archivo como write no lo estas cerrando. Debes cerrar el archivo explícitamente a menos que lo estes ocupando en un bloque `do` como:`File.open(...) do |f|`

**Comment by jerosalazar** [comment]
Puedes revisar [este link](https://stackoverflow.com/questions/4795447/rubys-file-open-and-the-need-for-f-close) si quieres leer un poco más

**Comment by vsantelicest** [comment]
Oka! Muchas gracias
