### ISSUE TITLE
Problemas con Rubocop

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2143-2020-2/syllabus#181]
Hola! Nos salen los siguientes problemas con Rubocop y no sabemos como arreglarlo :( 

<img width="561" alt="image" src="https://user-images.githubusercontent.com/42807519/95640718-762bd400-0a74-11eb-9fa3-fdabc93c39b9.png">

**Comment by daleal** [comment]
Hola! El problema es que su sistema operativo usa `CRLF` en vez de `LF` para los saltos de línea, y eso a rubocop no le gusta (en general es preferible trabajar con `LF`). Hay otras _issues_ en que se detalla la diferencia entre ambos saltos de línea. [Aquí te dejo una](https://github.com/IIC2143-2020-2/syllabus/issues/168). En cualquier caso, lo mejor que puedes hacer es configurar tu editor de texto para utilizar `LF` en vez de `CRLF`.

**Comment by tedroppelmann** [comment]
Hola! Pero como hago para borrar la ofensa en el rubocop??

**Comment by daleal** [comment]
Una opción es hacer que tu editor use `LF` en vez de `CRLF`. Así, al guardar cambiará automáticamente todos los `\r\n` a `\n`, y rubocop estará feliz. Otra opción es ignorar la ofensa en el `.rubocop.yml`, aunque ese tipo de ofensas en general es mejor resolverlas a ignorarlas.
