### ISSUE TITLE
Problema con git master

### ISSUE THREAD

**Issue by mjfontanet** [IIC2143-2020-2/syllabus#182]
Queremos hacer push en el master pero nos sale el siguiente error 
![Problema](https://user-images.githubusercontent.com/53796237/95643351-14279a80-0a85-11eb-9081-b6e3479b6008.PNG)

**Comment by jerosalazar** [comment]
Hola, esto se debe a que hay conflictos en los archivos mencionados (o sea hay cambios en master y develop que trabajan sobre las mismas lineas). Localmente puedes hacer merge a master, ir a los archivos mencionados y resolver los conflictos a mano antes de hacer push

**Comment by mjfontanet** [comment]
Es que como hay conflictos en archivos no deja hacer merge al master

**Comment by Gaonuk** [comment]
El merge deberias hacerlo localmente a traves de tu consola! Usando visual studio code puedes solucionar esos conflictos!  #174

**Comment by mjfontanet** [comment]
Yaa gracias!!
