### ISSUE TITLE
Precompiling assets failed

### ISSUE THREAD

**Issue by aljara97** [IIC2143-2020-2/syllabus#183]
He estado intentando hacer deploy a heroku, pero al hacer `git push heroku master` arroja el error 
```
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
```
He buscado en fuentes como [esta](https://stackoverflow.com/questions/19650621/heroku-upload-precompiling-assets-failed), pero no puedo tener claridad sobre cómo arreglar este error :c

**Comment by johnowenatala** [comment]
El error en si es bien sencillo: falla al compilar los assets.

Esto normalmente significa que tienes un error en tu CSS o en tu Javascript.

Mi consejo: revisa tu css y tu javascript y si crees que está todo bien, empieza a probar quitando archivos hasta encontrar el archivo con problemas, y luego puedes ir probando en qué mitad del archivo está, así hasta que aisles el problema.
