### ISSUE TITLE
Gemas permitidas y prohibidas

### ISSUE THREAD

**Issue by daleal** [IIC2143-2020-2/syllabus#185]
Hola! Les dejo las gemas permitidas a lo largo del proyecto. Cualquier duda de gema pregúntenla en un comentario de esta issue. Iré actualizando la lista a medida que se agreguen nuevas gemas.

## Gemas permitidas

- `devise`
- `cancan`
- `rolify`
- `will_paginate`
- `faker`
- `rails-i18n`
- `devise-i18n`
- `rspec-rails`
- `rails-controller-testing`
- `faker`
- `factory_bot_rails`
- `annotate`
- `awesome_print`
- `simplecov`
- `omniauth-google-oauth2`
- `activeadmin`
- `jquery-ui-rails`
- `geocoder`
- `cloudinary`
- `bulmajs-rails`
- `commontator`
- `excon`
- `chartkick`

## Gemas prohibidas

- `jumpstart`

**Comment by benjavicente** [comment]
Hola! en esta lista se van a incluir gemas de utilidad para el desarrollo (como [`solargraph`](https://github.com/castwide/solargraph)), las gemas obligatorias (`rubocop`, `rspec`, `simplecov`) o gemas equivalentes (como `webdrivers` y [`chromedriver-helper`](https://github.com/flavorjones/chromedriver-helper), `faker` y [`ffaker`](https://github.com/ffaker/ffaker))?

Tambíen creo que falta `factory_bot`, que se mostró en clases de rails mvc y rspec.

**Comment by johnowenatala** [comment]
Yo recomendaría incluir estas gemas en la lista:

```
  # Localizacion de rails (para otros idiomas no-inglés)
  gem 'rails-i18n'

  # Localizacion de devise (para otros idiomas no-inglés)
  gem 'devise-i18n'

  # testing
  gem 'rspec-rails'
  gem 'rails-controller-testing'

  # generador de cosas
  gem 'faker'

  # fabricas. Va tambien en dev para que al generar modelos se generen las fabricas
  gem 'factory_bot_rails'

  # esta gema hace que los modelos tengan un comentario con sus campos
  gem 'annotate'

  # esta gema mejora la experiencia en consola
  gem 'awesome_print'
  # para ruby 2.7:
  # gem 'awesome_print', git: 'https://github.com/akshaymohite/awesome_print', branch: 'ruby-2-7-0-warnings-fix'

  # estadisticas de testing
  gem 'simplecov', require: false

  # Por si quieren hacer login con google
  gem 'omniauth-google-oauth2'
```

Por último, probablemente las gemas típicas de administración debieran estar prohibidas, como
* administrate
* activeadmin

**Comment by daleal** [comment]
Hola @benjavicente! La idea de esta _issue_ no es que sea una lista de todas las gemas que existen indicando si se permiten o no. Las gemas que se han mostrado en clases/ayudantías pueden ser usadas en el proyecto (a menos que se diga lo contrario al momento de usarse). La idea es que en esta issue se pregunte por gemas en específico utilizando un formato similar al siguiente:

```
Hola! Puedo usar la gema ${gema} para poder ${objetivo}?
```

De esta manera, debido a que todos deben resolver un problema similar, al momento de querer usar una gema "distinta" a las gemas "base", pueden ver en la lista de gemas que ya se han preguntado. En caso de no estar ahí, pueden preguntar con un comentario en la _issue_ y les responderé si se puede/no se puede, y la agregaré a la lista con las demás.

**Comment by Etienne99** [comment]
Hola! ¿Puedo usar la gema 'jquery-ui-rails' para poner una interfaz gráfica de calendario cuando el usuario selecciona una fecha límite para su carrete? Para aclarar la idea adjunto una imagen de lo que quiero hacer:
![calendario](https://user-images.githubusercontent.com/42183961/97194754-475a7100-1789-11eb-94f7-6dd5efd8b927.png)

**Comment by daleal** [comment]
@Etienne99 si puedes usarla!

**Comment by Gabowo** [comment]
Hola! Puedo usar la gema Geocoder para poder convertir las ubicaciones de perfiles o carretes en latitud y longitud, pudiendo asi mostrar la ubicacion en un mapa?

**Comment by daleal** [comment]
@Gabowo si puedes!

**Comment by benjavicente** [comment]
Hola! Se puede usar la gema [`cloudinary`](https://github.com/cloudinary/cloudinary_gem) para añadir facilmente almacenamiento en la nube y [`bulmajs-rails`](https://github.com/dhmgroup/bulmajs-rails) para no tener que preocuparse de JS en algunos componentes de Bulma?

**Comment by daleal** [comment]
@benjavicente ambas gemas están permitidas!

**Comment by tocococa** [comment]
Hola! Puedo usar la gema `commontator` para poder tener una sección de comentarios?

**Comment by daleal** [comment]
@tocococa si puedes usar esa gema!

**Comment by mpbosnic** [comment]
Hola! ¿Puedo usar las gemas `excon` para comunicarme con una api?

**Comment by daleal** [comment]
@mpbosnic esa gema está permitida!

**Comment by nvenegasu** [comment]
Hola! Puedo usar la gema #{open_street_map} para poder comunicarme con una api?

**Comment by mpbosnic** [comment]
Hola! ¿Puedo usar la gema `chartkick` para hacer un gráfico?

**Comment by daleal** [comment]
@mpbosnic si puedes!
