### ISSUE TITLE
Devise problema cambiar imagen de usuario

### ISSUE THREAD

**Issue by Francisco5674** [IIC2143-2020-2/syllabus#187]
Hola!
Tengo una duda con las imágenes de usuario, resulta que estoy usando la gema 'Active_storage' para configurar esta funcionalidad de la aplicación, y todo bien, ya lo logre, tengo una imagen de default para todos los usuarios, el usuario puede cambiar su imagen de perfil si lo prefiere, etc, etc, pero el problema esta en que al momento de editar el perfil y cambiar la imagen de default que aplica la pagina o cualquier otra imagen antigua que tenga el usuario, esta se cambia aunque el usuario no confirme los cambios con la contraseña, es decir, cuando el usuario quiere cambiar su nombre, comuna, edad o lo que sea, todos estos cambios necesitan de la contraseña del usuario para ser efectivamente cambiados, todos excepto la imagen que se cambia independientemente de que el usuario confirme con la contra o no lo haga, eso me molesta mucho, acaso hay alguna manera de que la imagen pase por el filtro de la contraseña, es decir, es posible configurar que requiere ser confirmado con la contraseña en devise y que no?

**Comment by meretamal** [comment]
Hola 😁 

Podrías explicarme cómo estás subiendo las fotos (estás usando `has_one_attached`?, en qué vista estás subiendo la foto?, etc)?

**Comment by Francisco5674** [comment]
Justamente estoy usando lo que tu dices, '''has one attached''' en la vista "edit" de "registration" puedes personalizar la imagen de usuario, en "new" no hay nada porque se pone una por defecto

**Comment by Francisco5674** [comment]
Aqui esta el modelo:
![image](https://user-images.githubusercontent.com/61996440/96367209-c1a04b00-1122-11eb-9e19-410bc56b88e0.png)
Esta es la vista de edit:
![image](https://user-images.githubusercontent.com/61996440/96367230-e268a080-1122-11eb-8a9f-1fea56483af8.png)

**Comment by meretamal** [comment]
Y cuando no haces ni un cambio y haces _submit_, no te pide la contraseña?

**Comment by TeresitaS** [comment]
Hola! Me podrías decir de donde te guiaste para implementar el 'Active Storage'? Estaba usando la documentación de rails guides pero no logro que se guarden los cambios ni mostrar la imagen!

**Comment by Francisco5674** [comment]
Ya solucione el problema, Muchas gracias por tu atención @meretamal, en cuanto a tu pregunta @TeresitaS el video que adjunto es la luz, fue el que me utilice para esto.

Videito: https://gorails.com/episodes/user-avatars-with-rails-active-storage
