### ISSUE TITLE
Problema al implementar Cloudinary

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#188]
Hola!Tengo un problema , al intentar agregar una imagen usando Activestorage y usando cloudinary para su almacenamiento me paso el siguiente error:
![Captura de pantalla (183)](https://user-images.githubusercontent.com/62029138/96607462-c43fa380-12ce-11eb-8fe1-5ec994ded496.png)

![Captura de pantalla (181)](https://user-images.githubusercontent.com/62029138/96606956-395ea900-12ce-11eb-96a9-a40229678e0c.png)

Para implementar cloudinary use la siguiente guía https://cloudinary.com/documentation/rails_activestorage.
Mi código se ve así:
![Captura de pantalla (178)](https://user-images.githubusercontent.com/62029138/96603904-dfa8af80-12ca-11eb-8a62-4f104bc5d160.png)
![Captura de pantalla (179)](https://user-images.githubusercontent.com/62029138/96605218-4c707980-12cc-11eb-8799-e14d5dfb7124.png)
![Captura de pantalla (180)](https://user-images.githubusercontent.com/62029138/96606986-44193e00-12ce-11eb-9fb9-9f22b84d440f.png)
![Captura de pantalla (182)](https://user-images.githubusercontent.com/62029138/96607174-77f46380-12ce-11eb-852b-2a5605286ef5.png)

**Comment by daleal** [comment]
Hola! Ejecutaste estos comandos?

```sh
rails active_storage:install
rake db:migrate
```

**Comment by RonaldoSosa** [comment]
Si los ejecute, y además me di cuenta de que en config/environments/production.rb tenía config.active_storage.service = :cloudinary y al cambiarlo a config.active_storage.service = :local me dejo de aparecer el error mencionado sin embargo ahora me aparece este error que me indica que no se puede cargar el cloudinary
![Captura de pantalla (385)](https://user-images.githubusercontent.com/62029138/97013389-62c24380-151f-11eb-9e1e-4d914b0f1864.png)
Además cuando ejecute rails active_storage:install y rake db:migrate
![Captura de pantalla (386)](https://user-images.githubusercontent.com/62029138/97013565-90a78800-151f-11eb-8cdd-98164b856d83.png)
![Captura de pantalla (384)](https://user-images.githubusercontent.com/62029138/97013732-c482ad80-151f-11eb-992b-808bb16b0505.png)

**Comment by johnowenatala** [comment]
Efectivamente en producción debes tenerlo con cludinary como servicio (con :local va a intentar guardar los archivos localmente y eso no te funcionará en Heroku).

Te recomiendo que revises esto:

https://stackoverflow.com/questions/50792581/rails-active-storage-unable-to-autoload-constant-activestorageblobanalyzable

**Comment by RonaldoSosa** [comment]
Yaaa muchas gracias!!!
