### ISSUE TITLE
Problemas con 'Active Storage'

### ISSUE THREAD

**Issue by TeresitaS** [IIC2143-2020-2/syllabus#189]
Hola! Estoy tratando de implementar 'Active Storage' y logro que me pida el archivo. Pero al tratar de guardar los cambios me tira error y no logro mostrar la imagen. Sería buenísimo saber como arreglarlo y como funciona el ":avatar", si es que es un atributo del modelo o un modelo por si solo (con métodos por si solo).

**Comment by meretamal** [comment]
Hola 😁 

¿Qué error te está levantando?

**Comment by TeresitaS** [comment]
ActiveModel::UnknownAttributeError (unknown attribute 'avatar' for User.):

**Comment by meretamal** [comment]
A tu modelo User le agregaste `has_one_attached :avatar`?

**Comment by TeresitaS** [comment]
Si!

**Comment by johnowenatala** [comment]
Puedes pegar qué hay en UsersController línea 19?

**Comment by TeresitaS** [comment]
Logré encontrar el error, estábamos usando un View que no era de devise.
