### ISSUE TITLE
Añadir Devise al modelo de usuario

### ISSUE THREAD

**Issue by ibaeza1** [IIC2143-2020-2/syllabus#190]
Hola!
Cree un modelo de usuario con su crud respectivo y despues intente añadirle devise, pero ya no me esta tomando nada que no sea el mail en el form. 
Inicia sesion perfecto con la contraseña y todo. Tambien funciona editar y eliminar, pero cuando creo un nuevo usuario en usuario_registration_path no me toma nada que no sea el email.
Por que pasa esto?
Gracias!

**Comment by meretamal** [comment]
Hola 😁 

Devise solo va a "aceptar" _email_ y _password_.

Para poder asignarle más atributos debes generar los controladores de _User_ y modificar `configure_sign_up_params`. En la ayudantía y en la documentación de [devise](https://github.com/heartcombo/devise) se enseña cómo hacerlo.

**Comment by ibaeza1** [comment]
Gracias!
