### ISSUE TITLE
uninitialized constant Users

### ISSUE THREAD

**Issue by IvaniaArias** [IIC2143-2020-2/syllabus#192]
Holaa!
Estoy tratando de crear los users con devise, segui paso a paso la ayudantía y cuando me meto al mismo link que ella me sale esto, que puede ser? :( 

![Captura de pantalla (737)](https://user-images.githubusercontent.com/61998881/96962411-1b1ac800-14dd-11eb-888c-af3bbca998de.png)

**Comment by jerosalazar** [comment]
Hola! corriste la migración que te crea los usuarios?

**Comment by IvaniaArias** [comment]
Si :( hice lo mismo de la ayudantía

**Comment by johnowenatala** [comment]
Probablemente estás poniendo Users, pero el modelo(la clase) es User (sin la s al final). Error que me es muy familiar 😅

**Comment by IvaniaArias** [comment]
@johnowenatala Lo tengo como user :( Pero tambien creo que va por ahi 
En controllers tengo una carpeta user
En models un archivo user
Y en vistas la carpeta es users (pero las demas tambien estan en plural) 
y en routes.rb agregé 

![Captura de pantalla (738)](https://user-images.githubusercontent.com/61998881/97044903-33c1c700-154b-11eb-9040-b0e5d57e9146.png)


Puede que haya alguna discordancia ? :(

**Comment by johnowenatala** [comment]
El archivo de rutas lo veo bien. Pero me suena que en algún lado estás llamando al modelo como Users - eso dice el error.
