### ISSUE TITLE
uninitialized constant ComentarioServicesController

### ISSUE THREAD

**Issue by ibaeza1** [IIC2143-2020-2/syllabus#193]
Hola!
Estoy tratando de eliminar un comentario y me sale el error "uninitialized constant ComentarioServicesController".
El comentario tiene dos foregin keys, una a usuario y una a servicio. Creo que puede que sea por eso.
En routes.rb tengo 
resources servicios do
   resources comentarios_services
end
y eso me soluciono lo de editar pero no eliminar.
Que puede ser? Busque en google por todas partes y no decia nada :(
Gracias!

**Comment by jerosalazar** [comment]
Hola! Quizás es un error en el nombre del controlador. Comentaste que en tu ruta tienes definido comentarios_services (plural) y que el error hace referencia a ComentarioServices (singular)
