### ISSUE TITLE
Problema con el puerto para la conexion mediante postresql

### ISSUE THREAD

**Issue by Sadhguy** [IIC2143-2020-2/syllabus#194]
Holaa, me salé este problema al correr "rails db:create"

Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5433?
Couldn't create 'dccarrete_development' database. Please check your configuration.
rails aborted!
![image](https://user-images.githubusercontent.com/62361849/97093771-3ee92580-1625-11eb-848b-84fc9c3f006e.png)

**Comment by jerosalazar** [comment]
Hola! estas seguro que el servicio de postgres está corriendo?

**Comment by Sadhguy** [comment]
Segurísimo, corri sudo service postresql start y me corrio correctamente

**Comment by Sadhguy** [comment]
![image](https://user-images.githubusercontent.com/62361849/97112338-7f4ab100-16c2-11eb-850a-741c104b7c7b.png)
.-.

**Comment by meretamal** [comment]
Hola 😁 

Si te fijas, tu servicio de postgres está corriendo en el puerto 5432 y en tu app está tratando de acceder al puerto 5433.

**Comment by Sadhguy** [comment]
Es que he cambiado muchas veces eso en el postresql.conf pero aun no logra acceder correctamente a la db:(

**Comment by meretamal** [comment]
Luego de modificar ese archivo, intentaste reiniciar tu servicio de portgres?

**Comment by Sadhguy** [comment]
sep, lo reinicie desde services usando win+r

**Comment by Sadhguy** [comment]
Me podría ayudar alguien hoy en la tarde un rato con pantalla compartida por favor? No puedo aportar al código ya que no puedo desplegar bien la aplicación en mi computador :(

**Comment by meretamal** [comment]
Háblame por telegram (@meretamal) 😉
