### ISSUE TITLE
Asociaciones Error ActiveRecord::RecordNotFound (Couldn't find User without an ID)

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#195]
Hola!Tengo un problema al implementar las asociaciones , lo que pasa es que cree un modelo User , con devise, y otro modelo llamado Service estos tienen una relación de 1 a N , al rellenar los modelos con has_many :services y belongs_to :user y modificar el controlador de service , cuando intento crear un nuevo servicio me tira el error ActiveRecord::RecordNotFound (Couldn't find User without an ID) , para hacer esto me guíe de https://guides.rubyonrails.org/getting_started.html , por lo que revise en línea este error se debe a que el archivo de las rutas le faltan elementos pero este no vendría siendo el caso ya que mi archivo routes tiene:
![Captura de pantalla (399)](https://user-images.githubusercontent.com/62029138/97097647-ce0c3280-1651-11eb-869a-16d27e34617c.png)
También vi que se puede deber a que mi base de datos no este sincronizada o que le falta el parametro user_id en mi tabla de service pero : 
![Captura de pantalla (403)](https://user-images.githubusercontent.com/62029138/97097681-3bb85e80-1652-11eb-8e16-09aca68f2a6c.png)
![Captura de pantalla (402)](https://user-images.githubusercontent.com/62029138/97097683-3f4be580-1652-11eb-9374-20235f1b30c1.png)
O también debido a que mi base de datos no este sincronizada pero luego de hacer un rails db:drop , rails db:create y un rails db:migrate el error persiste , además adjunto una foto de como luce el controlador de services:
![Captura de pantalla (404)](https://user-images.githubusercontent.com/62029138/97097708-99e54180-1652-11eb-8c3e-e5bf006660dc.png)
![Captura de pantalla (405)](https://user-images.githubusercontent.com/62029138/97097713-aff30200-1652-11eb-864a-87c060468e1c.png)
Señalo que el error también sigue cuando cambio User.find(params[:user_id]) por User.find(params[:id])

**Comment by jerosalazar** [comment]
Hola! Cuando haces submit del formulario para crear un servicio, dentro del terminal donde dejaste corriendo `rails s` deberías poder ver los parámetros que se envían. Revisa esos parámetros y asegúrate de que exista un `user_id` y que sea válido

**Comment by RonaldoSosa** [comment]
Hola!Revise la terminal cuando hago esto y sigo sin entender porque ocurre ya que el usuario con el que lo hago existe y es valido, aquí una imagen del terminal:
![Captura de pantalla (406)](https://user-images.githubusercontent.com/62029138/97116276-da889d80-16da-11eb-9b0b-cc8f036c96b4.png)
Y con esto supongo que se demuestra que el usuario es válido
![Captura de pantalla (407)](https://user-images.githubusercontent.com/62029138/97116309-fb50f300-16da-11eb-8068-44f07ff668e3.png)
No se si también tiene que ver pero aquí va una imagen del formulario y la ruta que se usa
![Captura de pantalla (408)](https://user-images.githubusercontent.com/62029138/97116349-36532680-16db-11eb-9093-bf5ec7e87137.png)

**Comment by jerosalazar** [comment]
Si te fijas, en los parámetros no está definido nunca el user_id (aquí me refiero a los params del último bloque donde dice POST a /services. Esto pasa porque no tienes en el form un field que defina el valor de user_id. Para esto puedes hacer un hidden field (por ejemplo) donde defines el id del usuario que va a crear el servicio o (esta es la opción más correcta), ya que tienes un usuario loggeado con devise simplemente puedes usar el helper `current_user` para obtener el usuario actual. Así puedes quitar la línea de tu controlador donde defines `@user = User.find(...)` y simplemente crear el servicio como `current_user.services.create(...)`

**Comment by RonaldoSosa** [comment]
Ya hice eso y además agregué en el controlador un before_action :authenticate_user! y en los parametros agregué
![Captura de pantalla (412)](https://user-images.githubusercontent.com/62029138/97117689-24c24c80-16e4-11eb-8c7b-9636a2b190ed.png)
Y mi formulario ahora se ve así
![Captura de pantalla (413)](https://user-images.githubusercontent.com/62029138/97117694-39064980-16e4-11eb-92ef-7b9ec93733b7.png)
Sin embargo ahora me tira el error: ActiveModel::UnknownAttributeError (unknown attribute 'user_id' for Service.):
![Captura de pantalla (414)](https://user-images.githubusercontent.com/62029138/97117731-72d75000-16e4-11eb-9a11-868a38f06674.png)

**Comment by jerosalazar** [comment]
Ya. Veo un par de errores. En primer lugar current_user no lleva @ al inicio, debes usarlo así no más. Lo otro es que veo que tu referencia a usuarios está en plural. Es decir tienes la migración como `references :services, :users` cuando debería ser user en singular. Esto hace que en tu schema tengas el atributo `users_id` y no en singular. Te recomiendo que bajes esa migración (y cualquier otra que tengas con references en plural), la edites y la corras de nuevo

**Comment by RonaldoSosa** [comment]
Con eso ya me funciona!!!Muchas gracias!!Una última consulta todo esto lo trabaje en una rama , cuando quiera mandarlo a la rama develop o master , es decir , al hacer merge debería hacer también lo de bajar las migraciones , editarlas y subirlas de nuevo?
