### ISSUE TITLE
Error al correr rails db:migrate

### ISSUE THREAD

**Issue by fbpesenti** [IIC2143-2020-2/syllabus#197]
Cuando intento hacer rails db:migrate me tira este error. Revise el estar corriendo el `sudo service postgresql start` y que el puerto fuera el correcto, por lo que vi que podría ser el problema. Pero sigue sin funcionar.

![image](https://user-images.githubusercontent.com/48263110/97252343-853ab200-17e8-11eb-9718-172996161d07.png)

De antemano muchas gracias

**Comment by benjavicente** [comment]
Hola! no soy ayudante, pero [tenía un problema similar](https://github.com/IIC2143-2020-2/syllabus/issues/132). Eso **no son errores de tu programa**. Es un problema que hay en las gemas que usa rails cuando la versión de ruby es `2.7`.

Antes de ejecutar `db:migrate`, ejecuta:
```bash
export RUBYOPT="W0"
```
Puedes añadir eso al archivo `.bashrc` que está en la carpeta de usuario (`~` o `/home/fbpesenti`) para no tener que hacerlo cada vez que se abre una nueva consola.

**Comment by fbpesenti** [comment]
Muchas Gracias ahora me funciona bien :)
