### ISSUE TITLE
Error iniciando la app

### ISSUE THREAD

**Issue by Baelfire18** [IIC2143-2020-2/syllabus#198]
Hola me falla con esto al iniciar la app y no se el pq
![image](https://user-images.githubusercontent.com/50716449/97378905-45380580-18a2-11eb-97e1-a9051efce144.png)

**Comment by daleal** [comment]
Hola! Mi apuesta es a que ya tienes `postgres` corriendo desde Windows. Recuerda que Windows y WSL comparten los puertos, por lo que si tienes `postgres` corriendo en el puerto `5432` en Windows, al intentar iniciar `postgres` desde WSL, el puerto `5432` se verá ocupado y fallará.

**Comment by Baelfire18** [comment]
@daleal asi es me descargue postgres, para arregarlo solo cambio el puerto en el database.yml?

**Comment by Baelfire18** [comment]
No se como arreglarlo, eso si se supone el el puerto esta vacio y ademas acabo de reiniciar el PC (no deberia estar correindo el psql de windows o no?)
![image](https://user-images.githubusercontent.com/50716449/97460314-67ba3500-191b-11eb-8dba-0fdb0481aeb1.png)

**Comment by johnowenatala** [comment]
En el caso de Windows, puede que psql se haya instalado como servicio, así que igual puede estar corriendo.
