### ISSUE TITLE
error en consola de wsl

### ISSUE THREAD

**Issue by mgbriones** [IIC2143-2020-2/syllabus#199]
Hola, me aparece la siguiente advertencia cuando utilizo rails:
`/home/mgbriones/.rvm/rubies/ruby-2.6.5/bin/ruby: warning: shebang line ending with \r may cause problems`

Que es, y como podria areglarlo??

**Comment by Gaonuk** [comment]
Hola!

Ese es un problema que pasa cuando editas tu archivo en windows y lo ejecutas en la wsl que seria Linux, entonces tu archivo se guarda con una linea de windows que Linux no reconoce bien

Para solucionarlo puedes usar el siguiente comando:
```git
git config --global core.autocrlf true
```

Si no te funciona aqui hay mas soluciones:
https://stackoverflow.com/questions/54286602/how-to-fix-shebang-warning-in-ruby
