### ISSUE TITLE
Default value en hash

### ISSUE THREAD

**Issue by Witomi** [IIC2143-2020-2/syllabus#20]
Hola!

Quería preguntar si es que existe alguna manera en ruby de crear un hash que tenga como valor predeterminado una lista, tal que:

a={}
a["nueva_llave"].append(3,6)
tal que
a["nueva_llave"] => [3,6]

Gracias

**Comment by meretamal** [comment]
Hola 😁 !!

Te dejo un link de [stackoverflow](https://stackoverflow.com/questions/9108619/if-key-does-not-exist-create-default-value) que te podría servir.

Hay dos soluciones, dependiendo de lo que quieras lograr.

**Comment by Witomi** [comment]
Muchas gracias!! Era lo que necesitaba jajaja
