### ISSUE TITLE
Problema deploy heroku

### ISSUE THREAD

**Issue by bpardobravo** [IIC2143-2020-2/syllabus#200]
Hola, al igual que en la issue #141 , me sale estoy la hacer el deploy a heroku.
![image](https://user-images.githubusercontent.com/48322933/97521791-10e54780-197d-11eb-9a0f-c5294ebad67d.png)
Y al igual que ahí, al hacer <buildpacks:set https://github.com/bundler/heroku-buildpack-bundler2> me deja hacer deploy, pero me sale esto:
![image](https://user-images.githubusercontent.com/48322933/97522141-d16b2b00-197d-11eb-8205-0e7e201c644b.png)
¿Cómo sigo desde ahí? He buscado en internet el mismo problema, pero logro dar con una solución que me sirva.
PD. los logs:
![image](https://user-images.githubusercontent.com/48322933/97522524-b64ceb00-197e-11eb-8a1d-f24a192ee70d.png)

**Comment by Gaonuk** [comment]
Al hacer el deploy corriste las migraciones? ```bash heroku run rake db:migrate```

**Comment by benjavicente** [comment]
Hola! Lo último de los logs de Heroku debe ser [este problema](https://github.com/IIC2143-2020-2/syllabus/issues/133#issuecomment-690829861). Ver si cambiando la secuencia de término de línea a `LF` ( `\n`) en el directorio `bin` se soluciona el problema.

**Comment by bpardobravo** [comment]
> Hola! Lo último de los logs de Heroku debe ser [este problema](https://github.com/IIC2143-2020-2/syllabus/issues/133#issuecomment-690829861). Ver si cambiando la secuencia de término de línea a `LF` ( `\n`) en el directorio `bin` se soluciona el problema.

¿Te refieres a cambiar la secuencia de término de cada uno de los archivos en bin? ¿Cómo puedo lograr eso?
Estoy medio confundido además con el path que dan los logs "usr/bin/env", no sé donde está eso, o si es un path que debiese estar en el proyecto.

**Comment by benjavicente** [comment]
> Estoy medio confundido además con el path que dan los logs "usr/bin/env", no sé donde está eso, o si es un path que debiese estar en el proyecto.

Esa ruta es la que aparece en los [_shebangs_](https://es.wikipedia.org/wiki/Shebang) en los archivos que están en el directorio `bin`. Deberían verse como:

```bash
#!/usr/bin/env ruby
```

> ¿Te refieres a cambiar la secuencia de término de cada uno de los archivos en bin? ¿Cómo puedo lograr eso?

En VSCode hay un [botón en la parte de abajo a la derecha](https://stackoverflow.com/a/39532890). Deben haber extensiones para hacer eso automáticamente, pero yo no conozco ninguna ¯\\\_(ツ)\_/¯
