### ISSUE TITLE
Eliminar un Crud

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#202]
Hola. hay alguna manera de eliminar un CRUD permanente en la app ? o basta con eliminar los archivos? gracias.

**Comment by Gaonuk** [comment]
Hola! 
Puedes hacerlo elimando los archivos, pero para hacerlo de forma segura puedes utilizar los siguientes comandos
Ademas tienes que eliminar la tabla del modelo que quieres borrar

```bash
rails d model Model_name
rails d controller controller_name
```
