### ISSUE TITLE
Agregar nuevo atributo

### ISSUE THREAD

**Issue by eugeizquierdo** [IIC2143-2020-2/syllabus#203]
Hola! Cómo puedo agregar un nuevo atributo a un modelo? Quiero agregarle a "Carrete" el atributo fecha y no lo estoy logrando.

Muchas gracias.

**Comment by bvallejo1** [comment]
Hola yo lo hice siguiendo este foro:
https://stackoverflow.com/questions/39049434/ruby-on-rails-how-to-add-parameter-to-database-in-existing-model

**Comment by eugeizquierdo** [comment]
Buenísimo, gracias!!
