### ISSUE TITLE
Associations Ruby

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2143-2020-2/syllabus#204]
Ayer estuve el día entero tratando de crear las relaciones y en internet hay distintas formas de hacerlo las cuales no tuvieron sirivieron mucho entonces voy a compartir los pasos que tuve que realizar para que funcionara a rasgos generales y que ojalá le ahorre sus buenas horas (esto es para una relacion `A has many Bs through Cs` que es una relacion de dos modelos a traves de un tercer modelo intermediario. Doy un ejemplo de como hacer la relación de Califica que tiene un `belongs_to` User

- Primero hay que actualizar la tabla de la relación Califica para que tenga llaves foreaneas de ambos modelos, esto se puede hacer con una migración `$ rails generate migration AddUserRefToCalifica user:references` y luego de migrar se puede ver en la tabla de psql con `SELECT * FROM Calificas` que existe una columa de llave foranea de `user_id` (si crearon el modelo con los reference al principio no hay que hacer esto).

- Luego hay que obtener a traves del form el id que se necesita para crear la relacion de Califica, yo lo hice a traves de `<%= form.collection_select :user_id, User.all, :id, :name %>` que en el submit aprace el parametro `user_id => "1"`.

- Por último hay que permitir el nuevo parámetro en  `@califica_params = params.require(:califica).permit(:texto, :nota, :user_id)`

Ahora se puede usar en las vistas @califica.user y se tiene el objeto relacionado. Feliz si los ayudantes pueden comentar si esta es una formacorrecta de hacer relaciones porque no estoy 100% seguro.

**Comment by johnowenatala** [comment]
En lo personal yo abordo la creación de las relaciones así:

1. Crear los modelos pensando en las relaciones, ej rails g model User name:string address:references ...

2. Yo nunca llego y ejecuto las migraciones. Siempre las reviso, de manera de darle un tunning concreto (ej: ¿quiero que todos los campos acepten null? ¿qué campos debieran ser índices?). A veces, al hacer esto me doy cuenta de errores (ej: ¿por qué este campo "distancia" es de tipo string?)

3. Cuando quiero agregar relaciones a modelos ya existentes, creo una migración para agregar los campos necesarios (rails g migration add_address_relation_to_users) y la migración en si la escribo a mano, haciéndome cargo de cómo quiero que se haga la migración y cuando corresponda, la reversa (no siempre "def change" hace la pega y es necesario escribir un up y un down).

Por último, en cualquiera de los casos, voy a los modelos y escribo las relaciones.

```
class User
  belongs_to :address, optional: true, inverse_of: :users
...

class Address
  has_many :users, inverse_of: :address
```
