### ISSUE TITLE
Error al realizar consulta psql

### ISSUE THREAD

**Issue by vaperez5** [IIC2143-2020-2/syllabus#205]
Tuve el problema de la issue #87 también y lo logré solucionar, pero luego al momento de querer hacer consultas me aparece "ERROR:  permission denied for table users" para todas las tablas creadas. Ya traté utilizando el comando GRANT que lo vi como solución en internet y no funciona. Esto nos pasa a mi compañera y a mi, y mi otro compañero aún no puede ingresar a la bdd por lo que nadie tiene posibilidad de ver la bdd y su contenido jajaja, ojalá alguien sepa como solucionarlo, gracias!!
![image](https://user-images.githubusercontent.com/42751454/97714210-a0831700-1a9f-11eb-9ac6-14c35ac61ba7.png)

**Comment by Gaonuk** [comment]
Hola!

Una solucion es que se metan como usuario postgres y cambien el owner de la tabla

```sql
alter table <TABLE> owner to <USER>;
```

Aqui hay mas links con informacion al respecto
https://stackoverflow.com/questions/15520361/permission-denied-for-relation
https://stackoverflow.com/questions/57949912/postgres-roles-and-users-permission-denied-for-table

**Comment by vaperez5** [comment]
Muchas gracias pero aun no me funciona 😢 ya había visto la información de esos links y no nos había resultado. Me confunde un poco que cuando ingreso como usuario postgres y hago \dt no encuentra las tablas por lo que si trato de ejecutar algún comando me sale que no existe, y por otro lado cuando ingreso con psql DCCarretes_development me muestra las tablas con owner postgres pero no puedo ejecutar ningún comando por falta de permisos. Es como si existieran 2 usuarios postgres distintos.
![image](https://user-images.githubusercontent.com/42751454/97741485-8f4b0200-1ac1-11eb-806a-c28880e935e2.png)

**Comment by Gaonuk** [comment]
Prueba utilizar el siguiente comando para acceder a tu base de datos:

```bash
sudo -u postgres psql <nombre de tu base de datos>
```
