### ISSUE TITLE
Error consulta psql permission denied

### ISSUE THREAD

**Issue by vaperez5** [IIC2143-2020-2/syllabus#206]
Tuve el problema de la issue #87 también y lo logré solucionar, pero luego al momento de querer hacer consultas me aparece "ERROR:  permission denied for table users" para todas las tablas creadas. Ya traté utilizando el comando GRANT que lo vi como solución en internet y no funciona. Esto nos pasa a mi compañera y a mi, y mi otro compañero aún no puede ingresar a la bdd por lo que nadie tiene posibilidad de ver la bdd y su contenido jajaja, ojalá alguien sepa como solucionarlo, gracias!!
![image](https://user-images.githubusercontent.com/42751454/97714210-a0831700-1a9f-11eb-9ac6-14c35ac61ba7.png)

**Comment by Gaonuk** [comment]
#205
