### ISSUE TITLE
Duda botones

### ISSUE THREAD

**Issue by eugeizquierdo** [IIC2143-2020-2/syllabus#207]
Hola!! Con mi grupo terminamos el Sprint 2, pero luego de ponerle el diseño a la app nos pasó que hay botones (como el de log in y el para registrarse) que no funcionan al apretarlo una primera vez, sino que es necesario actualizar la página y ahí funciona.
Qué puede ser?

Muchas gracias.

**Comment by eugeizquierdo** [comment]
Podría ser por la clase de los botones? 

Pusimos así el de **log in**: 

<div class="box">
<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "box"}) do |f| %>
     ......

<div class="action">
    <%= f.submit "Log in", class: 'button' %>
  </div>
  </div>


Y el de **registro**:

<div class="box">
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: "box"}) do |f| %>
      ...

<div class="actions">
    <%= f.submit "Sign up", class: 'button' %>
  </div>
  </div>

Muchas gracias!

**Comment by daleal** [comment]
Hola! Puede ser que en su controlador, en la acción que maneja la creación/edición de la entidad no estén redirigiendo al final? Lo que sucede es que al apretar el botón lo que se hace es ejecutar la acción, pero eso no significa que la página cambie. Al final de la acción de creación de una entidad, deberías redirigir a una página donde se vea reflejada la creación de esa entidad (al `index` de dicha entidad, por ejemplo)
