### ISSUE TITLE
Error al crear entidades

### ISSUE THREAD

**Issue by JulioGalvez** [IIC2143-2020-2/syllabus#208]
No podemos crear entidades(carretes) desde una form, aunque se envían los parámetros, la entidad no se crea, el problema ocurre en el controlador en el método create

Controlador:

<img width="1548" alt="controlador carrete" src="https://user-images.githubusercontent.com/62029166/97761634-f9c16980-1ae4-11eb-9556-af1c4079b401.png">

Vista:

<img width="1548" alt="vista new" src="https://user-images.githubusercontent.com/62029166/97761650-03e36800-1ae5-11eb-886c-0195edae4545.png">

Consola con problema:

<img width="1548" alt="consola" src="https://user-images.githubusercontent.com/62029166/97761667-0d6cd000-1ae5-11eb-8f94-b320b3af1a41.png">

**Comment by meretamal** [comment]
Hola 😁 !!

Podrías mandarme el contenido de tu modelo `Carrete` y un listado de los atributos de tu tabla?

**Comment by JulioGalvez** [comment]
> Hola 😁 !!
> 
> Podrías mandarme el contenido de tu modelo `Carrete` y un listado de los atributos de tu tabla?

Te lo adjunto!
muchas gracias!


Modelo:


<img width="1548" alt="modelo carrete" src="https://user-images.githubusercontent.com/62029166/97762596-d3e99400-1ae7-11eb-9e1d-18c7c94ffbef.png">


Schema:


<img width="1548" alt="tabla carretes" src="https://user-images.githubusercontent.com/62029166/97762608-d946de80-1ae7-11eb-8ec9-18984dc1d583.png">

**Comment by Tomas-Ira** [comment]
Hola, tengo el mismo problema, lo pudieron solucionar? Supongo que en alguna parte hay que hacer la relación con el usuario y la comuna. Llevamos todo el día en esto, cualquier idea sirve.

**Comment by diegogarcia98** [comment]
Sii!! porfavor yo igual estoy en lo mismoo.

**Comment by JulioGalvez** [comment]
@meretamal Se ven las imágenes adjuntas??

pd: aun sigo con el mismo problema

**Comment by meretamal** [comment]
No se si pueda tener algo de relación con esto, pero ojo que tienes una asociación 1:n entre carrete - usuario y carrete - comuna.

Para esto no te basta solo con definir la asociación en rails, sino que también debe tener alguna representación en tu base de datos (para asociaciones 1:n, generalmente le vas a pasar una llave foránea a la entidad que le "pertenece a la otra", por ejemplo, a la tabla de carretes le agregas una columna `user_id` y `comuna_id`).

Te recomiendo ver la ayudantía de asociaciones y migraciones donde se enseña este tipo de asociación.
