### ISSUE TITLE
Servicio es una instancia de String

### ISSUE THREAD

**Issue by gonzaloconcha** [IIC2143-2020-2/syllabus#209]
Al tratar de crear un comentario le paso al atributo servicio una instancia de la clase Servicio, pero al momento de guardarlo en el controlador en create me aparece: (Service(#157000) expected, got "#<Service:0x00007fb70c1adcc0>" which is an instance of String(#5220)).

**Comment by meretamal** [comment]
Hola 😁 !!

Si es que aún no lo solucionas, puedes mandar el contenido del `form` y del método `create`?

**Comment by gonzaloconcha** [comment]
El controlador:
![image](https://user-images.githubusercontent.com/53947841/97788951-87f82700-1b9b-11eb-9056-22565fdea5a1.png)

El form:
![image](https://user-images.githubusercontent.com/53947841/97788961-a0684180-1b9b-11eb-91d2-d6953c9bd018.png)

**Comment by meretamal** [comment]
Y el atributo `service` de tu tabla de comentarios representa el id del servicio al cual le pertenece?
