### ISSUE TITLE
[Tarea] Consideraciones de errores de formato

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2143-2020-2/syllabus#21]
Hola!
Me pregunto si puedo asumir que los archivos .csv **siempre** vendrán con el formato correcto, por ejemplo el número fijo de columnas, el *header* siempre en la fila 0, y las notas siempre en formato *float*, exceptuando la nota **P** del alumno (que por lo que vi, no puede ocurrir en *Grupos*), o incluso datos nulos/faltantes.
Lo anterior va para ver si utilizar bloques de captura de excepciones tipo **try/except** o **SIEMPRE** podré convertir *strings* a *float* o *int* de manera directa.

**Comment by meretamal** [comment]
Hola 😁 !!

Puedes asumir que los archivos siempre vendrán en el formato que se indica en el enunciado

**Comment by Christian-Klempau** [comment]
Genial, gracias! :)

**Comment by Camila-sty** [comment]
Si un alumno tiene nota "p" de examen, ésta "p" va a estar en mayúscula o minúscula?
