### ISSUE TITLE
Agregar instancia a modelo según relación **has_and_belongs_to_many**

### ISSUE THREAD

**Issue by bvasquezm** [IIC2143-2020-2/syllabus#210]
Hola!

Con mi grupo estamos teniendo el problema de no poder agregar o "asociar" un objeto con el cual se relaciona según **has_many** o **has_and_belongs_to_many**. Es decir, a diferencia de un objeto de relación 1-1, no logramos "appendear" un objeto según su id para cuando se debiese tener muchos de esos objetos en una relación n-n. Ejemplo:
```ruby
class Persona < ApplicationRecord
  has_and_belongs_to_many :ramos
end

class Ramo < ApplicationRecord
  has_and_belongs_to_many :personas
end

## Dentro del controlador, recibo varios id_ramo (Distintas opciones) ##

def create
   @persona_params = params.require(:persona).permit(:nombre_persona, :id_ramo_1, :id_ramo_2)
   @persona= Persona.create(@persona_params) # Esto entiendo que no crearía bien los ramos
   @persona = Persona.create(@persona_params.merge(ramos_ids: [:id_ramo_1, :id_ramo_2])) # Esto podría servir?
   ## código donde busco los ramos con id_ramo_1 y id_ramo_2. Genera @ramo_1 y @ramo_2##
   @persona = Persona.create(@persona_params.merge(ramos: [@ramo_1, @ramo_2])) # Pasar instancias?
   @persona.ramos << @ramo_1, @ramo_2 # Opción 4?
end
```
Como decía, para el caso de 1-1 es muy clara la forma de asociar, pero para casos como este creo que me confunde cuál sería el formato correcto para proceder 😕. Gracias de antemano!

**Comment by meretamal** [comment]
Hola 😁 , lo que podrías intentar hacer  es crear a la `@persona` con su nombre, luego encontrar los ramos a través de los dos ids que tienes y por último realizar la opción 4.
