### ISSUE TITLE
Asociaciones Error Couldn't find Service with 'id'=1 [WHERE "services"."user_id" = $1]

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#211]
Hola!Tengo un problema respecto al tema de asociaciones lo que pasa es que, tengo tres modelos los cuales son user,creado con devise, service y comment los cuales no fueron creados con devise, de los cuales entre user y service tienen una relacion de 1-N y lo mismo para user y comment, y service y comment ; agregué las asociaciones dentro de los modelos correspondientes e  intente crear un formulario dentro de la vista show del modelo service para agregar un comentario , me base en el ejemplo visto en https://guides.rubyonrails.org/getting_started.html , sin embargo al hacer esto me arroja el siguiente error:

![Captura de pantalla (465)](https://user-images.githubusercontent.com/62029138/97769429-bf1df800-1b09-11eb-9c5a-bee3b2d5fe82.png)

Y en la consola se ve así

![Captura de pantalla (456)](https://user-images.githubusercontent.com/62029138/97769442-e379d480-1b09-11eb-87dc-6e37620645bc.png)

Aqui adjunto una imagen del formulario para comment, su controlador y sus columnas:

![Captura de pantalla (457)](https://user-images.githubusercontent.com/62029138/97769559-c85b9480-1b0a-11eb-904c-b45a017ae0bb.png)
![Captura de pantalla (466)](https://user-images.githubusercontent.com/62029138/97769591-f345e880-1b0a-11eb-944b-bd3422039834.png)
![Captura de pantalla (467)](https://user-images.githubusercontent.com/62029138/97769605-1a041f00-1b0b-11eb-89be-603f2fec4ef8.png)
![Captura de pantalla (468)](https://user-images.githubusercontent.com/62029138/97769613-33a56680-1b0b-11eb-9805-931adef04759.png)

Para estar seguro de si los argumentos ingresados eran suficientes para crear el comentario lo intente hacer desde la consola, con el comando rails console, y logré crear un comentario desde ahí:

![Captura de pantalla (464)](https://user-images.githubusercontent.com/62029138/97769514-6bf87500-1b0a-11eb-8a29-33b2a1e4f79c.png)
Por lo cual no se exactamente donde esta el problema que provoca este error.

**Comment by meretamal** [comment]
Hola 😁 !!

En ves que ejecutar:
```ruby
@service = current_user.services.find(params[:service_id])
```
intenta con:
```ruby
@service = Service.find(params[:service_id])
```

**Comment by RonaldoSosa** [comment]
Funcionó!Muchas gracias!!! Pero me quedo la duda cuál es la diferencia entre:  
@service = current_user.services.find(params[:service_id])
y 
@service = Service.find(params[:service_id])?

**Comment by meretamal** [comment]
Cuando tú corres `current_user.services`, si es que tienes alguna asociación entre estos modelos, rails se encargará de buscar a todos los servicios que tengan `user_id` igual al `id` del `current_user`. Al agregar `.find`, haces que se busque, no entre todos los servicios, si no que entre los servicios asociados al usuario, lo cual te levantaba un error, ya que no encontraba ni uno con id=1.

Al poner `Service.find` haces que se busque el servicios con ese `id` entre todos los servicios existentes.

**Comment by RonaldoSosa** [comment]
Yaaa me quedo claro!!!!Gracias de nuevo!!!!
