### ISSUE TITLE
problema de paths

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2143-2020-2/syllabus#212]
Hola, tengo un problema,
tengo una vista en "carretes/contratar_servicios"
pero cuando trato de accederla con un get me lleva a
a la función show (la función show tiene ruta carretes/:id)
y piensa que el :id es igual a "contratar_servicios"
¿porque rails puede tener esta confusión?
(En las rutas puse "get 'carretes/contratar_servicios', to: 'carretes#contratar_servicios', as: 'contratar_servicios'"
y tambipen probé simplemente con 
"get 'carretes/contratar_servicios',  as: 'contratar_servicios'", por aún así se confunde)

**Comment by meretamal** [comment]
Hola, es posible que en tus rutas tengas definido "carretes/:id" antes que "carretes/contratar_servicios", por lo que, cuando haces el _request_ que mencionas, es probable que rails utilice el `show`, ya que es la primera ruta con la que hace _match_.

Si defines "carretes/contratar_servicios" primero, no deberías tener problemas.

Dime cómo te va 😉
