### ISSUE TITLE
atributos a devise

### ISSUE THREAD

**Issue by mjfontanet** [IIC2143-2020-2/syllabus#213]
Hola!! Quería agregar atributos a cruds que hicimos con devise, pero al hacerlo manual no funciona y no encontramos otra forma de hacerlo

**Comment by meretamal** [comment]
Hola 😁 !!

Cuando creas a tus usuarios con `devise`, no basta con agregar nuevos atributos con una migración y luego agregar los campos correspondientes en el formulario, sino que también debes "decirle" a `devise` que quieres utilizarlos.

Para esto debes generar los controladores y configurar los `permited_params` (en la ayudantía se enseñó cómo hacerlo).

Si es que ya hiciste esto y no te funciona, por favor guíame en torno a los pasos que seguiste para entender bien qué puede estar pasando 😉

**Comment by mjfontanet** [comment]
Hice una migración AddCommuneToUsers
![image](https://user-images.githubusercontent.com/53796237/97815415-92362600-1c6c-11eb-96bf-a020e319c708.png)
Luego arreglé en En app/controller users registrations_controller.rb lo siguiente:
![image](https://user-images.githubusercontent.com/53796237/97815451-e214ed00-1c6c-11eb-8afb-8bb623291c04.png)
Pero cuando en el form de registrations new hago lo siguiente 
![image](https://user-images.githubusercontent.com/53796237/97815485-286a4c00-1c6d-11eb-92fc-f0e55ddd078f.png)
Me tira el siguiente error
![image](https://user-images.githubusercontent.com/53796237/97815496-3ddf7600-1c6d-11eb-86b3-7dc161add9d5.png)

**Comment by meretamal** [comment]
Y en **registrations_controller.rb** descomentaste los `before_action` que hay arriba?
