### ISSUE TITLE
No puedo hacer deploy a Heroku

### ISSUE THREAD

**Issue by amparostevens** [IIC2143-2020-2/syllabus#216]
Hola! Me sale el siguiente error:
![Captura](https://user-images.githubusercontent.com/53883653/97806145-e9ba9e80-1c38-11eb-968d-eb805bb08363.PNG)

Intenté hacer lo que sale [aquí](https://thoughtbot.com/blog/how-to-reduce-a-large-heroku-compiled-slug-size) pero no funcionó.

Gracias!

**Comment by daleal** [comment]
Hola! Estuve viendo tu repo y noté que tienes una carpeta `.bundle`. En esa carpeta, `bundler` está instalando todas las gemas para correr tu app. Dado que eso se debe instalar de máquina en máquina, te recomiendo eliminar esa carpeta, hacer commit, agregar `.bundler` al `.gitignore`, hacer commit de nuevo y luego volver a intentar hacer _push_ a Heroku.

**Comment by amparostevens** [comment]
Gracias!! Funcionó
