### ISSUE TITLE
Tipos de usuarios con devise y cancan

### ISSUE THREAD

**Issue by mseguel** [IIC2143-2020-2/syllabus#217]
Hola, tengo problemas para hacer la diferenciaciones de los usuarios, buscado mucha info pero no llego a nada, mi error es el siguiente:

![Captura de pantalla de 2020-11-01 14-01-37](https://user-images.githubusercontent.com/62021372/97809417-825a1a00-1c4b-11eb-893d-5cf7f47a4ff6.png)
![Captura de pantalla de 2020-11-01 14-03-07](https://user-images.githubusercontent.com/62021372/97809423-884ffb00-1c4b-11eb-91c7-a5fea51c0a8c.png)
![Captura de pantalla de 2020-11-01 14-03-21](https://user-images.githubusercontent.com/62021372/97809426-8c7c1880-1c4b-11eb-943e-f0a188bbfca3.png)
![Captura de pantalla de 2020-11-01 14-07-40](https://user-images.githubusercontent.com/62021372/97809443-a158ac00-1c4b-11eb-8a8a-0cadbc62c2bb.png)
ocupe el siguiente tutorial:
https://altalogy.com/blog/rails-6-user-accounts-with-3-types-of-roles/

**Comment by daleal** [comment]
Hola! El error realmente es que `current_usuario` no existe. No sé si es porque el helper quedó mal definido desde Devise o si es porque intentas llamarlo cuando no hay usuarios conectados, pero ese es el problema, todo lo demás se ve _gucci_ (en otras palabras, el problema no es la implementación de los roles, sino que la llamada a `current_usuario` retorna `nil`).

**Comment by mseguel** [comment]
Muchas gracias! Me sirvió, era lo segundo
