### ISSUE TITLE
Error deploy Heroku

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2143-2020-2/syllabus#218]
Al hacer git push heroku master me aparece el siguiente error:
![image](https://user-images.githubusercontent.com/48532824/97813502-70867000-1c67-11eb-8f5f-7a8cb8386885.png)
Hemos probado Bundle update, rails app:update:bin, rake db:migrate, y nos sigue tirando el mismo error.
Ayuda

**Comment by daleal** [comment]
Hola! El problema es que tienen saltos de línea con `CRLF` en vez de `LF`. Hay un par de _issues_ al respecto, pero esencialmente lo que deben hacer es setear sus editores de texto para que usen `LF` automáticamente en vez de `CRLF` (en `vscode` está abajo a la derecha de la pantalla, dice `CRLF` y cuando lo apretas puedes cambiarlo a `LF`) y luego entrar a todos los archivos de la app y guardarlos nuevamente. Los saltos de línea cambiarán para usar solamente `\n` en vez de `\r\n`. Particularmente, ese error es por alguno de los archivos dentro de la carpeta `bin`, por lo que podrías partir por ahí.

**Comment by VicenteElCyrano** [comment]
Funcionó, esos errores los mostraba rubocop pero no sabiamos cuales eran los errores como tal. Muchas gracias.
