### ISSUE TITLE
Migración a Heroku - Tabla no existe

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2143-2020-2/syllabus#219]
Hola!

La aplicación web funciona correctamente en `localhost`, pero al hacerle deploy a Heroku, y utilizar los comandos para migrarla, me indica que una tabla no existe:

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "bids" does not exist
: ALTER TABLE "bids" ADD "id_usuario" integer
```

Intenté reiniciar la base de datos de heroku, pero no funcionó 😢  

Gracias desde ya!

**Comment by meretamal** [comment]
Hola 😁 !!

Podrías revisar en tus migraciones si esta migración que te levanta el error (la que trata de agregar `id_usuario` a `bids`) está antes que la migración que crea la tabla `bids`?

**Comment by JosefaPaz** [comment]
Hola!

Toda la razón, ahí está el problema jajaj primero está el error y no sale nunca la migración para crear la tabla `bids`. Hay algún comando para solucionarlo?

Gracias!

**Comment by meretamal** [comment]
Puedes hacer hartas cosas:
* Si es que la migración del error solo se encarga de agregar esta columna, podrías borrarla y crear otra que haga lo mismo, así esta queda después que la migración que crea `bids`.
* Si es que la migración del error solo se encarga de agregar esta columna y no quieres borrarla, podría cambiar el _timestamp_ que lleva en el nombre, tal que ese número sea mayor al _timestamp_ que tiene la migración que crea `bids`.
* Si es que la migración del error hace más cosas, podrías borrar la linea que agrega `id_usuario` y luego crear una migración que se encargue de agregar `id_usuario`.

Te recomiendo que después de hacer alguna de estas cosas, con tu grupo boten su base de datos local y luego ejecuten las migraciones de nuevo.

Además, para evitar situaciones así a futuro, les recomiendo que, si es que quieren realizar algún cambio en su bdd, nunca toquen las migraciones originales, sino que traten de crear nuevas migraciones que realicen este cambio.

**Comment by JosefaPaz** [comment]
Ahí funcionó! Muchísimas gracias 😄 

Y sí o sí ordenaremos todo para la proxima entrega jajaj gracias!
