### ISSUE TITLE
[Tarea] Redondeo de promedios

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2143-2020-2/syllabus#22]
Hola! 
Me preguntaba si se deben redondear los promedios, y en ese caso, hasta qué decimal?
Por ejemplo, el alumno `1,Javier Kemmer,5.1,5.4,5.6,0`, posee una **NC** de `5.366666666...7`.
Gracias!

**Comment by meretamal** [comment]
Hola 😁 

No es necesario redondearlos. Te recomiendo ver los archivos de prueba que subimos.

**Comment by Christian-Klempau** [comment]
Verdad, se me había olvidado revisarlo!
Muchas gracias :)
