### ISSUE TITLE
crash aplicacion heroku

### ISSUE THREAD

**Issue by baseba** [IIC2143-2020-2/syllabus#220]
hola nuestra app hace deploy en heroku pero al momento de abrirla crashea adjunto fotos de los logs
![Captura de pantalla 2020-11-02 010642](https://user-images.githubusercontent.com/48297670/97829237-2c678f80-1ca8-11eb-8993-9a5bf76220ea.png)
![Captura de pantalla 2020-11-02 010804](https://user-images.githubusercontent.com/48297670/97829241-2e315300-1ca8-11eb-85cf-e3daf2808c4f.png)

**Comment by daleal** [comment]
Hola! Hay muchas razones por las que podría estar fallando la aplicación, el _log_ que enviaste es solamente el de la _request_, pero probablemente la app falló antes, al momento de hacerse el _deploy_
