### ISSUE TITLE
Guardar archivos permanentemente con Active Storage en Heroku

### ISSUE THREAD

**Issue by benjavicente** [IIC2143-2020-2/syllabus#221]
Hola! Para el proyecto, es **requisito que los archivos se guarden permanentemente en la aplicación?**

Lo menciono ya que se pide como atributo mínimo del usuario una imagen de perfil y en las issue #176 se menciona que:

> (...) pero en Heroku, el sistema de archivos se borra cada cierto tiempo, por lo que tendrás que usar algo como Cloudinary para almacenar las imágenes

Gracias de antemano!

**Comment by daleal** [comment]
Hola! Depende de tu negociación con tu Product Owner, pero en principio si, las imagenes **deben ser persistentes**.
