### ISSUE TITLE
Problema con rails server y mac

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2143-2020-2/syllabus#223]
Holaa! Desde la entrega pasada que tengo un problema al ejecutar rails server, en el que me salía un error (que si no me equivoco tenía que ver con Xcode). Luego de buscar posibles soluciones en muchas páginas, encontré la forma de instalar Xcode mediante un archivo .xip y finalmente después de como 3 horas buscando soluciones, logré instalarlo y que me funcionara rails server para poder trabajar en localhost.

Al día siguiente cerré ese servidor, hice push a mis cambios y mis compañeros también, pero cuando quise abrir nuevamente rails server, me apareció otro error, el que tenía que ver con la gema bcrypt.

He hecho de todo, comentar la línea en el gemfile, eliminar el gemfile.lock, cambiar la versión de esta gema y no pasa nada.
Dejaré los pantallazos de los errores acá por si alguien podría ayudarme :(

Al eliminar los números de la versión del gemfile de la gema bcrypt y ejecutar 'rails server' me aparece esto:
![Captura de Pantalla 2020-11-05 a la(s) 12 05 20](https://user-images.githubusercontent.com/48359777/98258067-2ea74380-1f5f-11eb-9da7-c532fc9b2ae5.png)

Luego ejecuto 'bundle install' y aparece esto
![Captura de Pantalla 2020-11-05 a la(s) 12 06 25](https://user-images.githubusercontent.com/48359777/98258194-55657a00-1f5f-11eb-915c-7668f54587ba.png)

Que al poner instalar me aparece lo siguiente
![Captura de Pantalla 2020-11-05 a la(s) 12 07 55](https://user-images.githubusercontent.com/48359777/98258360-8ba2f980-1f5f-11eb-9357-60275d4790a5.png)

En la terminal, a su vez, me aparece este error:
![Captura de Pantalla 2020-11-05 a la(s) 12 08 42](https://user-images.githubusercontent.com/48359777/98258442-a70e0480-1f5f-11eb-8f09-f31963abec97.png)

Y realmente estos errores me aparecen de igual forma aunque tenga o no en el gemfile la gema bcrypt (con distintas versiones, o sin versión en específico)

Ya he buscado en muchas partes distintos comandos, 2 ayudantes me han tratado de ayudar, y aún asi no logro solucionarlo :( 
Alguien sabe cómo podría arreglarlo?

**Comment by daleal** [comment]
Hola! Podrías decirme qué sucede al ejecutar `xcode-select --install`?

**Comment by JaviGuzman** [comment]
Esa línea de código me tiró error, o sea me pedía que lo instalara, pero luego decía que no encontraba el software.

![Captura de Pantalla 2020-11-12 a la(s) 00 56 51](https://user-images.githubusercontent.com/48359777/98894509-ad324280-2483-11eb-9c93-68d5a06d0f8d.png)
![Captura de Pantalla 2020-11-12 a la(s) 00 57 32](https://user-images.githubusercontent.com/48359777/98894514-af949c80-2483-11eb-80a8-3bb193c6f568.png)

Pero al instalarlo directamente de la página que pusiste me funcionooo!!
Aunque, ahora obtuve otro error, que probablemente se deba a que mis compañeros utilizan Windows y yo Mac, y no se cómo arreglarlo :(

![Captura de Pantalla 2020-11-12 a la(s) 01 11 17](https://user-images.githubusercontent.com/48359777/98894647-fa161900-2483-11eb-91a9-3c84b27f3f54.png)

Sabes qué puedo hacer para solucionar esto?

Muchas gracias de antemano por la solución anterior!!

**Comment by daleal** [comment]
Esa es probablemente una gema llamada `wdm` que no funciona bien fuera de Windows. Sirve para monitorear cambios en los archivos. No debería ser necesaria para el proyecto, así que convérsalo con tus compañeros de grupo
