### ISSUE TITLE
Problema al insertar javascript en rails

### ISSUE THREAD

**Issue by Baelfire18** [IIC2143-2020-2/syllabus#224]
Hola tengo un problema al poner un javascript en un archivo html.erb. La funcion tiene un window.onload pero no se carga al llegar por boton, solamnte se hace si recargo la página o si a la mala escribo el URL no se porque. Creo que se debe a que el onload es dintino cuando uno esta en rails, pero no se como arreglarlo.

![image](https://user-images.githubusercontent.com/50716449/98397468-27a33280-203e-11eb-9855-6f7778b6b68b.png)

**Comment by benjavicente** [comment]
Hola! Puede que sea por algo de los [turbolinks que usa Rails](https://github.com/turbolinks/turbolinks#working-with-script-elements)

Yo seguí una guía que recomendaba usar esto y me funciono perfecto:

```html.irb
# app/views/layouts/application.html.erb
<head>
    ...
    <%= yield(:head_tags) %>
</head>
```

```html.irb
# app/views/<controlador>/<método>.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      // código javascript
    });
  </script>
<% end %>
```

**Comment by daleal** [comment]
Hola! Confirmo que el problema son los turbolinks (es una tecnología para no tener que re-cargar algunas partes del HTML al cambiar de página, para hacer parecer que no se está cargando una página nueva, pero genera algunos conflictos con el JavaScript). Prueba la solución de @benjavicente, parece ser bastante apropiada.
