### ISSUE TITLE
Error al ejecutar rails s

### ISSUE THREAD

**Issue by Sadhguy** [IIC2143-2020-2/syllabus#227]
![image](https://user-images.githubusercontent.com/62361849/98882375-dd211c00-246a-11eb-88a7-e62cd0a2d052.png)
Al ejecutar rails s me tira este error. Tengo todas las gemas instaladas y estoy al corriente con las migraciones. Pls help

**Comment by daleal** [comment]
Hola! Podrías decirme qué sucede al ejecutar `bundle exec rails s`?

**Comment by Sadhguy** [comment]
Me arroja el mismo error :(
