### ISSUE TITLE
Actualizar un form con información nueva

### ISSUE THREAD

**Issue by benjavicente** [IIC2143-2020-2/syllabus#228]
Hola! Estoy tratando de seguir la guia de Rails para [mostrar los errores al crear un record](https://guides.rubyonrails.org/v5.2/active_record_validations.html#displaying-validation-errors-in-views) en un form, pero **al hacer el `render` en el controlador respectivo, la página en el navegador se queda con los mismos contenidos**: no hay `errors.any?`  y tampoco se añade el `<div class="field_with_errors">`.

En la consola se muestra que se hacer el request y el render:

```
Rendered articles/new.html.erb within layouts/application
Completed 200 OK
```

En la vista tengo un form básico junto al código que se muestra en la guía y tengo algo así en el controlador:

```rb
  ...
  def new
    @article = Article.new
  end

  def create
    @article= Article.create(article_params)
    if @article.save
      redirect_to article_path
    else
      render :new
    end
  end
  ...
```
¿Qué puede estar faltando? Gracias de antemano!

**Comment by meretamal** [comment]
Hola 😁 

Podrías mandar el contenido del _form_ que estás usando?

**Comment by benjavicente** [comment]
En resumen, tengo esto en los forms de la vista:

```html.erb
...
<%= form_with(model: @article, method: :post) do |form| %>

    <div class="field">
      <%= form.label :name, class: 'label' %>
      <%= form.text_field :name, class: 'input' %>
    </div>

    <div class="field">
      <%= form.label :image, class: 'label'  %>
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.label :description, class: 'label' %>
      <%= form.text_area :description, class: 'textarea' %>
    </div>

    ...

    <div class="field">
      <%= form.label :date, class: 'label' %>
      <%= form.date_field :date, class: 'input' %>
    </div>

    <div class="action">
      <%= form.submit class: 'button is-primary' %>
    </div>

  <% end %>
...
```
lo que creo que debería pasar, es que al hacer el `render`, los contenidos del form se deberían cargar nuevamente, pero al añadir un ` <%= rand  -%>` para verificar que está pasando, al hacer `render` el número no cambia.

**Comment by meretamal** [comment]
Lo que pasa es que `form_with` por defecto está pensado para utilizar Ajax, por lo que previene la acción por _default_ del _form_.

Intenta agregando `form_with(model: @article, method: :post, local: true)`

**Comment by benjavicente** [comment]
Con eso me funcionó! Gracias!

> Lo que pasa es que `form_with` por defecto está pensado para utilizar Ajax, por lo que previene la acción por _default_ del _form_.

No entendí eso, ¿cuál sería la acción por defecto? Yo pensé que Rails se encargaba de actualizar la parte del form (dentro del bloque `form_with`) al hacer el request. Esta solución actualiza toda la página, pero con eso me conformo.

**Comment by meretamal** [comment]
Hola @benjavicente, perdón por contestar recién ahora 🙈 .

Para contextualizar un poco el tema, **AJAX** es un acrónimo para **A**synchronous **J**avaScript **A**nd **X**ML, la cual es una herramienta utilizada para realizar cambios sobre las páginas sin la necesidad de recargarlas, mejorando la interactividad, velocidad y usabilidad de las aplicaciones. Por ejemplo, si implementan una funcionalidad de _likes_ y _dislikes_, por el momento, con las herramientas que conocen, al presionar el botón tendrían que recargar la página para ver el cambio, en cambio, utilizando AJAX, se hace el _request_ y se actualiza la vista utilizando JavaScript (si quieres aprender un poco más de este tema, puedes preguntarme).

Sin embargo, para poder hacer esto es necesario evitar la acción por _default_ del _form_, ya que sino la página se recargaría al hacer _submit_ de él.

`form_with` por defecto utiliza AJAX (a diferencia de `form_tag` o `form_for`), por lo que hay que "decirle" que no evite la acción por _default_ y esto se hace agrando `local: true` en él.

**Comment by benjavicente** [comment]
> (AJAX) es una herramienta utilizada para realizar **cambios sobre las páginas sin la necesidad de recargarlas**

> es necesario evitar la acción por default del form, ya que sino la página **se recargaría al hacer submit de él**.

> **`form_with` por defecto utiliza AJAX** (a diferencia de `form_tag` o `form_for`), por lo que hay que "decirle" que no evite la acción por _default_

Me enrede un poco 😅. Entendí perfecto que hace AJAX, pero no como Rails lo implementa y que es lo que se hace por defecto, porque `form_with` por defecto no recarga o actualiza la página, y no se muestran los [mensajes de error del helper](https://guides.rubyonrails.org/v5.2/active_record_validations.html#displaying-validation-errors-in-views).

Lo otro respecto a AJAX, el objetivo es mandar trozos de HTML con XML? Vi un par de ejemplos y no me quedó claro porque se usa `XML` en vez de algo más "compacto" como `JSON`  (o si se usan ambos), por ejemplo, [cuando se usa para crear una tabla](https://www.w3schools.com/js/tryit.asp?filename=tryjs_ajax_xml2).

**Comment by meretamal** [comment]
Hola 😁 

La verdad que explicar todo en una _issue_ es un poco difícil jaja.

Si quieres me puedes hablar por telegram (meretamal) y te puedo mandar una ayudantía que hice de esto hace un año, o hasta podríamos coordinar una llamada para explicarte bien todo.
