### ISSUE TITLE
Fecha entrega 3.

### ISSUE THREAD

**Issue by jjaubele** [IIC2143-2020-2/syllabus#229]
Hola, escribo para consultar la posibilidad de aplazar la entrega 3 para el domingo al igual que en la entrega 2. Siento que varios estamos necesitados de tiempo y estos días serían vitales para nuestra entrega. Dejo esta issue aquí para que, si lo estiman necesario, puedan reaccionar y mostrar su apoyo a está propuesta.

**Comment by daleal** [comment]
Hola! Finalmente el plazo será ampliado **hasta el domingo 22 de Noviembre a las 23:59**, es decir, **tienen 48 horas extra para terminar su Sprint** 🎉
