### ISSUE TITLE
Duda con el comando a ejecutar

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#23]
Hola.
No entiendo qué es lo que debería hacer el comando que ejecutarán.
![image](https://user-images.githubusercontent.com/59337116/90546432-0fff9080-e158-11ea-8460-f34f9bcfc613.png)
Me podrían explicar qué pasa con el archivo de instrucciones y el output?, lo que entiendo es que de acuerdo a las instrucciones yo debo crear el archivo output con la respuesta correspondiente, pero entonces por qué es parte del comando que ustedes pondrán?

**Comment by Camila-sty** [comment]
Ya lo entendí, no pude eliminar la issue. Gracias!

**Comment by cchauriye** [comment]
Hola!

En cada corchete debes reemplazar por los nombres de los archivos correspondientes correspondientes. 
- 'datasets_folder': carpeta donde están los archivos csv con los datos.
- 'instruction_file': es el archivo que contiene las instrucciones del programa. Está en la misma carpeta que 'main.rb' de acuerdo al enunciado.
- 'output_file': es el nombre del archivo de output. El archivo de output no lo creas tu, sino que lo crea tu programa usando como nombre de archivo ese input. 

Por ejemplo, si yo corro "ruby main.rb data instr.txt output.txt", entonces se creará un archivo de nombre "output.txt".
