### ISSUE TITLE
Problema al agregar rating

### ISSUE THREAD

**Issue by dpacevedo** [IIC2143-2020-2/syllabus#231]
Hola! :blush:

Tengo una pregunta sobre bulma, con mi grupo estamos intentando mostrar la calificación de un servicio mediante la visualización de su calificación promedio en estrellas, sin embargo, solo nos muestra el número y no las :star: :star: :star: :star: :star:. No sabemos bien dónde está el error ya que es solo problema de visualización, adjunto el código.

![imagen](https://user-images.githubusercontent.com/48335327/99749329-0f5ef900-2abd-11eb-9f33-3c3f31734cfb.png)

Muchas gracias de antemano!

**Comment by daleal** [comment]
Hola! Podrías decirme exactamente qué elemento de Bulma estás tratando de utilizar?

**Comment by dpacevedo** [comment]
Hola! Nos basamos en este tutorial [https://www.youtube.com/watch?v=wOIQDO1yF80&t=2125s], pero lo solucionamos 😊 

Muchas gracias de todas maneras!
