### ISSUE TITLE
Problema vista para usuario no logeado

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2143-2020-2/syllabus#232]
Quiero ingresar a una vista como usuario no logeado, y al momento de ir a la vista me sale este error.
![image](https://user-images.githubusercontent.com/48532824/99753202-94014580-2ac4-11eb-864b-3e256c71968a.png)
Busqué el error pero como que la búsqueda no me aportó mucho, ayuda

**Comment by VicenteElCyrano** [comment]
ah, quiero creer que el error es de bulma, pero literal esa vista es la copia de carretes para usuarios registrados pero con menos cosas respecto a su contenido, asi que en caso de ser bulma el problema ni idea porqué se origina

**Comment by benjavicente** [comment]
Hola! Eso creo que pasa cuando no hay un archivo de vista asociado al método del controlador. Ve si tienes el archivo `app/views/home/carretes_no_registrados.html.erb` con el nombre bien escrito.

**Comment by VicenteElCyrano** [comment]
Tengo bien las vistas y rutas, de hecho como que llego a la vista pero esta no carga y tira el error

**Comment by daleal** [comment]
Hola! Podrías mandar un _pantallazo_ de los archivos dentro de la carpeta `app/views/home`?

**Comment by VicenteElCyrano** [comment]
No sé que cambié pero lo arreglé, gracias.

**Comment by daleal** [comment]
OK, si entiendes qué hiciste para resolverlo, por favor comenta en esta _issue_ por si otra persona tiene el mismo problema.
