### ISSUE TITLE
Error de rutas

### ISSUE THREAD

**Issue by Witomi** [IIC2143-2020-2/syllabus#233]
Hola!

Estoy tratando en rspec de testear el metodo delete, este es mi caso:
![image](https://user-images.githubusercontent.com/48265428/99852890-ad57cf80-2b60-11eb-823e-0aed8b2394b7.png)

Sin embargo, me retorna lo siguiente:
![image](https://user-images.githubusercontent.com/48265428/99852962-d37d6f80-2b60-11eb-9927-32714be41e1d.png)

El problema al final es que antes del id (en la última foto) pone un "." en vez de un "/", a qué se puede deber?

Muchas Gracias!!!

**Comment by daleal** [comment]
Hola! Podrías tratar pasándole solamente `@service` al helper `services_path`?

**Comment by benjavicente** [comment]
Hola! Esto me ha pasado cuando la ruta que estoy usando (`services_path` en este caso) es algo como `/services` en vez de `/service/:id`. Puede que el nombre del helper de la ruta sea otro, como `service_path`.

**Comment by Witomi** [comment]
Al final lo de benjavicente me funcionó, que raro, dado que lo tenia con el helper de services.
Muchas gracias a ambos!
