### ISSUE TITLE
Permisos de usuario con cancan

### ISSUE THREAD

**Issue by mseguel** [IIC2143-2020-2/syllabus#234]
Hola, estoy teniendo problemas con los roles de usuario y sus permisos, por ejemplo, un user_role (usuario normal) puede hacer lo mismo que un admin. Ocupe cancan para la creación de los usuario. En las views reconoce los tipos de usuario, por lo que creo que tengo algo malo en este archivo

![user_role](https://user-images.githubusercontent.com/62021372/99856484-d039b200-2b67-11eb-8b9f-f901fb5f7a81.png)

**Comment by daleal** [comment]
Hola! Cómo estás chequeando los permisos al momento de tratar de acceder a un modelo? Estás usando `load_and_authorize_resource` en el controlador? O estás usando el método `can?` para chequear?
