### ISSUE TITLE
Error Rspec

### ISSUE THREAD

**Issue by hsazos** [IIC2143-2020-2/syllabus#235]
Hola!

Estoy teniendo problemas para testear mis comentarios. Como tienen una asociación belongs_to con User y Service, al testearlo me tira error porque no le asigno ni User ni Service, pero los atributos correspondientes a los id de User y Service existen. Mi duda es: ¿Como puedo, en el contexto de testeo, agregar esa relacion para que no me tire ese error? Adjunto pantallazo en el siguiente comentario.

**Comment by hsazos** [comment]
![image](https://user-images.githubusercontent.com/48263455/99866605-3f77cc00-2b91-11eb-8599-cc18d66a6879.png)
![image](https://user-images.githubusercontent.com/48263455/99866610-46064380-2b91-11eb-8ef1-d08c39af1d8d.png)

**Comment by daleal** [comment]
Hola! Probablemente es porque, en vez de asignarle un `id` a mano al comentario, deberías hacer `subject.save`

**Comment by hsazos** [comment]
@daleal  gracias! Podrías explayarte un poco más? Que me tiene bien confundido ese error y me gustaría entenderlo para no repetirlo :).

**Comment by daleal** [comment]
Disculpa, acabo de leer el error correctamente, en realidad la forma en que defines el comentario es correcta. Sin embargo, como puedes ver, la razón por la que la validación falla es porque no existe un usuario de `id` 1 ni existe un servicio de `id` 1. Para que la validación funcione probablemente necesitas crear dichos objetos.

**Comment by hsazos** [comment]
ahhh perfecto, muchas gracias!!
