### ISSUE TITLE
SimpleCov omite controladores sin tests

### ISSUE THREAD

**Issue by benjavicente** [IIC2143-2020-2/syllabus#239]
Holá! Me di cuenta que **SimpleCov está omitiendo un controlador llamado `carreterequests_controller.rb`.** Esto hace que no se tome correctamente la cobertura de nuestra aplicación. Tengo la configuración que se mostró en la ayudantía más un formateador de JSON de los resultados:

```rb
# spec/spec_helper.rb
require 'simplecov'
require 'simplecov-json'

SimpleCov.formatters = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::HTMLFormatter,
  SimpleCov::Formatter::JSONFormatter
])

SimpleCov.start do
  add_filter '/config/'
  add_filter '/spec/'
  add_filter '/test/'
  add_filter '/vendor/'

  add_group 'Controllers', 'app/controllers'
  add_group 'Models', 'app/models'
  add_group 'Helpers', 'app/helpers'
end

# This outputs the report to your public folder
# You will want to add this to .gitignore
SimpleCov.coverage_dir 'public/coverage'
```
## Cobertura generada 
![covertura](https://user-images.githubusercontent.com/62021328/99916591-c50e8f80-2ce9-11eb-8afd-2506b65c215a.png)

## Archivos de controladores
```tree
app/
├── controllers
│  1├── application_controller.rb
│  *├── carreterequests_controller.rb
│  3├── carretes_controller.rb
│  4├── comentarios_controller.rb
│  5├── communes_controller.rb
│  6├── services_controller.rb
│  7├── services_requests_controller.rb
│   ├── users
│   │   ├── confirmations_controller.rb
│   │   ├── omniauth_callbacks_controller.rb
│   │   ├── passwords_controller.rb
│   │   ├── registrations_controller.rb
│   │   ├── sessions_controller.rb
│   │   └── unlocks_controller.rb
│  8├── users_controller.rb
│  9└── welcome_controller.rb
```

¿Que puede ser lo que esté fallando o faltando? gracias de antemano

**Comment by daleal** [comment]
Hola! Cual es el nombre de la clase del controlador? Dado el nombre del archivo, debería ser `CarreterequestsController`. Me imagino que es `CarreteRequestsController` (que tiene más sentido para nosotros pero no para Rails). Para arreglar eso, debes cambiar el nombre del archivo del controlador a `carrete_requests_controller.rb`

**Comment by benjavicente** [comment]
El nombre del controlador es `CarreterequestsController`, probe cambiandole el nombre tanto a la clase como al archivo (solo del controlador) y no se añadío 🤔

**Comment by daleal** [comment]
Extraño 🤔 puedes mandarme el contenido de tu controlador?

**Comment by benjavicente** [comment]
Me acabo de dar cuenta de que solo se añaden a la cobertura si tienen tests 😅, ya que al añadir uno aparece en el reporte. Aunque es muy raro eso, porque podría tener fácilmente 100% de cobertura si hago solo test a un controlador.

**Comment by daleal** [comment]
😲 que extraño 🤔 bueno, al menos el misterio fue resuelto jajajajajajaajaja
