### ISSUE TITLE
Orden de los archivos CSV

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#24]
Hola!
En el anunciado mencionan que el archivo de las instrucciones puede tener un orden distinto, pero tengo la duda con los archivos CSV, en cuanto a sus ids. Ahora nos entregaron los archivos de ejemplos donde los 3 están ordenados según su id de menor a mayor, esto será así siempre?

**Comment by meretamal** [comment]
Hola 😁 

No necesariamente. Asume que pueden llegar en desorden.

**Comment by Camila-sty** [comment]
😟 Gracias!!
