### ISSUE TITLE
Turbolinks heroku error

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2143-2020-2/syllabus#240]
Hola, cuando utilizo mi app en local va de maravilla, pero al momento de subirla a heroku y al realizar algun metodo (edit, create, delete) estos se aplican pero la página no redirige, y al momento de salirme con un botón manualmente aparece el notice.
Como si la parte subrayada no la utilice: 
![image](https://user-images.githubusercontent.com/48532824/99924634-d7082680-2d19-11eb-80ca-312e0aeb0bf8.png)
Antes no nos pasaba, ahora si. nefasto

**Comment by VicenteElCyrano** [comment]
Al pulsar el boton aparece esto en la consola del navegador 
![image](https://user-images.githubusercontent.com/48532824/99924679-fa32d600-2d19-11eb-9ebc-d463aa2ca2d3.png)

**Comment by benjavicente** [comment]
Esto puede que sea que falte javascript que se añade por defecto, ve si tienes esto:
```html
<!-- en app/views/layouts/application.html.erb -->
<head>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
```

**Comment by VicenteElCyrano** [comment]
Tenemos esa linea en application.html.erb :(

**Comment by benjavicente** [comment]
Ve si puedes [desactivarlos o activarlos](https://stackoverflow.com/a/38649595). Supuestamente tiene que estar también `//= require turbolinks` en `application.js` y la gema `gem 'turbolinks', '~> 5'`

**Comment by Baelfire18** [comment]
Hola @benjavicente nosotros tenemos exactamente el mismo problema con los create, edit, delete. La única forma de solucuionarlo es apagar todos los tubro links de la app? No hay otra forma. ¿Por qué igual se supone tienen utilidad o no?

**Comment by benjavicente** [comment]
@Baelfire18, supongo que sí. Me imagino que puede ser un problema en el javascript que se compila, algo como que [variables globales](https://yeisondaza.com/entendiendo-scopes-de-variables-en-javascript) choquen con las que están en `Turbolinks` cuando se juntan los archivos (cosa que pasa en production pero no en development). Según su repositorio:
> [Turbolinks®](https://github.com/turbolinks/turbolinks) makes navigating your web application faster. Get the performance benefits of a single-page application without the added complexity of a client-side JavaScript framework. Use HTML to render your views on the server side and link to pages as usual. When you follow a link, Turbolinks automatically fetches the page, swaps in its <body>, and merges its <head>, all without incurring the cost of a full page load.

pd no soy ayudante de este ramo xd

**Comment by daleal** [comment]
Hola! Los Turbolinks son una librería de JavaScript que se utiliza para no recargar todo el HTML al momento de cambiar de página, cargando solamente el `body` y no el resto. La única utilidad que tienen es dar la impresión de que la página se carga más rápido. No debería haber problema con que desactiven Turbolinks. En cualquier caso, creo que el problema efectivamente debe estar en el paso de compilación de _assets_ en producción, pero a simple vista no veo nada erróneo, por lo que debe ser un problema más profundo de lo que se ve (podría incluso no estar relacionado con Turbolinks pero estarse cayendo en esa parte del flujo por un error previo, por ejemplo).
