### ISSUE TITLE
Problema deploy a heroku api google maps

### ISSUE THREAD

**Issue by rinorambuena** [IIC2143-2020-2/syllabus#241]
Hola!

Con mi grupo utilizamos la api de google para mostrar los mapas de las ubicaciones y otra que autocompleta la información con la dirección. Cuando corremos la app a nivel local funciona a la perfección, sin embrago, en heroku solo funciona mostrar el mapa y no la parte de autocompletado. Estuvimos buscando como arreglar este problema y casi todas las soluciones fueron ver si teníamos activa la api, la cual si lo está. Alguien sabe cómo solucionar este problema?

**Comment by daleal** [comment]
Hola! A veces esas APIs funcionan cuando están en un entorno de desarrollo pero en producción puede que cobren/necesiten llaves especiales. Cómo dice la documentación que debe ser usada?

**Comment by inzuniga** [comment]
Hola! Yo igual soy parte del grupo y cuando busco la documentación de la api me aparece lo siguiente:

![WhatsApp Image 2020-11-27 at 21 19 57](https://user-images.githubusercontent.com/48324412/100491559-3643ad80-3103-11eb-8c85-c1e941b59991.jpeg)

Y al ingresar las listas de las apis activas en el dashboard me aparece esto:

![WhatsApp Image 2020-11-27 at 21 20 32](https://user-images.githubusercontent.com/48324412/100491568-52474f00-3103-11eb-9359-de010bc833c9.jpeg)

**Comment by daleal** [comment]
Mi pregunta realmente es si en la documentación se explica qué credenciales necesitan para poder usar la API (a veces necesitas crear una cuenta de servicio para poder usarlas en producción, por ejemplo)

**Comment by inzuniga** [comment]
No, no explica nada al respecto

**Comment by daleal** [comment]
OK, mira, te explico. Todas las APIs de Google necesitan que las autentiques para usarlas en tus aplicaciones. Te dejo la documentación de cómo usar la API key de maps [aquí](https://developers.google.com/maps/documentation/javascript/get-api-key).

**Comment by inzuniga** [comment]
Gracias por la ayuda! Finalmente era un problema con los turbolinks
