### ISSUE TITLE
Error con Ventana Modal (Al cerrar se envía dos veces el formulario )

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#243]
Hola!Tengo un problema lo que pasa es que implemente una ventana modal para dar un aviso a un usuario acerca de un evento al momento de rellenar un formulario ,en este caso un formulario para crear un servicio, esta ventana funciona  sin embargo cuando se intenta cerrar con la "x" que esta en la esquina superior derecha, se entiende esto al ver la foto adjunta, el formulario es enviado dos veces y por lo tanto se crea dos servicios iguales , lo extraño es que esto pasa solo cuando se intenta cerrar el aviso de esta manera al hacerlo dando click en alguna parte de la ventana negra este problema no pasa , por que pasaría esto?
![Captura de pantalla (566)](https://user-images.githubusercontent.com/62029138/100648379-9d3dae00-331f-11eb-9db2-9da23130497a.png)
 Adjunto también el código en javascript que se uso para esto:
![Captura de pantalla (569)](https://user-images.githubusercontent.com/62029138/100648823-44bae080-3320-11eb-9abc-00fe6ef7840d.png)

**Comment by daleal** [comment]
Hola! Cómo haces la request al servidor una vez cerrado el modal?

**Comment by RonaldoSosa** [comment]
Hola!Lo que pasa es que yo hago de que el modal aparezca una vez se presione el botón "Crear servicio" , supongo que este se presione una vez se completen los datos del formulario.

**Comment by daleal** [comment]
No estoy seguro de por qué está ocurriendo la interacción, pero lo que si sé es que hay algo que puede estar ocurriendo extraño: Cuando presionas el botón de enviar, dado que es un formulario, se envía automáticamente al servidor. Acto seguido, estás abriendo el modal. Esto puede tener algún efecto secundario. Intenta sacando el modal del flujo y ve si funciona todo bien. En caso de ser así, el problema es alguna interacción entre la request del form y el javascript.

**Comment by RonaldoSosa** [comment]
Hola!Hice lo que me dijiste y lo comprobé sin el modal el formulario se envía una sola vez
