### ISSUE TITLE
Problema con bundle install

### ISSUE THREAD

**Issue by Naogaz** [IIC2143-2020-2/syllabus#244]
Estoy teniendo el siguiente problema al hacer bundle install.
![Sin título](https://user-images.githubusercontent.com/48302271/101126708-cc337880-35da-11eb-9ff0-be1f066cd928.png)

**Comment by daleal** [comment]
Hola! Parece ser un error de _networking_ de WSL. Mi única recomendación sería reiniciar tu computador y volverlo a intentar.
