### ISSUE TITLE
heroku controlador que no existe da error

### ISSUE THREAD

**Issue by baseba** [IIC2143-2020-2/syllabus#247]
cuando subo la app a heroku hay un controlador que da un error pero en nuestro proyecto  adjunto foto de nuestro erro y de los controladores
![image](https://user-images.githubusercontent.com/48297670/101958703-9c8bfe00-3be2-11eb-8b99-8aee2161a647.png)
![image](https://user-images.githubusercontent.com/48297670/101958732-a877c000-3be2-11eb-8eb7-a2d029ec9833.png)

**Comment by benjavicente** [comment]
Hola! no soy ayudante, pero
ese error quiere decir que el método del controlador (o ApplicationController) no existe, probablemente porque Heroku tiene una versión de Rails donde `before_filter` no exista (debería ser `before_action`, como recomienda en el error)

https://stackoverflow.com/a/16519841

> As we can [see][1] in ```ActionController::Base```, ```before_action``` is just a [new syntax][3] for ```before_filter```.
> However all ```before_filters``` syntax [are deprecated][2] in **Rails 5.0** and will be removed in **Rails 5.1**


[1]: https://github.com/rails/rails/blob/master/actionpack/lib/abstract_controller/callbacks.rb
[2]: https://github.com/rails/rails/blob/v5.0.0.beta2/actionpack/lib/abstract_controller/callbacks.rb#L190-L193
[3]: https://github.com/rails/rails/commit/9d62e04838f01f5589fa50b0baa480d60c815e2c

**Comment by baseba** [comment]
claro eso es, el problema es que no existe el controlador commontator 😕

**Comment by benjavicente** [comment]
Es un controlador de la gema `commontator`, parece que las versiones más nuevas arreglan eso. Ve si cambiando la versión en `Gemfile` funciona.

**Comment by baseba** [comment]
Era eso, te pasaste, infinitamente agradecido ajjaja tenia una version super antigua 😂
