### ISSUE TITLE
Error: undefined local variable or method

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#27]
Hola cuando intento correr una función me tira el siguiente error main.rb:128:in `aprobados': undefined local variable or method `array_de_alumnos' for main:Object (NameError)
por lo que revise en línea esto pasa cuando instancio una funcion antes de definirla pero no es mi caso, como podría solucionarlo ,podría subir mi código por acá?

**Comment by jerosalazar** [comment]
Estas seguro que estás llamando bien a la variable array_de_alumnos? Este error te sale dentro de una función, un método de una clase o en otro lugar?

**Comment by RonaldoSosa** [comment]
me sale dentro de una función , lo que hago con array_de_alumnos , es array_de_alumnos.each do |alumnos|

**Comment by jerosalazar** [comment]
Revisa si lo estás definiendo bien, te recomiendo hacer un `puts array_de_alumnos` para revisar que es lo que contiene

**Comment by jerosalazar** [comment]
O `puts array_de_alumnos.inspect`

**Comment by RonaldoSosa** [comment]
![Captura de pantalla (18)](https://user-images.githubusercontent.com/62029138/90573704-18ba8b80-e185-11ea-983e-5d465458964a.png)

**Comment by RonaldoSosa** [comment]
segun el puts esta bien definido ya que me tira las clases :(

**Comment by jerosalazar** [comment]
Háblame por telegram pra que lo veamos más en detalle @jerosalazar

**Comment by RonaldoSosa** [comment]
no te lo puede ser por mail? no tengo telegram y de momento no puedo registrarme XD

**Comment by meretamal** [comment]
Hola, por casualidad estás definiendo esa variable fuera de tu función?

**Comment by RonaldoSosa** [comment]
sii era eso :)))), respecto a eso tengo una duda seria valido si defino ese array como una variable global , asi si me funciono , o tendría que hacerlo dentro de la funcion ?

**Comment by jerosalazar** [comment]
Generalmente no se considera como muy buena práctica llamar a una variable global desde la función. Se me ocurre que podrías pasarla como parámetro o definirla dentro de la función y retornarla

**Comment by RonaldoSosa** [comment]
Entendido! , muchas gracias por la ayuda :)
