### ISSUE TITLE
espacio vacío al finalizar linea

### ISSUE THREAD

**Issue by F-arellano** [IIC2143-2020-2/syllabus#29]
quería saber si el output "{id 1} {nombre 1} " es igual de válido que "{id 1} {nombre 1}", o si al momento de ser corregida la tarea los espacios al final serán considerados como una respuesta erronea

**Comment by daleal** [comment]
Hola! Dado que las tareas serán revisadas por un _script_ que compara el output esperado con el suyo, un espacio extra al final **será considerado erróneo**

**Comment by lewebe** [comment]
@daleal Hola! Cómo se puede evitar que el archivo de texto creado termine con una línea vacía? Parece ser que ocurre de manera automática...

**Comment by daleal** [comment]
No debería ocurrir de manera automática. Puede ser que estés haciendo una iteración que primero escribe una línea y luego un salto de línea para escribir la siguiente línea y no estás manejando el caso final. Sin embargo, **si** puedes dejar una última línea vacía al final del archivo.

**Comment by Juan379** [comment]
Para quedar claro entonces, si el archivo de output entregado para probar tiene 90 líneas y el mio es exactamente igual pero tiene 91 líneas, siendo la última vacía, se considerará esto correcto o erróneo?

**Comment by daleal** [comment]
Si, si tu output es **exactamente igual** excepto en que el tuyo tiene una línea vacía **al final del archivo**, eso se considerará correcto.
