### ISSUE TITLE
duda ejecucion

### ISSUE THREAD

**Issue by Crespy98** [IIC2143-2020-2/syllabus#30]
no me habia quedado muy claro el comando que se correra, seria este `ruby main.rb data/alumnos.csv data/ayudantes.csv data/grupos.csv insrt.txt ouput.txt`

**Comment by jerosalazar** [comment]
No, debes correrla como `ruby main.rb data instrucciones.txt output.txt`, dentro de tu programa debes hacer que lea los archivos csv dentro del directorio (data) que le entregas
