### ISSUE TITLE
Ruby + Visual Studio Code

### ISSUE THREAD

**Issue by dpacevedo** [IIC2143-2020-2/syllabus#31]
Hola! :blush:

He estado intentando correr mis códigos directamente en vscode, sin tener que recurrir a la terminal. Para ello seguí las instrucciones de este link https://github.com/rubyide/vscode-ruby/blob/master/docs/debugger.md  e instalé todas las _gems_ necesarias, sin embargo, no funciona. Luego de apretar f5, no me aparece nada en _debug console_ y tampoco me indica si hay un error.

Instalé ruby en base a este tutorial https://www.youtube.com/watch?v=iR0tFkeHIoc, mi sistema operativo es Windows y estoy usando la terminal por ahora.

Muchas gracias de antemano! :sunflower:

**Comment by daleal** [comment]
Hola! Noté que seguiste un tutorial para setear el _debugger_ con el objetivo de ejecutar el código sin necesidad de acceder al terminal. Hay alguna razón en particular para eso? (el _debugger_ sirve para cuando quieres, por ejemplo, ejecutar hasta cierta línea y ver qué valor tiene cada variable de tu ejecución hasta entonces). En realidad, creo que deberías usar algo [como esto](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) para poder lograr tu objetivo.

**Comment by dpacevedo** [comment]
Súper! Muchas gracias :blush:
