### ISSUE TITLE
Contenido a subir en el Zip

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2143-2020-2/syllabus#33]
¿En el zip unicamente tiene que ir el archivo main.rb o algunos más? Que no me quedo claro con el enunciado

**Comment by jerosalazar** [comment]
Hola! Deben ir todos los archivos necesarios para hacer correr tu tarea, excepto los archivos csv y txt. Es decir que si tu tarea tiene main.rb, extras.rb, la carpeta con data, instrucciones.txt y output.txt, solo deberías incluir main.rb y extras.rb en el zip

**Comment by gachondoj** [comment]
Hola, entonces como lo hacemos con los paths?

Gracias

**Comment by meretamal** [comment]
Hola 😁 

Si te refieres a los _paths_ a los archivos **csv** y **txt**, tal como se indica en el enunciado, estos se dan en un **ARGV** al momento de corregir tu tarea.

**Comment by dpacevedo** [comment]
Hola!
¿El zip debe tener algún nombre en particular, como nuestro número de alumno o nombre?

Gracias! :sunflower:

**Comment by meretamal** [comment]
Hola 😁 

Ponle tu número de alumno seguido de tu nombre.
