### ISSUE TITLE
Problema con Git

### ISSUE THREAD

**Issue by burgosibarra** [IIC2143-2020-2/syllabus#34]
Hola! Quería consultar sobre si les ha ocurrido o tienen una solución al siguiente problema: Al abrir git, o ejecutar un comando (desde cd, ls o git pull) la consola de git bash trabaja muy lenta (cosa que nunca me había pasado, si antes tardaba 1-3 segundos, ahora son 10-15). He intentado buscar en internet, pero no encuentro nada que me de seguridad (algunos hablan de desactivar AMD, pero no entiendo muy bien el por qué y cómo  hacer).
Desde ya, muchas gracias

**Comment by johnowenatala** [comment]
Hola, ¿En qué OS estás? Si es windows, ¿qué versión? ¿qué programa estás usando para la consola (ej: cmd, powershell, terminal)?

**Comment by burgosibarra** [comment]
Estoy usando Windows 10, mi versión de git es "git version 2.28.0.windows.1" (resultado de hacer git --version en el cmd).
Para la consola estoy usando GIT BASH (la opción que aparece al dar click derecho sobre la carpeta de un repositorio).

**Comment by daleal** [comment]
Me puedes decir si instalaste `nvm` o `rvm`? A veces esos programas enlentecen el inicio del terminal

**Comment by burgosibarra** [comment]
Si he instalado, ruby y node, pero no estoy seguro de haber instalado esos programas (No los había escuchado tampoco, los acabo de buscar en google)

**Comment by daleal** [comment]
Puedes en el terminal ejecutar los siguientes comandos:

```bash
which nvm
which rvm
```

Y decirme qué te sale con cada uno?

**Comment by burgosibarra** [comment]
"which" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by jerosalazar** [comment]
Hola, que comando estas corriendo?

**Comment by daleal** [comment]
Eso te sale dentro del Git Bash? En cualquier caso, si es así, dime qué te retornan los siguientes comandos:

```bash
nvm --version
rvm --version
```

**Comment by burgosibarra** [comment]
Disculpa, lo había hecho en cmd. Aquí van los output de git bash
**which nvm**
which: no nvm in (/c/Users/Nicolas/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Nicolas/bin:/c/Python38/Scripts:/c/Python38:/c/Rtools/bin:/c/gurobi811/win64/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files (x86)/Wolfram Research/WolframScript:/c/Users/Nicolas/AppData/Local/Microsoft/WindowsApps:/c/adb:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Program Files/MiKTeX/miktex/bin/x64:/c/Strawberry/c/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Program Files/PostgreSQL/12/bin:/c/sqlite3:/c/Program Files (x86)/Yarn/bin:/cmd:/c/Ruby27-x64/bin:/c/Users/Nicolas/AppData/Local/Programs/Python/Python36/Scripts:/c/Users/Nicolas/AppData/Local/Programs/Python/Python36:/c/Users/Nicolas/AppData/Local/Programs/Python/Python37/Scripts:/c/Users/Nicolas/AppData/Local/Programs/Python/Python37:/c/Users/Nicolas/AppData/Local/Microsoft/WindowsApps:/c/Users/Nicolas/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/Nicolas/AppData/Roaming/npm:/c/Users/Nicolas/AppData/Local/Yarn/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)

**which rvm**
which: no rvm in (/c/Users/Nicolas/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Nicolas/bin:/c/Python38/Scripts:/c/Python38:/c/Rtools/bin:/c/gurobi811/win64/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files (x86)/Wolfram Research/WolframScript:/c/Users/Nicolas/AppData/Local/Microsoft/WindowsApps:/c/adb:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Program Files/MiKTeX/miktex/bin/x64:/c/Strawberry/c/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Program Files/PostgreSQL/12/bin:/c/sqlite3:/c/Program Files (x86)/Yarn/bin:/cmd:/c/Ruby27-x64/bin:/c/Users/Nicolas/AppData/Local/Programs/Python/Python36/Scripts:/c/Users/Nicolas/AppData/Local/Programs/Python/Python36:/c/Users/Nicolas/AppData/Local/Programs/Python/Python37/Scripts:/c/Users/Nicolas/AppData/Local/Programs/Python/Python37:/c/Users/Nicolas/AppData/Local/Microsoft/WindowsApps:/c/Users/Nicolas/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/Nicolas/AppData/Roaming/npm:/c/Users/Nicolas/AppData/Local/Yarn/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)

**nvm --version**
bash: nvm: command not found

**rvm --version**
bash: rvm: command not found

**Comment by daleal** [comment]
Mmmmh... Podrías mandarme como texto formateado el _output_ del siguiente comando?

```bash
cat ~/.bashrc
```

**Comment by burgosibarra** [comment]
El resultado en git bash es:
cat: /c/Users/Nicolas/.bashrc: No such file or directory

**Comment by daleal** [comment]
No sabría decirte por qué está tan lento tu Git Bash. También encontré la solución de desactivar el hardware AMD, pero tampoco entiendo por qué podría estar causando lentitud en tu terminal. Mi recomendación sería usar wsl2, que te dará una experiencia de desarrollo similar (y probablemente mejor) a usar el bash de git.
