### ISSUE TITLE
[Ruby]- Lectura de Archivos

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#36]
Hola! Tengo una duda , lo que pasa es que al ejecutar el siguiente código, no me funciona no me arroja ningún error así que no comprendo el problema.
File.open("texto.txt","r").each do |line|
   if line == "lo mismo que dice la linea en el archivo"
       puts "leo esta linea"
   end
end
Esto si me lee el archivo "texto.txt " en cuestión, sin embargo, nunca entra al if y no se la razón

**Comment by johnowenatala** [comment]
Hola,

Puedes probar haciendo un `puts line.inspect` para cada línea, para asegurarte que lee todo el archivo y que las líneas tienen lo que esperas que tengan (y asegurarte que tu comparación == es correcta)

**Comment by RonaldoSosa** [comment]
Con esologre encontrar el error ! Muchas gracias !!!! :)
