### ISSUE TITLE
Problema instalación maquina virtual

### ISSUE THREAD

**Issue by Francisco5674** [IIC2143-2020-2/syllabus#37]
![image](https://user-images.githubusercontent.com/61996440/90807418-761d1c80-e2ec-11ea-9ca7-4a540c7fc49b.png)
Instale la maquina virtual siguiendo los pasos de la guía que mandaron pero en la parte 3 paso 5 me pasa lo de la imagen, no se que onda.

**Comment by johnowenatala** [comment]
Hola Francisco,

Primero que todo, debes aprender a googlear estos errores. Yo busqué esto:
virtualbox vt-x is disabled in the bios for all cpu modes

y encontré esta posible solución (vale la pena que lo intentes y nos cuentes si te sirve):

In Virtual Box "Settings" > System Settings > Processor > Enable the PAE/NX option. It resolved my issue.

**Comment by Francisco5674** [comment]
Hola 

Ya pude resolver el problema, y si, se googlear, gracias de todas formas por el consejo, comparto esto principalmente por aquí para que otros que tengan el mismo problema lo solucionen buscando en las Issues del curso. Si alguien mas tiene este mismo problema sobre Hyper virtualization, deben entrar al Bios del equipo que estén utilizando y activarla manualmente para poder configurar Virtual Box, es decir, es un problema de la configuración predeterminada del Hardware, depende del proce y el Bios que usen si tendrán o no este mensaje de error, al parecer los Intel de 10° generación están con el Hyper V desactivado por defecto en las Bios Asus, como en mi caso que tengo un i5 10400 por ende debería pasar lo mismo para cualquier intel 10000 en las placas Asus.

***Igual depende de la Bios que los reconozca, no para todos es igual.

*** Aquí dejo un vídeo medio rancio que me encontré, pero que me ayudo a solucionar el problema, si es que alguien quiere ver que onda:
https://www.youtube.com/watch?v=u0AWnCr80Ws

Saludos a los K
¡Gracias por la ayuda!
