### ISSUE TITLE
Tarea 1 - Duda Output

### ISSUE THREAD

**Issue by gachondoj** [IIC2143-2020-2/syllabus#38]
Hola, queria saber si el archivo de output se tiene que reiniciar cada vez que se corra el programa

Gracias

**Comment by jerosalazar** [comment]
Sí. Es importante que cada vez que corran el programa el archivo de output empiece vacío. De no hacerlo, si corres el programa multiples veces el archivo de output ne sería el esperado (ya que tendría el output repetido multiples veces)
