### ISSUE TITLE
[Tarea]-Instrucciones recibidas

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#39]
Hola!El archivo instructions.txt siempre va a tener cinco lineas?O puede ser algo como :
aprobados
reprobados
proyecto
top_grupos
top_ayudante
proyecto
top_ayudante
Además solo para asegurarme el orden en el que vengan esas líneas va a variar verdad?

**Comment by meretamal** [comment]
Hola 😁 

El archivo de instrucciones puede llegar en cualquier orden, se pueden repetir métodos y pueden faltar métodos, tal como se indica en el enunciado.

**Comment by RonaldoSosa** [comment]
Entendido!Gracias!!!
