### ISSUE TITLE
Problema al correr código ruby en VSC

### ISSUE THREAD

**Issue by vsantelicest** [IIC2143-2020-2/syllabus#4]
Hola! tengo un problema al correr cualquier tipo de código .rb en Visual Studio Code. Instalé el ruby on rails siguiendo este tutorial "https://gorails.com/setup/windows/10#ruby-rbenv", y me funcionó perfecto. Luego, en VSC, instalé todas las extensiones recomendadas (Code Runner, Ruby, Ruby on Rails, VSCode Ruby) y aún así, al correr un código sumamente simple, me dice lo siguiente: 
[Running] ruby "c:\code\1.rb"
"ruby" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

[Done] exited with code=1 in 0.121 seconds
Alguna idea de que es lo qu epodría estar fallando o que paso me faltó para completar la instalación ocrrectamente?

**Comment by jerosalazar** [comment]
En donde estas corriendo el programa (en la consola de vscode, en un terminal aparte, etc)?. Dime también que te dice si corres `ruby -v`

**Comment by vsantelicest** [comment]
El programa lo estoy corriendo en la misma consola de vscode y al correr ruby -v en el ubuntu 18, me dice:
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
Al hacerlo en el cmd de windows me dice:
"ruby" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by daleal** [comment]
Hola! Creo que lo que está pasando es que vscode está usando el terminal de Windows en vez de Ubuntu para ejecutar los comandos que le pides. Puedes ver que tienes todas tus herramientas de desarrollo en Ubuntu y no en Windows, por lo que debes usar el otro terminal. Puedes leer desde las intuiciones básicas del tema hasta un paso a paso de cómo desarrollar usando wsl + vscode en [esta guía](https://code.visualstudio.com/docs/remote/wsl-tutorial)

**Comment by vsantelicest** [comment]
Toda la razón, ese debería ser el problema. Ahora seguí todos los pasos del link pero surgió un problema con las extensiones: me dice que Ruby on Rails y vscode ruby estan "enabled locally and disabled on WSL Ubuntu 18". Como puedo resolver esto? Porque al correr cualquier código me sigue saliendo lo que puse en el mensaje inicial.

**Comment by daleal** [comment]
Probablemente tendrás que reinstalar esas extensiones con la conexión a wsl activada. `vscode` instala automáticamente las extensiones donde deban ir (las extensiones que afectan a la UI van en Windows y las que necesitan acceso a herramientas como `ruby` van en Ubuntu), pero probablemente instalaste las extensiones antes de tener hecha la conexión, por lo que `vscode` no sabía que debía instalar las extensiones en Ubuntu. Ahora que ya tienes hecha la conexión, reinstala esas extensiones y dime cómo te va

**Comment by vsantelicest** [comment]
Si te entiendo perfecto, pero ahora desinstalé las extensiones y las volví a instalar y no hubo cambios, me sigue diciendo que esta disabled para WSL

**Comment by vsantelicest** [comment]
Ahora al correr un código que dice puts "hola" me da el siguiente output:
[Running] ruby "/home/vsantelicest/helloWorld/1.rb"
hola

[Done] exited with code=0 in 0.851 seconds
No se si eso está bien o debería aparecer solo el puts

**Comment by jerosalazar** [comment]
Eso está bien, el resto solo son mensajes extra
