### ISSUE TITLE
Problema paso 5

### ISSUE THREAD

**Issue by Witomi** [IIC2143-2020-2/syllabus#42]
Hola!

Estoy en Windows trabajando con WSL (WSL1). Resulta que en el paso 5 cuando ejecuto "gem install rails -v 5.2.4" me imprime:
![image](https://user-images.githubusercontent.com/48265428/90947816-e4560200-e406-11ea-94b6-b246e570143a.png)

Busqué, y una opción podría ser que hubiese un problema para acceder a internet, por lo que intente ejecutar el comando "ping google.com" para identificar si podía este ser un problema, el cual se queda ejecutando eternamente hasta que lo paro con CTRL+C, con lo cual me imprime:
![image](https://user-images.githubusercontent.com/48265428/90947989-5bd86100-e408-11ea-94c6-5aa4eff1d6ad.png)

Sin embargo, cuando ejecuto este comando en el cmd sin entrar al WSL me imprime:
![image](https://user-images.githubusercontent.com/48265428/90948001-727eb800-e408-11ea-9c94-a6cc5794baaf.png)

 Y si ya llegue hasta ese paso no entiendo por qué no tendría internet el WSL, ni cómo poder arreglarlo.

Cualquier ayuda me serviría mucho, gracias!!

**Comment by Camila-sty** [comment]
@Witomi hola, pudiste resolver ese problema?

**Comment by Witomi** [comment]
Nope, alfinal me pude conseguir cambiar de computador para correr bien rails, pero gracias igual!
