### ISSUE TITLE
Problema Paso 11

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#43]
Hola! Al ejecutar el Paso 11 de la ayudantía , me refiero a : rails db:create me aparece el siguiente error:
![Captura de pantalla (22)](https://user-images.githubusercontent.com/62029138/90945894-e6fc2b80-e3f5-11ea-83ba-b80a6c0d1f46.png)

**Comment by oscars810** [comment]
Hola! :smile: 

Intenta correr `sudo systemctl status postgresql` para ver si efectivamente está corriendo postgres.
Tambien descarga `pgadmin` para administrar postgres con una interfaz que es mucho más comodo.

**Comment by RonaldoSosa** [comment]
Hola !!! AL correr sudo systemctl status postgresql luego de correr rails db:create , me apar ec lo siguiente 
![Captura de pantalla (31)](https://user-images.githubusercontent.com/62029138/90986403-9baa6000-e550-11ea-927e-ae93bab94e04.png)
Esto significa de que no lo esta corriendo ? Si es asi es extraño ya que previo a correr rails db:create , hice sudo service postgresql start y me apareció que:
![Captura de pantalla (32)](https://user-images.githubusercontent.com/62029138/90986459-f0e67180-e550-11ea-9c07-54fc1b151867.png)

**Comment by oscars810** [comment]
No, no quiere decir que no esté corriendo, solo quería probar otro comando para asegurarme.

Podrías enviarme un screenshot de tu archivo `database.yml` que se encuentra en la carpeta config del proyecto.

**Comment by RonaldoSosa** [comment]
![Captura de pantalla (33)](https://user-images.githubusercontent.com/62029138/90988603-0e700700-e562-11ea-828c-502ee74fcd4e.png)

**Comment by RonaldoSosa** [comment]
![Captura de pantalla (34)](https://user-images.githubusercontent.com/62029138/90988622-352e3d80-e562-11ea-9f2b-3e7b7974e723.png)

**Comment by johnowenatala** [comment]
En el encoding, prueba con utf-8 en lugar de unicode

**Comment by cirey1** [comment]
Hola Ronaldo, 

Tu problema se ve en que no se esta tomando la codificación correcta para tu base de datos de rails. Para solucionarlo debes agregar al archivo ./database.yml la siguiente linea dentro de default.

```
template: template0
```

Por lo tanto, la parte default de tu archivo de configuracion deberia tener un formato asi.
```
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: <la clave que pusiste en el paso 7>
  pool: 5
  template: template0
```

Posterior al cambio, tienes que correr nuevamente

```
rails db:create
rails server
```

Ojala te sirva!

Referencia:
https://gist.github.com/amolkhanorkar/8706915

**Comment by RonaldoSosa** [comment]
Siii :´´) me funcionó , muchas gracias !!!!
