### ISSUE TITLE
Fechas Evaluaciones

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2143-2020-2/syllabus#49]
Hola! Quería saber si en alguna parte están las fechas de las entregas y evaluaciones del curso, porque no las encontré :( y si no están, alguien podría darmelas? Gracias 😄

**Comment by daleal** [comment]
Solamente para dejarlo todo explícito en un solo lugar, les dejo [el link al calendario de Google](https://calendar.google.com/calendar?cid=dWMuY2xfODVhdWx1cmRjYW5raGkyN3Nua3NnZGhpNjhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ). En el anuncio sobre el calendario pueden encontrar también un `iframe` con las fechas, por si no quieren tener que agregar el calendario del curso a sus calendarios.
