### ISSUE TITLE
Método top_grupos

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2143-2020-2/syllabus#5]
¡Hola! 💎 

Respecto al método ```top_grupos()``` (pág 3), dice que estos irán ordenados según id, pero no sale si es de menor a mayor. ¿Cómo será el orden? 

Gracias y que estén muy bien 😸

**Comment by meretamal** [comment]
Hola. 😁 , debería ser de menor a mayor!! Muchas gracias!!

**Comment by daleal** [comment]
Dejaré esta _issue_ abierta ya que lo más probable es que más gente tenga la misma duda y así será más fácil que la encuentren. Disculpen el detalle! 🐳
