### ISSUE TITLE
Línea vacía al final de output.txt

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2143-2020-2/syllabus#53]
Hola!
Mi archivo **output.txt** es exactamente igual al dado de ejemplo, pero en el mío tengo una línea vacía al final (porque como uso puts, la última linea inserta un salto de línea pero no hay nada después).
¿Es relevante? ¿Y en el caso de serlo, cómo podría solucionarlo?

**Comment by meretamal** [comment]
#52
