### ISSUE TITLE
problema paso 12 Mac

### ISSUE THREAD

**Issue by kmhaller** [IIC2143-2020-2/syllabus#54]
Hola, me pasa que al correr "rails server" me aparece lo siguiente:
----------------------------------------------------------------
MacBook-Air-de-Mathias:proy_soft mathiashaller$ rails server
=> Booting Puma
=> Rails 5.2.4.3 application starting in development 
=> Run `rails server -h` for more startup options
/Users/mathiashaller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/mathiashaller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:111: warning: The called method `initialize' is defined here
Puma starting in single mode...
* Version 3.12.6 (ruby 2.7.0-p0), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop

---------------------------------------------
y si trato de meterme a  http://localhost:3000/ me aparece una página con una franja roja arriba 
que dice:
ActiveRecord::NoDatabaseError
FATAL: role "postgres" does not exist

Busque algunas soluciones y se supone que tengo que cambiar al superuser de la base de datos,
pero no me quedo muy claro. ¿Cómo lo arreglo?
gracias!

**Comment by johnowenatala** [comment]
Tu aplicación no se está pudiendo conectar a tu base de datos.
¿tienes bien configurado el archivo database.yml? Ahí debieras tener un usuario y contraseña para que tu aplicación se conecte a la BD (que tienes que haber creado previamente en posgres).

**Comment by johnowenatala** [comment]
A todo esto, ¿cómo instalaste postgresql?

**Comment by daleal** [comment]
Me podrías decir cual es el _output_ del comando `rails db:create` por favor?

**Comment by kmhaller** [comment]
Sí, tengo bien configurado el archivo database.yml, está igual que como lo vieron en la ayudantía.

No me acuerdo muy bien cómo lo instale, me acuerdo que lo tenía instalado para bases de datos y
ahora lo borre y lo volvi a instalar con esta página: https://medium.com/@bitadj/completely-uninstall-and-reinstall-psql-on-osx-551390904b86. 
Eso si, el comando "rm -rf .psql_history .psqlrc .psql.local .pgpass .psqlrc.local" me tiro  un error y no funcionó.

El output de rails db:create es el siguiente:
Usage:
  rails new APP_PATH [options]

Options:
      [--skip-namespace], [--no-skip-namespace]            # Skip namespace (affects only isolated applications)
  -r, [--ruby=PATH]                                        # Path to the Ruby binary of your choice
                                                           # Default: /Users/mathiashaller/.rbenv/versions/2.7.0/bin/ruby
  -m, [--template=TEMPLATE]                                # Path to some application template (can be a filesystem path or URL)
  -d, [--database=DATABASE]                                # Preconfigure for selected database (options: mysql/postgresql/sqlite3/oracle/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                           # Default: sqlite3
      [--skip-yarn], [--no-skip-yarn]                      # Don't use Yarn for managing JavaScript dependencies
      [--skip-gemfile], [--no-skip-gemfile]                # Don't create a Gemfile
  -G, [--skip-git], [--no-skip-git]                        # Skip .gitignore file
      [--skip-keeps], [--no-skip-keeps]                    # Skip source control .keep files
  -M, [--skip-action-mailer], [--no-skip-action-mailer]    # Skip Action Mailer files
  -O, [--skip-active-record], [--no-skip-active-record]    # Skip Active Record files
      [--skip-active-storage], [--no-skip-active-storage]  # Skip Active Storage files
  -P, [--skip-puma], [--no-skip-puma]                      # Skip Puma related files
  -C, [--skip-action-cable], [--no-skip-action-cable]      # Skip Action Cable files
  -S, [--skip-sprockets], [--no-skip-sprockets]            # Skip Sprockets files
      [--skip-spring], [--no-skip-spring]                  # Don't install Spring application preloader
      [--skip-listen], [--no-skip-listen]                  # Don't generate configuration that depends on the listen gem
      [--skip-coffee], [--no-skip-coffee]                  # Don't use CoffeeScript
  -J, [--skip-javascript], [--no-skip-javascript]          # Skip JavaScript files
      [--skip-turbolinks], [--no-skip-turbolinks]          # Skip turbolinks gem
  -T, [--skip-test], [--no-skip-test]                      # Skip test files
      [--skip-system-test], [--no-skip-system-test]        # Skip system test files
      [--skip-bootsnap], [--no-skip-bootsnap]              # Skip bootsnap gem
      [--dev], [--no-dev]                                  # Setup the application with Gemfile pointing to your Rails checkout
      [--edge], [--no-edge]                                # Setup the application with Gemfile pointing to Rails repository
      [--rc=RC]                                            # Path to file containing extra configuration options for rails command
      [--no-rc], [--no-no-rc]                              # Skip loading of extra configuration options from .railsrc file
      [--api], [--no-api]                                  # Preconfigure smaller stack for API only apps
  -B, [--skip-bundle], [--no-skip-bundle]                  # Don't run bundle install
      [--webpack=WEBPACK]                                  # Preconfigure for app-like JavaScript with Webpack (options: react/vue/angular/elm/stimulus)

Runtime options:
  -f, [--force]                    # Overwrite files that already exist
  -p, [--pretend], [--no-pretend]  # Run but do not make any changes
  -q, [--quiet], [--no-quiet]      # Suppress status output
  -s, [--skip], [--no-skip]        # Skip files that already exist

Rails options:
  -h, [--help], [--no-help]        # Show this help message and quit
  -v, [--version], [--no-version]  # Show Rails version number and quit

Description:
    The 'rails new' command creates a new Rails application with a default
    directory structure and configuration at the path you specify.

    You can specify extra command-line arguments to be used every time
    'rails new' runs in the .railsrc configuration file in your home directory.

    Note that the arguments specified in the .railsrc file don't affect the
    defaults values shown above in this help message.

Example:
    rails new ~/Code/Ruby/weblog

    This generates a skeletal Rails installation in ~/Code/Ruby/weblog.

**Comment by johnowenatala** [comment]
Prueba lo siguiente:
1. Ve si te puedes conectar a la BD directamente en consola. Yo lo hago así:
<img width="175" alt="Screen Shot 2020-08-24 at 17 49 34" src="https://user-images.githubusercontent.com/4601442/91099951-3dee4480-e632-11ea-913c-5317bc4896c5.png">

2. Te comparto mi archivo database.yml . Este es el archivo por defecto que crea el proyecto, lo único que tuve que cambiar fue ponerle mi usuario y contraseña (que es mi usuario de macos y como contraseña vacío)

[https://github.com/johnowenatala/iic2143_2020_2_rails_e1/blob/master/config/database.yml](https://github.com/johnowenatala/iic2143_2020_2_rails_e1/blob/master/config/database.yml)

**Comment by kmhaller** [comment]
Osea de username pongo: mathiashaller (que es el de macos) en vez de postgres?

**Comment by johnowenatala** [comment]
Se supone que en macos postgres se instala así por defecto. Prueba y si no te funciona no es así (no me acuerdo si venía así o yo lo cambié, porque instalé postgres hace muuuuuuuuucho tiempo)

**Comment by kmhaller** [comment]
hola, me funcionó cambiando el user por el de mi usuario en mac en el archivo "database.yml".
Ahora cambie el superuser a postgres con estos comandos que dieron en la ayudantía:

create user postgres with encrypted password 'contraseña';

alter user postgres with superuser;

gracias
