### ISSUE TITLE
Duda output 

### ISSUE THREAD

**Issue by mjespinoza** [IIC2143-2020-2/syllabus#55]
Holaa, tengo dos dudas:
1. el archivo output siempre será txt o el formato puede variar?
2. El formato de escritura de este archivo con respecto a los id es:
    {id 1} {nombre} etc
           o 
    {1} {nombre} etc 
Gracias de antemano!!

**Comment by meretamal** [comment]
Hola 😁 

En torno a la primera pregunta, el formato de output siempre debe ser txt.

En torno a la segunda, ¿está preguntando si los ids siempre van a partir del 1? Si es eso, los ids pueden variar y no necesariamente estar en orden.

**Comment by mjespinoza** [comment]
me refería a la escritura, osea si es que cada vez que se tenga que poner el id se deba anteponer la palabra id y luego el numero o solo colocar el numero en los corchetes

**Comment by meretamal** [comment]
Se debe poner solo el valor del id. Puedes revisar los _test files_ que subimos 😉
