### ISSUE TITLE
Error en el paso 3

### ISSUE THREAD

**Issue by javierzagal** [IIC2143-2020-2/syllabus#56]
Hola he estado siguiendo el tutorial que tienen en la carpeta ayudantia 2, aunque la verdad sin entender nada de lo que estoy haciendo, ahora en el paso me sale este error:
![imagen](https://user-images.githubusercontent.com/53867633/90993550-53586580-e583-11ea-89f6-15ba1f6b706a.png)
y si lo intento nuevamente me dice:
![imagen](https://user-images.githubusercontent.com/53867633/90993617-8d296c00-e583-11ea-97b0-23ab755a01cf.png)
Alguien tiene alguna idea de que puedo hacer?

**Comment by Gaonuk** [comment]
No importa! Yo tuve el mismo error y el resto de los pasos deberian funcionar!

**Comment by javierzagal** [comment]
Gracias! si me funcionó el siguiente comando, y en teoría debería instalarme el rvm, pero cuando llego al paso 5 no me reconocía el comando, aunque esto me funcionó por si alguien vé esto y tiene el mismo problema: 
https://stackoverflow.com/questions/39643791/no-command-rvm-found-but-there-are-20-similar-ones
(
    sudo apt-get install curl
    curl -L https://get.rvm.io | bash -s stable
    source ~/.rvm/scripts/rvm
    rvm requirements
)
