### ISSUE TITLE
Error: "could not connect to server: No such file or directory"

### ISSUE THREAD

**Issue by javierzagal** [IIC2143-2020-2/syllabus#59]
Hola, al llegar al paso 7 no logro conectarme al servidor, alguien sabe que hacer en este caso? De antemano muchas gracias!
![imagen](https://user-images.githubusercontent.com/53867633/91005933-20739900-e5a6-11ea-8c82-7f11df6bbb49.png)

**Comment by daleal** [comment]
Hola! Probablemente no está corriendo el servidor de PostgreSQL. Puedes iniciarlo ejecutando `sudo service postgresql start`
