### ISSUE TITLE
agregar atributos no enunciados

### ISSUE THREAD

**Issue by teverde** [IIC2143-2020-2/syllabus#6]
No hay problema si agrego un atributo más allá de lo que dicta el enunciado?
Por ejemplo, si a la clase Grupos le diera como atributo sus integrantes en vez de hacerlo en una array aparte

**Comment by meretamal** [comment]
Hola 😁 , puede agregar más atributos o métodos si es que lo estimas conveniente, sin embargo, deben estar presentes los atributos que se mencionan en el enunciado
