### ISSUE TITLE
Tarea 1 - Duda output

### ISSUE THREAD

**Issue by MGome** [IIC2143-2020-2/syllabus#62]
Hola buenas, 
Se considera erróneo un output si al final del todo tiene un salto de línea extra? (imagen a continuación)
![image](https://user-images.githubusercontent.com/48321270/91064092-d1a51e00-e5fc-11ea-8bff-18e848cf491b.png)

Cabe señalar que todas las líneas son correctas de acuerdo al archivo de instrucciones, sólo tiene esa diferencia con el output de ejemplo que se entregó.

**Comment by lisraelrat1** [comment]
Hola! Te dejo un segmento de las instrucciones de la tarea en donde se especifica porqué debe ser exactamente igual a lo pedido. 
<img width="644" alt="Captura de Pantalla 2020-08-24 a la(s) 12 06 56" src="https://user-images.githubusercontent.com/52945060/91068451-4fb7f380-e602-11ea-8471-cc32ad11d80d.png">
De todas maneras estás super cerca, ánimo y ojalá te salga!

**Comment by meretamal** [comment]
Hola 😁 

En teoría, con o sin esa línea, la parte importante del _output_ está buena, por lo que, si es que crees que te viste afectado por algún tema de formato, habrá una instancia para mandar a recorregir 😉 .
