### ISSUE TITLE
Error paso 12

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2143-2020-2/syllabus#65]
Hola! Hice todos los pasos bien hasta el 12. Cuando ejecuté el último *rails server* (en wsl, windows) creo que salió bien también con esto:

![image](https://user-images.githubusercontent.com/62080216/91098131-ebf7ef80-e62e-11ea-88eb-7c07b3ddd046.png)

Pero cuando me metí al link * http://localhost:3000/ * no se me cargó nunca, entonces cerré el terminal y ahora cuando  traté de ejecutarlo denuevo sale

![image](https://user-images.githubusercontent.com/62080216/91098378-590b8500-e62f-11ea-8dbb-e49972bc9a01.png)

**Comment by daleal** [comment]
Hola! Eso a veces ocurre con Rails. Para solucionar ese error, elimina el archivo `server.pid` ubicado en `tmp/pids` dentro de tu proyecto. Luego de eso, podrás volver a levantar el servidor. Dime si al intentarlo nuevamente se carga `localhost:3000`

**Comment by jirarrazaval** [comment]
Gracias! Pero lo hice y ahora cuando apreto el link me aparece esto
![image](https://user-images.githubusercontent.com/62080216/91111953-d3e49800-e64f-11ea-9283-c31d0358783d.png)

**Comment by daleal** [comment]
Dado que el problema original fue resuelto, te pediré que hagas otra issue para este nuevo problema y cerraré esta issue.

**Comment by daleal** [comment]
(En todo caso, probablemente podrás resolver tu error con la misma solución que #59)

**Comment by jirarrazaval** [comment]
sÍ lo solucioné gracias!
