### ISSUE TITLE
Ayudantia 2 paso 8

### ISSUE THREAD

**Issue by mjespinoza** [IIC2143-2020-2/syllabus#66]
Holaa, al ejecutar el comando _bundle install_ me sale el siguiente error y no se como solucionarlo :c Estoy usando wsl por si acaso.
![error_paso8](https://user-images.githubusercontent.com/42595117/91107686-db05a900-e643-11ea-97a3-9cef8113a5fb.JPG)

Gracias de antemano!

**Comment by johnowenatala** [comment]
No es importante el error que tienes, porque está tratando de instalar rails 4.x (es un tema con la versión isntalada de bundler vs la que necesita el proyecto).

Debes usar rails 5.2.4.

**Comment by daleal** [comment]
Podrías enviar el contenido de tu `Gemfile` por favor?

**Comment by mjespinoza** [comment]
Aquí esta el contenido del Gemfile, encuentro raro que aparezca rails 4.2.10. 
pd: Perdon por responder tan tarde

source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.10'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '>= 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

**Comment by mjespinoza** [comment]
otra cosaa cuando ejecuto rails -v dentro del proyecto aparece lo siguiente 
![error](https://user-images.githubusercontent.com/42595117/91239192-dc4ed880-e70c-11ea-829d-f9bb5cb1a01f.JPG)

**Comment by johnowenatala** [comment]
Si, eso es normal.
Insisto, no le des mas vueltas. Borra esa carpeta, instala la version correcta de rails con 
gem install rails -v 5.2.4
Y luego crea un nuevo proyecto con rails 5.
Si ejecutas rails -v luego de instalar rails 5.2.4, y te sigue diciendo rails 4.x, puedes forzar la version de rails con esto:
rails _5.2.4_ - v
Y lo mismo al crear el proyecto:
rails _5.2.4_ new ...

**Comment by mjespinoza** [comment]
ya me funciono, muchas gracias!! :D
