### ISSUE TITLE
Ubicación del archivo "instructions.txt"

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#67]
Hola 😄 
Tengo una duda con respecto a lo que sale en el siguiente párrafo:
![image](https://user-images.githubusercontent.com/59337116/91108963-895f1d80-e647-11ea-9b9a-0abb3bb55cea.png)
Mencionan que los archivos "TXT" deben estar dentro de la carpeta ```data```. Pero luego en el ejemplo de cómo deberían verse en el repositorio, el archivo ```instructions.txt``` sale fuera de la carpeta ```data```. 
Lo estoy leyendo mal quizás, pero para confirmar mi duda, dónde debería estar el archivo ```instructions.txt``` ?

**Comment by jerosalazar** [comment]
Hola, como se explica en la sección de archivos csv + txt, los archivos de datos (extensión csv) van dentro de la carpeta data. Mientras que los archivos txt (instrucciones y output) van el el directorio principal

**Comment by Camila-sty** [comment]
Ok. Gracias!!!
