### ISSUE TITLE
Instalación Ruby MacOS

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2143-2020-2/syllabus#68]
Hola! Estaba siguiendo los pasos de IntroRuby.pdf para instalarlo y al intentar el paso uno de la instalación de RVM me tira error diciendo gpg2: command not found, pero si lo instalé. Ayuda qué puedo hacer, he buscado en internet y las soluciones no me han servido :(

**Comment by jerosalazar** [comment]
Hola! te sale algo si escribes `rvm -v`?

**Comment by beatrizacuna** [comment]
me sale command not found también, pero ceo que es porque me quede pegada en el primer paso y no pude seguir
![Captura de pantalla 2020-08-25 a la(s) 16 30 14](https://user-images.githubusercontent.com/48481963/91224634-66d50f00-e6f0-11ea-9f70-1814307a0e37.png)

**Comment by Gaonuk** [comment]
Para instalar gpg2 utilizaste `brew install gpg2`??

**Comment by beatrizacuna** [comment]
siii, igual de pava puse brew install ruby, será eso?

**Comment by Gaonuk** [comment]
No para nada! Prueba usar este comando `gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB` a ver si soluciona el error de `gpg2: command not found`.

ref: https://stackoverflow.com/questions/54391696/gpg2-command-not-found-even-when-gpg2-is-installed-on-mac-trying-to-install-rv

**Comment by beatrizacuna** [comment]
al ejecutar eso me sale no route to host, y aun me sale command not found al ejecutar gpg2 :(

**Comment by Gaonuk** [comment]
Mmmm.. Podrias probar usando otro server de las keys. `gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
`

**Comment by beatrizacuna** [comment]
siii pude con lo primero que pusiste, muchas gracias!!! 😄

**Comment by Gaonuk** [comment]
Fantastico!
