### ISSUE TITLE
ARGV 

### ISSUE THREAD

**Issue by mserranob** [IIC2143-2020-2/syllabus#69]
Para la corrección de la T1 el comando a correr va a ser `ruby main.rb data instr.txt output.txt` o `ruby main.rb data instructions.txt output.txt` que la carpeta de las instrucciones viene guardada como instructions.txt en los test_files/
Gracias.

**Comment by jerosalazar** [comment]
Hola, podrías reformular tu pregunta? no la entendí muy bien

**Comment by mserranob** [comment]
En el enunciado en la parte de ejecución sale:
![image](https://user-images.githubusercontent.com/53835473/91183781-df6ca900-e6b9-11ea-9bc5-d5fde6118a44.png)
Pero las instrucciones estan guardadas como instructions.txt en los testfiles y quería confirmar si esa sería la linea a correr en la corrección o sería `ruby main.rb data instructions.txt output.txt`

**Comment by jerosalazar** [comment]
El nombre del archivo no es relevante. Lo importante es que cuando se corra el programa, luego de `ruby main.rb` el primer argumento será la carpeta de los archivos csv, el segundo el nombre del archivo con las instrucciones y el tercero el nombre del archivo donde se enviará el output

**Comment by mserranob** [comment]
perfect, gracias
