### ISSUE TITLE
Ejecución de la tarea

### ISSUE THREAD

**Issue by Baelfire18** [IIC2143-2020-2/syllabus#7]
Hola creo que entendi como ejecutar la tarea, pero a la hora de hacerlo me tira error
![image](https://user-images.githubusercontent.com/50716449/90321724-55367f00-df1a-11ea-8699-499e93bc3838.png)
(por si acaso cree un archivo zzz.txt para no sobre escirbir aún el output pedido)

Y otra cosa se recibe el input con un `gets ` o un `ARGV`

**Comment by jerosalazar** [comment]
Hola, los argumentos que le pasas al programa deben ir sin los brackets. Por ejemplo `ruby main.rb data_folder instrucciones.txt output.txt`

**Comment by Baelfire18** [comment]
Gracias otra pregunta a la hora de ejecutar las instruciones de instruciones.txt, se puede hacer con eval()?

**Comment by jerosalazar** [comment]
Se puede, pero no lo recomiendo (imagínate ponemos una instrucción maliciosa 😨 ) te recomendaría mejor buscar cómo funciona el _case statement_
