### ISSUE TITLE
No me corre localhost, pero si el codigo rails server

### ISSUE THREAD

**Issue by mgnavarrete** [IIC2143-2020-2/syllabus#70]
Seguí todos los pasos de la ayudantía y cuando tiro el código `rails server`, según yo me funciona bien, pero no me corre el localhost.

![Prube 1](https://user-images.githubusercontent.com/30879824/91125197-24b7b900-e66f-11ea-8c00-9954362ef1c9.JPG)

**Comment by jerosalazar** [comment]
Hola. Ese mensaje indica que la aplicación debería estar corriendo en localhost:3000/ puedes revisar si efectivamente corre o que error te indica?

**Comment by mgnavarrete** [comment]
me meto al local host y me aparece esto
![Uploading asdsdfsdsdfsdfsfdsfadsdafsdfsdasdaf.JPG…]()

**Comment by mgnavarrete** [comment]
En el localhost me aparece:

No se puede acceder a este 
sitiolocalhost rechazó la conexión.

**Comment by cchauriye** [comment]
Hola! Puedes mandar un screenshot de lo que te sale en localhost?

**Comment by mgnavarrete** [comment]
No me deja subir una imagen, pero ahi esta

https://imgur.com/RIWsLMz

**Comment by mgnavarrete** [comment]
Hice todo lo de la ayudantia denuevo y me sigue pasando lo mismo

![image](https://user-images.githubusercontent.com/30879824/91199906-7e9a9c00-e6cc-11ea-8ac7-f1efff2761ae.png)

![image](https://user-images.githubusercontent.com/30879824/91200008-996d1080-e6cc-11ea-97c9-0682aa0b636c.png)

**Comment by cchauriye** [comment]
En qué carpeta estás corriendo rails s?

**Comment by mgnavarrete** [comment]
en la del proyecto

**Comment by Gaonuk** [comment]
Podrias probar hacerlo en otro puerto? `rails s -p 3001`

**Comment by cirey1** [comment]
Hola, creo que tienes un problema de routing. La solución que hay, dado el problema de routing, es ir al archivo database.yml y cambiar en host a 127.0.0.1, tu sección default del archivo debería quedar algo asi.

```
default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: <la clave que pusiste en el paso 7>
  pool: 5
```

Esto debería arreglar tu problema, ahora si te diriges a http://localhost:3000/ debería aparecerte la pagina de rails.

Referencia:
https://stackoverflow.com/questions/13394238/rails-server-is-running-but-cannot-connect-to-localhost3000

**Comment by mgnavarrete** [comment]
Alfinal elimine ubuntu, volvi a instalar todo de nuevo y ahora me funciona todo bien.
Gracias igual a todos.
