### ISSUE TITLE
Diferencia entre output.txt

### ISSUE THREAD

**Issue by MINGOD24** [IIC2143-2020-2/syllabus#73]
Hola, 

Termine de programar la tarea y al correrla y compararla a simple ojo con el output.txt original se ve igual, pero al hacer diff entre ambos archivos me sale que todas las lineas estas distintas. Alguien sabe que puedo hacer? La primera foto es el output original y la segunda es el ouput mio.
![image](https://user-images.githubusercontent.com/62083817/91245715-25f2ef80-e71c-11ea-91ae-6bfe88edf59d.png)
![image](https://user-images.githubusercontent.com/62083817/91245754-3f943700-e71c-11ea-9a5a-7a87f94fef34.png)

**Comment by jerosalazar** [comment]
Hola! Podrias revisar alguna pagina que compare texto (como [esta](https://text-compare.com/)) para asegurarte que tu output esté correcto

**Comment by MINGOD24** [comment]
Me aparece igual. Que hago?

**Comment by jerosalazar** [comment]
Que estas haciendo para comparar los archivos que dices que sale distinto? Si el contenido de los archivos es el mismo, estás bien

**Comment by daleal** [comment]
Hola! Probablemente es por los _line endings_ (dado que en entornos UNIX funcionan distinto a como funcionan en entornos MS). Por favor, prueba corriendo `diff` con el _flag_ `--strip-trailing-cr`. Sería algo como así:

```bash
diff --strip-trailing-cr output.txt output_1.txt
```

**Comment by MINGOD24** [comment]
Respondo a ambos jajajaja

@jerosalazar diff output.txt output_1.txt, corro con ese codigo. Bacan!

@daleal Corriendo ese codigo me deja solo con la linea en blanco del final que lei que no era problema. Entonces me quedo tranquilo?

**Comment by daleal** [comment]
Si, no te preocupes! Nosotros usaremos ese flag para corregir todas las tareas.
