### ISSUE TITLE
Orden de los alumnos y ayudantes en los archivos.csv

### ISSUE THREAD

**Issue by JulioGalvez** [IIC2143-2020-2/syllabus#74]
Los archivos csv estarán siempre escritos según orden de id como se muestra en la imagen adjunta? o puede que aparezca primero el alumno por ejemplo con id 5 luego 1 etc?, gracias de antemano!

<img width="430" alt="Captura de pantalla 2020-08-26 a la(s) 16 20 49" src="https://user-images.githubusercontent.com/62029166/91352742-407aa680-e7b8-11ea-8d9e-5bbf036b4495.png">

**Comment by meretamal** [comment]
Hola 😁 

No necesariamente van a estar ordenados por id.
