### ISSUE TITLE
Error Paso 12 Mac

### ISSUE THREAD

**Issue by fplois** [IIC2143-2020-2/syllabus#75]
Hola, después de ejecutar todos los pasos de la ayudantía y revisar el localhost: 3000 me aparece lo siguiente:
![Captura de pantalla 2020-08-27 a la(s) 10 21 47 a  m](https://user-images.githubusercontent.com/48328108/91456256-0a3d3580-e851-11ea-9bed-69f2db871a7b.png)
Como puedo solucionar el error?
Saludos.

**Comment by meretamal** [comment]
Hola 😁 

Eso significa que la base de datos que estás intentado utilizar no existe.

Ejecutaste `rails db:create`?

**Comment by fplois** [comment]
si lo ejecute pero no se si esta bien hecho, de todas maneras obtengo el siguiente output :(

/Users/felipelois/.rvm/gems/ruby-2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/felipelois/.rvm/gems/ruby-2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:111: warning: The called method `initialize' is defined here
/Users/felipelois/.rvm/gems/ruby-2.7.0/gems/activerecord-5.2.4.3/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/felipelois/.rvm/gems/ruby-2.7.0/gems/activerecord-5.2.4.3/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
/Users/felipelois/.rvm/gems/ruby-2.7.0/gems/activemodel-5.2.4.3/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/felipelois/.rvm/gems/ruby-2.7.0/gems/activemodel-5.2.4.3/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
/Users/felipelois/.rvm/gems/ruby-2.7.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql/oid/specialized_string.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/felipelois/.rvm/gems/ruby-2.7.0/gems/activemodel-5.2.4.3/lib/active_model/type/value.rb:8: warning: The called

**Comment by Gaonuk** [comment]
Podrias mandar un screenshot de tu database.yml?

**Comment by fplois** [comment]
![Captura de pantalla 2020-08-27 a la(s) 5 39 11 p  m](https://user-images.githubusercontent.com/48328108/91497609-480b7f80-e88c-11ea-92f4-168a5c4c8480.png)

**Comment by Gaonuk** [comment]
Y cual es el nombre de la carpeta donde tienes tu app? Porque puede ser que tu problema es que el nombre de tu app es "NombreApp" pero en el database tienes lo que esta en la ayudantia, osea donde dice <nombre de tu app> eso lo tienes que reemplazar por el nombre de tu app.

**Comment by fplois** [comment]
La carpeta donde se encuentra la app se llama "teamdff" :(

**Comment by Gaonuk** [comment]
Ahi esta entonces el error, tienes que cambiar todo donde dice "\<nombre de tu app\>" por "teamdff" y eso deberia solucionar tu problema

**Comment by fplois** [comment]
No se que paso pero se arreglo, lo único diferente es que ahora cuando ejecuto la app de Postgres, se ve lo siguiente(antes no estaba):
![Captura de pantalla 2020-08-28 a la(s) 4 41 05 p  m](https://user-images.githubusercontent.com/48328108/91613335-51105580-e94d-11ea-9e85-cf4badfddfcc.png)

**Comment by fplois** [comment]
no cambie nada, todo lo que envié sigue igual, aun así debo cambiar los nombres de la app que aparecen en database.yml?

**Comment by Gaonuk** [comment]
Si te funciona no es necesario, pensaba que quizas las bases de datos se habian creado a nombre de tu app pero no lo pusiste en el database.yml, al final tienes bases de datos con ese nombre jajaja no cambia nada

**Comment by fplois** [comment]
Muchas gracias por toda la ayuda 👍  :)
