### ISSUE TITLE
Instalación rails

### ISSUE THREAD

**Issue by sgutgar** [IIC2143-2020-2/syllabus#76]
Hola, al instalar rails me dice que se instalo correctamente, pero luego para comprobar que esta con rails --version me dice que rails no esta instalado en el sistema. Me pasa lo mismo al tratar de usar rails new myapp.

**Comment by Gaonuk** [comment]
Te dice `rails: command not found`?

**Comment by sgutgar** [comment]
ya lo solucione, gracias
