### ISSUE TITLE
Ejecutar tarea

### ISSUE THREAD

**Issue by IvaniaArias** [IIC2143-2020-2/syllabus#77]
Holaa! Tengo dudas sobre como correr la tarea.
Dentro del main no tenemos que llamar a los metodos? Eso lo hace instrucciones?

Si ese es el caso, mis metodos son del tipo aprobados(lista_alumnos), como detecta lo que debe ocupar? :(
Gracias de antemano!

**Comment by meretamal** [comment]
Hola 😁 

No, tu código debe ejecutar los método que creaste.

El archivo de instrucciones está para que sepas cuáles son los métodos que deben ejecutarse y el orden en que deben hacerlo.

**Comment by IvaniaArias** [comment]
Perfectoo! Muchas graciaas
