### ISSUE TITLE
nombre carpeta

### ISSUE THREAD

**Issue by JoseAvanzada2019** [IIC2143-2020-2/syllabus#78]
al final el nombre de la carpeta es. data o datasets_folder ¿Cómo lo van a ejecutar?

**Comment by jerosalazar** [comment]
Hola! La idea es que el nombre de la carpeta de los datos se tome desde el terminal (al correr `ruby main.rb data instructions.txt output.txt`), así puedes ponerle el nombre que quieras a la carpeta (útil para cuando corrijamos)

**Comment by JoseAvanzada2019** [comment]
si caché, mala mía
