### ISSUE TITLE
Tarea: Ruby hash each

### ISSUE THREAD

**Issue by Baelfire18** [IIC2143-2020-2/syllabus#8]
Hola como hago un each (o loop en general) llamando al value de un HASH.
Por ejemplo tengo un hash con hartas cosas y quiero correrlo en un loop para revisar algo dentro de él.
Busque en stackoverflow y no me solucionaba lo que buscaba

**Comment by jerosalazar** [comment]
Hola! ve si [este link](https://riptutorial.com/ruby/example/5235/iterating-over-a-hash) te sirve. Recuerda buscar bien en internet si puedes encontrar tu pregunta antes de hacer una issue.
Ps: si soluciona tu problema, cierra la issue 😊

**Comment by Baelfire18** [comment]
Gracias!!
