### ISSUE TITLE
Ejecutar instrucciones

### ISSUE THREAD

**Issue by teverde** [IIC2143-2020-2/syllabus#80]
Si bien tengo claro como abrir y leer el archivo _instrucciones.txt_, no tengo claro como llevar eso a que se ejecute el método correspondiente al leerlo

**Comment by meretamal** [comment]
Hola 😁 

Por ejemplo, al leer la línea "top_grupos", sabes que se debe ejecutar el método top_grupos. Puedes usar hartas herramientas, como control de flujo o _case statements_, pero eso ya dependí de ti.

**Comment by teverde** [comment]
Muchas gracias. Con lo de _case statements_ me quedó clarísimo

**Comment by JoseAvanzada2019** [comment]
sobre los métodos, tengo que hacer literal una funcion o puedo escribir el código con control de flujo nomás?
