### ISSUE TITLE
[Error] Ayudantía Paso 10

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#81]
Hola! Cuando corro el comando sudo service postgresql start me aparece el siguiente error
![Captura de pantalla (58)](https://user-images.githubusercontent.com/62029138/91616524-de56a880-e953-11ea-85a3-4c59920caa83.png)
Esto es extraño ya que previamente no me había aparecido este error y había logrado completar los pasos en su totalidad.
Al revisar el puerto 5432, me aparece que esta ejecutanto postgres.exe , esto debería ser así? o no debería estar ejecutando esto?
![Captura de pantalla (59)](https://user-images.githubusercontent.com/62029138/91648114-9ad26c00-ea31-11ea-9055-8e669fba302b.png)
![Captura de pantalla (60)](https://user-images.githubusercontent.com/62029138/91648144-e7b64280-ea31-11ea-9f12-f41b7547b75c.png)

**Comment by Gaonuk** [comment]
Que pasa si tratas de entrar a la consola de postgres?

**Comment by RonaldoSosa** [comment]
Me aparece el siguiente mensaje:
![Captura de pantalla (61)](https://user-images.githubusercontent.com/62029138/91648698-9a899f00-ea38-11ea-83f4-3d56d02ab9dc.png)

**Comment by Gaonuk** [comment]
Este error al usar `sudo service postgresql start` lo sigues teniendo luego de haber apagado y encendido tu computador?

**Comment by RonaldoSosa** [comment]
:( si acabo de hacer eso ahora mismo y el error sigue.

**Comment by Gaonuk** [comment]
Mandame un mail a rodrigo.gaona@uc.cl
