### ISSUE TITLE
Paso 6 

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2143-2020-2/syllabus#83]
Hola! Para la parte 6 tengo un problema estoy ejecutando la primera linea y arroja lo siguiente:
```jaimecoloma@MacBook-Air-de-Jaime ~ % curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13527  100 13527    0     0  87270      0 --:--:-- --:--:-- --:--:-- 87837
=> nvm is already installed in /Users/jaimecoloma/.nvm, trying to update using git
=> => Compressing and cleaning up git repository

=> nvm source string already in /Users/jaimecoloma/.bashrc
=> bash_completion source string already in /Users/jaimecoloma/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion 
```

Pero cuando ejecuto la siguiente linea me dice que no existe el comando:
```jaimecoloma@MacBook-Air-de-Jaime ~ % nvm install --lts
zsh: command not found: nvm
```
Que puede ser?

**Comment by Gaonuk** [comment]
Tienes que ejecutar las 3 ultimas lineas de lo que te aparecio:
```bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
```

**Comment by jaimecoloma** [comment]
Buenisimo! ahi pude, para el paso 7 eso si yo no uso sudo, tengo homebrew y no entiendo mucho donde ejecutar e comando, abro postgres?

**Comment by Gaonuk** [comment]
Pero instalaste postgres usando el paso 4? Ahi se usa sudo. No deberias tener problemas usando ese comando en la terminal, si no podrias probar usando `psql postgres`

**Comment by jaimecoloma** [comment]
Para el paso 4 busqué la alternativa para homebrew que era similar, y voy a probar eso, pero no entendi en donde lo ejecuto, la misma consola? No caché que abrir ahora para continuar

**Comment by Gaonuk** [comment]
Todos los comandos son en la misma consola!

**Comment by jaimecoloma** [comment]
yaya voy entendiendo!
Ahora para el paso 8 siguiendo los comandos cree un proyecto pero cuando usé  ```cd <proyecto>``` como que no pasó nada, puse el ```bundle install```y no hizo nada tampoco. Eso esta bien?

**Comment by Gaonuk** [comment]
No te preocupes! Feliz de ayudar! Podrias mandar un screenshot de los pasos que estas haciendo y lo que aparece en la consola por favor!

**Comment by jaimecoloma** [comment]
![Captura de Pantalla 2020-08-29 a la(s) 17 15 42](https://user-images.githubusercontent.com/62038531/91646257-46bc8d00-ea1b-11ea-93e9-42f9dc864894.png)

Esto fue lo ultimo

**Comment by Gaonuk** [comment]
Perfecto ya entendi, el problema ahi es que es que cuando ejecutas el paso 8 entras desde tu consola, a la consola postgres donde pones la contraseña, lo que no se especifica ahi es que tienes que salir de esa consola usando `\q` y asi volver a bash donde puedes seguir con el resto de los pasos sin problemas, ojala esto sea la solucion.

**Comment by jaimecoloma** [comment]
Buenisimo! Logré avanzar hasta el paso 10, donde hay que volver a usar sudo, pero ahora no se que comando utilizar
Voy entendiendo todo!

**Comment by Gaonuk** [comment]
Fantastico, entonces para empezar postgres usando homebrew al parecer tienes que usar `brew services start postgresq`. Ve si te funciona!

**Comment by jaimecoloma** [comment]
Buenisimo! Logré terminar todos los pasos 😃 muchisimas gracias! Te pasaste la ayuda!

**Comment by Gaonuk** [comment]
Buenisimo!
