### ISSUE TITLE
ERROR Paso 8 

### ISSUE THREAD

**Issue by CarlosOlivos** [IIC2143-2020-2/syllabus#85]
No me crea bien la carpeta para el proyecto. Este es el error que me tira: 
![image](https://user-images.githubusercontent.com/37186058/91646827-6ce52b80-ea21-11ea-839f-827a622f7864.png) 
Que deberia hacer ?

**Comment by cchauriye** [comment]
Hola!

Encontré este foro que tiene algunas sugerencias de cómo solucionarlo: https://askubuntu.com/questions/1115564/wsl-ubuntu-distro-how-to-solve-operation-not-permitted-on-cloning-repository

Cuéntame cómo te va!

**Comment by daleal** [comment]
Para complementar un poco este _thread_, el problema es que la carpeta `/mnt/c` tiene un sistema de archivos `NTFS` que no soporta algunos comandos que `git` usa (`rails new` crea un repositorio de `git` junto con la app, por eso falla `git` al hacer `rails new`). Para solucionar esto, te recomiendo trabajar bajo la carpeta `~` (que es alias para `/home/<username>`, donde `<username>` es el nombre de tu usuario en wsl). Puedes moverte dentro de tus archivos mediante la consola utilizando el comando `cd` (por ejemplo, `cd ~` te llevará a la carpeta `~`, donde puedes ejecutar `rails new` sin problemas).

**Comment by CarlosOlivos** [comment]
Me resulto dirigirme a la carpeta ~ muchas gracias @daleal.

**Comment by mafernandez9** [comment]
Hola! tengo una duda con este caso, ya que no se donde se encuentran los archivos de esta carpeta. Hay algun directorio donde se almacenen? Lo digo para encontrar la carpeta de manera 'fisica' desde windows (abriendo carpetas manualmente) ya que no puedo modificar el archivo config de esta forma. Muchas gracias de antemano

**Comment by daleal** [comment]
Hola! Dentro de `wsl`, solamente puedes acceder a través de una interfaz gráfica a los archivos que están en `/mnt/c`. Todo lo que está en otro lado (por ejemplo, en `~`) solamente puede ser accedido mediante la consola, navegando con el comando `cd`. Para editar un archivo, te recomiendo abrirlo con `vscode`. Por ejemplo, si quisieras trabajar en tu proyecto del curso, tendrías que hacer `cd ~/path/to/project`. Eso te llevaría a la carpeta donde están todos los archivos de tu app de `rails`. Una vez ahí, puedes ejecutar `code .` y eso abrirá un editor de `vscode` con todos los archivos de la carpeta actual para editar. Ojalá te sirva!

**Comment by mafernandez9** [comment]
Perfect, la encontre altiro! muchas gracias. Ahora tengo otro problema con el paso 11, al momento de ejecutar rails db:create me sale algo así:
![image](https://user-images.githubusercontent.com/53874019/92207922-1ed48b80-ee58-11ea-8b3b-fb5174f7deeb.png)
y no encontré una solución en internet. Muchas gracias de antemano!

**Comment by mafernandez9** [comment]
Perfect! la encontre altiro! muchisimas graciassss
