### ISSUE TITLE
ERROR Paso 8

### ISSUE THREAD

**Issue by TdelrioC** [IIC2143-2020-2/syllabus#86]
Hola, cuando trate de hacer el paso 8 me tiro un error de que no tenia rails, cuando le puse rails -v me decia que faltaba algo por lo que tenia que reinstalar. 
<img width="1440" alt="Captura de Pantalla 2020-08-29 a la(s) 21 17 51" src="https://user-images.githubusercontent.com/52587183/91649052-682e7080-ea3d-11ea-8cb8-978aa9117d22.png">
<img width="1440" alt="Captura de Pantalla 2020-08-29 a la(s) 21 17 58" src="https://user-images.githubusercontent.com/52587183/91649056-7f6d5e00-ea3d-11ea-9424-7b6748242d5e.png">

Lo reinstalo siguiendo lo que me dice y luego me tira este error al final
<img width="1440" alt="Captura de Pantalla 2020-08-29 a la(s) 21 18 05" src="https://user-images.githubusercontent.com/52587183/91649058-8a27f300-ea3d-11ea-8cfb-6a926e9cc33b.png">

Alguien sabe que puede ser?

**Comment by daleal** [comment]
Me podrías decir qué output tienes al ejecutar `rvm list`?

**Comment by TdelrioC** [comment]
<img width="1440" alt="Captura de Pantalla 2020-08-31 a la(s) 00 22 49" src="https://user-images.githubusercontent.com/52587183/91682613-20cce080-eb20-11ea-84e1-a8a0e7f92a2c.png">
Ese es.

PD. Como pongo labels al issue? trate de hacerlo como dicen en el foro pero no me sale la caja para marcarla.
Gracias

**Comment by daleal** [comment]
Si intentas nuevamente ejecutar `rails -v`, vuelves a tener el error? Solamente el equipo docente puede etiquetar las _issues_, así que no te preocupes

**Comment by TdelrioC** [comment]
Ahora me dice que tengo rails 5.2.4

**Comment by daleal** [comment]
Excelente! Creo que debe haber sido un bug de `rvm`
