### ISSUE TITLE
Error correr postgres en la terminal (Ubuntu)

### ISSUE THREAD

**Issue by Juan379** [IIC2143-2020-2/syllabus#87]
Hola!
Antes tenia windows y cuando instalé postgres en su momento me acuerdo que se podía entrar a la consola de postgres fácilmente corriendo "psql".
Ahora, volviendo a instalar desde Ubuntu, cuando corro "psql" me tira el siguente error: **psql: error: could not connect to server: FATAL:  role "juanchi" does not exist**.

¿Alguien conoce alguna forma de  poder acceder mediante "psql"?

Gracias!

**Comment by Gaonuk** [comment]
Hola! Tienes que usar `psql postgres` para poder acceder con el usuario "postgres" que se crea por defecto y es al que le pusiste clave en los pasos a seguir de la ayudantia de set-up!

**Comment by vaperez5** [comment]
Tuve este problema también y lo logré solucionar, pero luego al momento de querer hacer consultas me aparece "ERROR:  permission denied for table users" para todas las tablas creadas. Ya traté utilizando el comando GRANT que lo vi como solución en internet y no funciona. Esto nos pasa a mi compañera y a mi, y mi otro compañero aún no puede ingresar a la bdd por lo que nadie tiene posibilidad de ver la bdd y su contenido jajaja, ojalá alguien sepa como solucionarlo, gracias!!
