### ISSUE TITLE
VSCode no autocompleta ni subraya los errores en WSL: Ubuntu

### ISSUE THREAD

**Issue by csmeneses** [IIC2143-2020-2/syllabus#9]
Hola! Instalé el WSL y Ruby en mi computador y VSCode puede correr archivos .rb y abrir la terminal de ubuntu sin problema. Sin embargo, la extensión de Ruby debería autocompletar cosas y subrayar errores y no consigo hacer que funcione.

Éstas son las extensiones que instalé:
![image](https://user-images.githubusercontent.com/48298696/90324418-a9525b00-df3c-11ea-9e31-75927d5b7bd8.png)
La ultima extensión dice que está "habilitada localmente pero no en WSL: Ubuntu" y no me da la opción de habilitarla, probablemente ese es el problema. Ayuda :(

**Comment by jerosalazar** [comment]
Hola! Me parece que la extensión de ruby solo agrega la sintaxis del lenguaje a VSCode, para que te subraye errores debes instalar un linter y para el autocompletado debes instalar una extensión de snippets, así que busca extensiones para ambas cosas. Espero que te sirva!

**Comment by csmeneses** [comment]
Le instalé Ruby Solargraph y Rubocop. Ahora autocompleta y subraya perfect. Muchas gracias!
