### ISSUE TITLE
Uso de Rubocop

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2143-2020-2/syllabus#91]
Hola!Para usar instalar la gema rubocop me guíe de esta página https://github.com/rubocop-hq/rubocop pero ahí me menciona dos métodos de los cuales me generan dudas , si lo instalo con gem install rubocop desde mi consola tendría el rubocop para todos los proyectos que podría crear ? y usando el segundo método me refiero a hacer  gem 'rubocop', require: false en el gemfile del proyecto en cuestión , en ese caso solo en ese proyecto podría usar el rubocop? y además hay que dejar una documentación o algo así acerca de que versión de rubocop se uso?

**Comment by johnowenatala** [comment]
En general siempre las gemas te dicen que puedes instalarlas de esas dos formas:

a) gem install XXXXXX
b) incluirlo en Gemfile como gem XXXXXX ,...

En Rails tu manejarás todas las gemas con bundler, por lo que debes ponerlo en el Gemfile.

Algunos datos útiles: 
* Cualquier gema que instales que no incluyas en el Gemfile, no se cargará automáticamente en Rails 
* Incluso se cargas manualmente la gema, tus compañeros no podrán usarla a no ser que les indiques qué gema y versión instalaste.

**Comment by RonaldoSosa** [comment]
Entendido! Solo para estar seguro si quiero señalar la versión de la gema se haría de la siguiente forma:
 **gem 'rubocop', '~> 0.89.1'**

**Comment by johnowenatala** [comment]
Si, pero no es necesario, pues al instalar la gema la primera vez (bundle install), la versión exacta instalada se guarda en el archivo Gemfile.lock . En adelante, bundle install se encarga que se instal exactamente la versión en Gemfile.lock

En todo caso, ~> 0.89.1 lo que indica es cualquier version 0.89.x mayor o igual a la 0.89.1. Si quisieras fijar la versión, es con =0.89.1

**Comment by RonaldoSosa** [comment]
Yaaaa ahora me quedo claro gracias!
