### ISSUE TITLE
Problemas instalacion - Paso 7

### ISSUE THREAD

**Issue by IvaniaArias** [IIC2143-2020-2/syllabus#92]
Holaa! Pasa que aun no puedo instalar todas las cosas del curso :( Tampoco pude ir a la ayudantía :((
Estoy siguiendo las instrucciones y en el paso 7 me aparece esto
![Captura de pantalla (586)](https://user-images.githubusercontent.com/61998881/91793816-4d97fb00-ebe7-11ea-883f-fbe98d941c19.png)

Abri una nueva consola para intentarlo de nuevo y al poner \password me salió de nuevo lo mismo :(  Si me pueden ayudan por fis :(

**Comment by daleal** [comment]
#59
