### ISSUE TITLE
error en paso 2 [mac]

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2143-2020-2/syllabus#95]
Hola! Estoy siguiendoo los pasos de "setup" y en el paso 2 me tira error. Al poner el comando sudo apt-get build-essential patch liblzma-dev libpq-dev me tira error en mi mac. Busque en google y salía que apt-get no está para Mac y que lo haga con "brew". Eso si también con brew me tira error. Error: No available formula with the name "build-essential"

**Comment by johnowenatala** [comment]
Esas instrucciones son sólo para linux. No sé si hay un conjunto de pasos recomendados para Mac.
En todo caso, te doy algunos tips (acá voy a revelarme contra el uso de RVM que han puesto en todos lados, si lo ve algún ayudante y quiere corregir estos pasos usando rvm, es bienvenido):

1. Instala homebrew (https://docs.brew.sh/Installation)
2. Instala postgres (brew install postgresql)
3. Instala rbenv (brew install rbenv)
4. Instala ruby (rbenv install 2.6.5)
5. Usa ruby 2.6.5 (rbenv local 2.6.5)
6. Instala rails (gem install rails)
7. Crea tu proyecto y configuralo (rails new nombre_proyecto --database=postgresql --skip-test)

Prueba con estos pasos y cuéntame como te va.

**Comment by jerosalazar** [comment]
Hola! @sebaelsaca te funcionó?

**Comment by sebaelsaca** [comment]
Holaaa, @jerosalazar @johnowenatala  no me funcionó la parte de instalar rails y cachee que era porque faltaba setear el ruby de rbenv como default y no el del sistema. Encontré un tutorial bueno de donde se puede setear ruby para que cada vez que se abra el terminal este con el de rbenv en https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-macos
