### ISSUE TITLE
Error al intentar iniciar postgres

### ISSUE THREAD

**Issue by FelipeA7** [IIC2143-2020-2/syllabus#96]
Hola, estaba intentando meterme a postgresql y me sale un error al tratar de iniciarlo.
![error](https://user-images.githubusercontent.com/48482398/91913854-9fdb2980-ec84-11ea-87a7-0335c5d14f20.png)

Qué significa esto? Ya había creado un proyecto hace un par de días y había terminado todos los pasos del setup sin problemas, pero ahora me sale esto.
**EDIT:** lo pude arreglar :), era porque había cambiado un archivo sin querer.

**Comment by johnowenatala** [comment]
prueba este comando y cuéntame si te ayuda:

`psql --help `
