### ISSUE TITLE
Instalación automática de rails 6.0.3.2

### ISSUE THREAD

**Issue by Daniel-SebastianGaete** [IIC2143-2020-2/syllabus#97]
Hola, ¿Es normal que al crear un nuevo proyecto de rails se instale automáticamente la última versión de rails?
Revisé hoy mi versión de rails y me encontré que tenía la versión 6.0.3.2, la que no había instalado. La desinstalé y luego al crear un proyecto de prueba se instaló automáticamente de nuevo.

**Comment by johnowenatala** [comment]
Esto te debiera ayudar:

# instalar la versión específica de rails
gem install rails -v 5.2.3

# decirle que use esa version
rails _5.2.3_ new ...

Cuéntame cómo te va.

**Comment by Daniel-SebastianGaete** [comment]
Parece que todo anda bien (sigue estando la versión 6 por ahí, pero no debería molestar).
