### ISSUE TITLE
Error al instalar rvm

### ISSUE THREAD

**Issue by mafernandez9** [IIC2143-2020-2/syllabus#98]
Hola!
Quería hacer una consulta, ya que al momento de intentar instalar rvm en wsl, con el comando que aparece en la guía de setup:
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
me tira el siguiente error: gpg: keyserver receive failed: No name
En caso de preferir un pantallazo de mi consola, lo adjuntaré apenas me digan. Muchas gracias de antemano!

**Comment by johnowenatala** [comment]
Intenta con este:

`
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
`

**Comment by mafernandez9** [comment]
Buenísimo, muchas gracias! me funcionó altiro. Ahora me sale otro error en el Paso 9, donde me sale:
error: chmod on /mnt/c/Users/Matías/desktop/carpeta/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'
y no entiendo el error :c muchas gracias de antemano!

**Comment by johnowenatala** [comment]
No te entiendo. El paso 9 es escribir en un archivo (database.yml). ¿Cómo te sale un error al escribir en un archivo?

**Comment by daleal** [comment]
Hola @mafernandez9! Puedes encontrar la solución (y la razón) de tu problema en #85. Saludos!
