### ISSUE TITLE
'rvm' not found

### ISSUE THREAD

**Issue by Camila-sty** [IIC2143-2020-2/syllabus#99]
Hola. Voy en el paso 5 de la guia setup y al poner en la consola "rvm install 2.6" me tira lo siguiente:
![image](https://user-images.githubusercontent.com/59337116/92176463-806f0880-ee0c-11ea-9b41-1e2e96421fe3.png)

Qué podría estar fallando?, se supone que ya se instaló rvm...

**Comment by daleal** [comment]
Hola! Por alguna razón no encuentra el comando `rvm` en tu `PATH`. Se me ocurren varias razones. La primera es que hayas instalado `rvm` dentro de wsl y estés ejecutando ese comando en PowerShell. La segunda es que no hayas cerrado y abierto la consola luego de instalar `rvm`. La tercera es que no se haya agregado bien `rvm` al `PATH`. Podrías confirmarme si alguna de las primeras dos situaciones es la tuya?

**Comment by Camila-sty** [comment]
La primera es mi situación..

**Comment by daleal** [comment]
Dentro de PowerShell, entras primero a wsl antes de intentar ejecutar `rvm`?

**Comment by Camila-sty** [comment]
sí

**Comment by daleal** [comment]
Necesito que me digas qué sucede cuando ejecutas lo siguiente:

```sh
source ~/.rvm/scripts/rvm

rvm --help
```

**Comment by Camila-sty** [comment]
![image](https://user-images.githubusercontent.com/59337116/92189347-6b09d680-ee2c-11ea-9ee3-03240dd89146.png)
![image](https://user-images.githubusercontent.com/59337116/92189368-7826c580-ee2c-11ea-9054-3beb027cc53e.png)

**Comment by daleal** [comment]
Excelente. Puedes ahora por favor mostrarme el output de `echo $SHELL`?

**Comment by Camila-sty** [comment]
![image](https://user-images.githubusercontent.com/59337116/92189701-524df080-ee2d-11ea-89af-596f20f31dfa.png)

**Comment by daleal** [comment]
Ya, haremos lo siguiente. Ejecuta el siguiente comando:

```sh
nano ~/.bashrc
```

Eso abrirá un editor de texto en tu consola con un archivo con muchas cosas sin sentido. Con la flechita de tu teclado, baja hasta la última línea. Ahí, escribe lo siguiente:

```sh
source ~/.rvm/scripts/rvm
```

Luego de eso, apreta `ctrl + X`. Te pedirá una confirmación, que aceptarás apretando la tecla `Y` de tu teclado. Una vez hecho todo esto, cierra tu terminal, y al abrirlo de nuevo, deberías tener `rvm` reconocido para siempre 🎉

**Comment by Camila-sty** [comment]
![image](https://user-images.githubusercontent.com/59337116/92191996-0e5dea00-ee33-11ea-9268-9cbab3b4e19e.png)
 esta bien ahí? cómo lo ejecuto? aprieto enter pero no me lo toma...

**Comment by daleal** [comment]
Aprieta `ctrl + X` y luego la tecla `Y`

**Comment by Camila-sty** [comment]
Perfecto 😄 muchas gracias!
